#!/bin/bash

# Here I have merged two little scripts from
# BudRich https://github.com/budlabs
# Dependency: rofi
# Opens a rofi menu to create/edit a script,
# in your favorite text editor

[[ -z ${SCRIPTDIR+x} ]] && exit 1

_autoscript() {

    local script_file

    script_file="$SCRIPTDIR/$1"

    if [[ -f $script_file ]]; then
        $EDITOR "$script_file" &
    else
        echo "#!/bin/bash" > "$script_file"
        chmod +x "$script_file"
        $EDITOR "$script_file" &
    fi
}

selected=$(ls "$SCRIPTDIR" | rofi \
                            -normal-window \
                            -dmenu \
                            -width 30 \
                            -hide-scrollbar \
                            -line-padding  \
                            -padding 20 \
                            -lines 10 \
                            -p "edit/create a script ")
[[ -z $selected ]] && exit

_autoscript "$selected"
