#!/usr/bin/env bash

# User systemd services.
systemctl --user start {mpv-ipc,mpd}

# Apply the lastest wallpaper
if [[ -n $(command -v nitrogen) ]]; then
    nitrogen --restore &
else
    sh -c "$XDG_CONFIG_HOME"/.fehbg
fi

# Sound
pulsemixer --set-volume 50 &
amixer set Capture,0 0%,0% mute nocap >/dev/null 2>&1

# Other settings
if [[ -n $(pidof bspwm) ]]; then
    launch_polybar
    nm-applet &
elif [[ -n $(pidof i3) ]]; then
    launch_polybar
    nm-applet &
else
    notify-send 'This is Awesome'
fi

cleanup &
rsync -apq "$SCRIPTDIR"/* ~/Documents/scripts/ &
rsync -apq --exclude 'VirtualBox' "$XDG_CONFIG_HOME"/* ~/Documents/configs/CONFIGS/ &

# Updates script
sleep 15s && updates-viewer --updates
