#!/usr/bin/env bash

echo -n "<i class='fa fa-$(curl -s https://raw.githubusercontent.com/wstam88/rofi-fontawesome/master/icon-list.txt \
    | rofi -dmenu -i -markup-rows -p "select an icon" -columns 4 -width 100 -location 1 -lines 20 -bw 2 -yoffset -2 \
    | cut -d\' -f2 )'></i>" | xclip -selection clipboard && xdotool key ctrl+shift+v
