#!/bin/bash

# Author: Barret E <archus@protonmail.com>
# github directory: https://github.com/archusXIV/wm_config
# Youtube channel: <https://www.youtube.com/@linuxinfrench9388>

# Colors
nc=$'\e[0;m';
g=$'\e[1;32m';
r=$'\e[0;31m';
y=$'\e[93m';

git clone https://github.com/archusXIV/wm_config.git
cd wm_config/ || exit 1

_i3Config() {
    ls -la
    echo "Hello World! this is i3"
}

_bspwmConfig() {
    
    local SYSCONFDIR USERCONFDIR
    
    SYSCONFDIR="/usr/share/doc/bspwm/examples"
    USERCONFDIR="/home/${usrname}/.config"
    
    printf '%s\n' " ${y}Configuring BSPWM.${nc}"
    sleep 1s
    if [[ -d $SYSCONFDIR ]]; then
        sudo rm -rf "$USERCONFDIR"
        mkdir --parents "$USERCONFDIR"/{bspwm,sxhkd}
        cp -f "$SYSCONFDIR"/bspwmrc "$USERCONFDIR"/bspwm/
        chmod +x "$USERCONFDIR"/bspwm/bspwmrc
        echo "setxkbmap $KBD" >> "$USERCONFDIR"/bspwm/bspwmrc
        echo "polybar example &" >> "$USERCONFDIR"/bspwm/bspwmrc
        cp -f "$SYSCONFDIR"/sxhkdrc "$USERCONFDIR"/sxhkd/
        killall polybar sxhkd
        bspc wm -r
    else
        printf '%s\n' " ${r}You will have to configure Bspwm.${nc}"
        sleep 3s
    fi
    
}

clear
read -r -p "${g}"' Window manager config to install: [I]3wm, [B]spwm '"${nc}" wm
case "$wm" in
    i|I) _i3Config ;;
    b|B) _bspwmConfig ::
esac
