#!/bin/bash

# Author: Barret E <archus@protonmail.com>
# github directory: https://github.com/archusXIV/wm_config
# Youtube channel: <https://www.youtube.com/@linuxinfrench9388>

# Colors
nc=$'\e[0;m';
g=$'\e[1;32m';
r=$'\e[0;31m';
y=$'\e[93m';

git clone https://github.com/archusXIV/wm_config.git
cd wm_config/ || exit 1

read -r -p "${g}"' Enter your user name: '"${nc}" usrname

KBD=$(sed 's/KEYMAP=//;s/-.*//' /etc/vconsole.conf | sed -n '1p')
SYSCONFDIR="/usr/share/doc/bspwm/examples"
USERCONFDIR="/home/${usrname}/.config"
USERLOCALDIR="/home/${usrname}/.local"

_i3Config() {
    ls -la
    echo "Hello World! this is i3"
}

_bspwmConfig() {
    
    printf '%s\n' " ${y}Configuring BSPWM.${nc}"
    sleep 1s
    if [[ -d $SYSCONFDIR ]]; then
        cp -rf * .. && cd .. \
        && mv config "$USERCONFDIR" \
        && chmod +x "$USERCONFDIR"/bspwm/bspwmrc \
        && mv local "$USERLOCALDIR" \
        && chmod +x "$USERLOCALDIR"/bin/* \
        && echo "setxkbmap $KBD" >> "$USERLOCALDIR"/bin/autostart \
        && cp -r wallpapers ~/Documents/ \
        && rm -rf wm_config \
        && printf '%s\n' " ${y}Rebooting...${nc}" \
        && sleep 2s && reboot
    else
        printf '%s\n' " ${r}You will have to configure Bspwm.${nc}"
        sleep 3s
    fi
    
}

clear
read -r -p "${g}"' Window manager config to install: [I]3wm, [B]spwm '"${nc}" wm
case "$wm" in
    i|I) _i3Config ;;
    b|B) _bspwmConfig ::
esac
