#!/bin/bash

# Author: Barret E <archus@protonmail.com>
# github directory: https://github.com/archusXIV/wm_config
# Youtube channel: <https://www.youtube.com/@linuxinfrench9388>

# Colors
nc=$'\e[0;m';
g=$'\e[1;32m';
r=$'\e[0;31m';
y=$'\e[93m';

[[ -d ~/.config ]] && rm -rf  ~/.config
[[ -d ~/.local ]] && rm -rf  ~/.local

git clone https://github.com/archusXIV/wm_config.git
cd wm_config/ || exit 1

read -r -p "${g}"' Enter your user name: '"${nc}" usrname

KBD=$(sed 's/KEYMAP=//;s/-.*//' /etc/vconsole.conf | sed -n '1p')
BSPCONFDIR="/usr/share/doc/bspwm/examples"

_i3Config() {
    ls -la
    echo "Hello World! this is i3"
}

_bspwmConfig() {
    
    printf '%s\n' " ${y}Configuring BSPWM.${nc}"
    sleep 1s
    if [[ -d $BSPCONFDIR ]]; then
        mv config .config \
        && chmod +x .config/bspwm/bspwmrc \
        && mv local .local \
        && chmod +x .local/bin/* \
        && echo "setxkbmap $KBD" >> .local/bin/autostart \
        && mv -f .local .. && mv -f .config .. \
        && mv -f wallpapers ~/Documents/ \
        && chmod +x .fehbg \
        && mv -f .{bash_profile,bashrc,zshenv,zshrc,fehbg,xinitrc,Xresources} .. \
        && echo "exec bspwm" >> ~/.xinitrc \
        && cd ~ && rm -rf wm_config \
        && printf '%s\n' " ${y}Bspwm configured, rebooting...${nc}" \
        && sleep 2s && reboot
    else
        printf '%s\n' " ${r}You will have to configure Bspwm.${nc}"
        sleep 3s
    fi
    
}

clear
read -r -p "${g}"' Window manager config to install: [I]3wm, [B]spwm: '"${nc}" wm
case "$wm" in
    i|I) _i3Config ;;
    b|B) _bspwmConfig ::
esac
