#!/bin/bash

# Optional dependency 'polybar'

duration="$(cmus-remote -Q 2> /dev/null | awk '/duration/{print $2}')"
artist=""
title=""
file=""
status="stopped"

# dollar sign isn't necessary in arithmetic test. (( ${duration} >= 3600 ))
if (( duration >= 3600 )); then
    hours=$(printf "%02d" $((duration / 3600)))
    minutes=$(printf "%02d" $((duration / 60 - 60)))
    seconds=$(printf "%02d" $((duration % 60)))
    total_time=" |  ${hours}:${minutes}:${seconds}"
elif (( duration < 3600 )); then
    minutes=$(printf "%02d" $((duration / 60)))
    seconds=$(printf "%02d" $((duration % 60)))
    total_time=" |  ${minutes}:${seconds}"
fi

while [[ $1 != "" ]]; do
    case "$1" in
        title) title="$2"
        ;;
        artist) artist="$2"
        ;;
        status) status="$2"
        ;;
        file) file="$2"
        ;;
    esac
    shift
    shift
done

msg=""

if [[ ${status} = 'stopped' ]]; then
    msg=""
else

    if [[ ${status} = 'paused' ]]; then
        msg="%{F$(xrdb -query | awk '/color4:/{print $NF}')}${msg}"
    fi

    if [[ -n ${artist} ]]; then
        msg="${msg} ${artist}"
    fi

    if [[ -n ${title} ]]; then
        msg="${msg} - ${title} ${total_time}"
    else
        if [[ -n ${file} ]]; then
            msg="${msg} $(basename "${file%.*}") ${total_time}"
        else
            msg=""
        fi
    fi

fi

output="$XDG_RUNTIME_DIR/music_player_output.txt"
echo "${msg}" > "${output}"

sleep 0.2

if [[ -n $(pidof bspwm) ]]; then
    polybar-msg -p "$(pgrep --full bspwm-bar-2)" \
    action "#music_player-ipc.hook.2" >/dev/null 2>&1
elif [[ -n $(pidof i3) ]]; then
    polybar-msg -p "$(pgrep --full i3-bar-2)" \
    action "#music_player-ipc.hook.2" >/dev/null 2>&1
else
    notify-send "$(cat "${output}")"
fi
