#!/bin/bash

for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done

echo

for fgbg in 38 48 ; do # Foreground / Background
    for color in {0..255} ; do # Colors
        # Display the color
        printf "\e[${fgbg};5;%sm  %3s  \e[0m" "$color" "$color"
        # Display 6 colors per lines
        if [ $(((color + 1) % 6)) == 4 ] ; then
            echo # New line
        fi
    done
    echo # New line
done
