#!/bin/env bash

_usage() {
    echo ""
    echo "Convert hex color code to RGB and RGB to HEX (Hexadecimal)"
    echo "Usage: color_convert [HEX] or [RGB] color value"
    echo "[HEX] example: color_convert 000000"
    echo "[RGB] example color_convert 0,0,0"
    echo ""
    echo "Can also convert ~/.Xresources color values"
    echo "(if you defined black as #000000)"
    echo "Example color_convert black; will be (0, 0, 0)"
    echo "Or: color_convert 0; where '0' is color0"
    echo ""
    exit
}

if [ $# -eq 0 ]; then
    echo 'Invalid color value!';
    _usage;
fi

if [[ $1 =~ ([[:xdigit:]]{2})([[:xdigit:]]{2})([[:xdigit:]]{2}) ]]; then
    printf "(%d, %d, %d)\n" \
           0x"${BASH_REMATCH[1]}" 0x"${BASH_REMATCH[2]}" 0x"${BASH_REMATCH[3]}"
    elif [[ $1 =~ ([[:digit:]]{1,3}),([[:digit:]]{1,3}),([[:digit:]]{1,3}) ]]; then
        printf "#%02x%02x%02x\n" \
                "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" "${BASH_REMATCH[3]}"
fi

_convert() {
    if [[ $1 =~ ([[:xdigit:]]{2})([[:xdigit:]]{2})([[:xdigit:]]{2}) ]]; then
    printf "(%d, %d, %d)\n" \
           0x"${BASH_REMATCH[1]}" 0x"${BASH_REMATCH[2]}" 0x"${BASH_REMATCH[3]}"
    elif [[ $1 =~ ([[:digit:]]{1,3}),([[:digit:]]{1,3}),([[:digit:]]{1,3}) ]]; then
        printf "#%02x%02x%02x\n" \
                "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" "${BASH_REMATCH[3]}"
    fi
}


case "$1" in
   foreground|fg)    _convert $(xrdb -query | awk '/foreground:/{print $2}' | sed 's/#//');;
   background|bg)    _convert $(xrdb -query | awk '/background:/{print $2}' | sed 's/#//');;
   black|blk|0)      _convert $(xrdb -query | awk '/color0:/{print $2}' | sed 's/#//');;
   red|1)            _convert $(xrdb -query | awk '/color1:/{print $2}' | sed 's/#//');;
   green|grn|2)      _convert $(xrdb -query | awk '/color2:/{print $2}' | sed 's/#//');;
   yellow|ylw|3)     _convert $(xrdb -query | awk '/color3:/{print $2}' | sed 's/#//');;
   blue|blu|4)       _convert $(xrdb -query | awk '/color4:/{print $2}' | sed 's/#//');;
   magenta|mag|5)    _convert $(xrdb -query | awk '/color5:/{print $2}' | sed 's/#//');;
   cyan|cyn|6)       _convert $(xrdb -query | awk '/color6:/{print $2}' | sed 's/#//');;
   white|wht|7)      _convert $(xrdb -query | awk '/color7:/{print $2}' | sed 's/#//');;
   black2|blk2|8)    _convert $(xrdb -query | awk '/color8:/{print $2}' | sed 's/#//');;
   red2|9)           _convert $(xrdb -query | awk '/color9:/{print $2}' | sed 's/#//');;
   green2|grn2|10)   _convert $(xrdb -query | awk '/color10:/{print $2}' | sed 's/#//');;
   yellow2|ylw2|11)  _convert $(xrdb -query | awk '/color11:/{print $2}' | sed 's/#//');;
   blue2|blu2|12)    _convert $(xrdb -query | awk '/color12:/{print $2}' | sed 's/#//');;
   magenta2|mag2|13) _convert $(xrdb -query | awk '/color13:/{print $2}' | sed 's/#//');;
   cyan2|cyn2|14)    _convert $(xrdb -query | awk '/color14:/{print $2}' | sed 's/#//');;
   white2|wht2|15)   _convert $(xrdb -query | awk '/color15:/{print $2}' | sed 's/#//');;
   -h|--help)        _usage;;
esac
