#!/usr/bin/env bash
##   Author: Barret E (2021) <archus@protonmail.com>
##   A simple colors converter. hex->rgb or rgb->hex

_usage() {
    printf '%s\n' \
    " Convert hex color code to RGB and RGB to HEX (Hexadecimal)" \
    " Usage: color_convert [HEX] or [RGB] color value" \
    " [HEX] example: color_convert 000000" \
    " [RGB] example color_convert 0,0,0" \
    "" \
    " Can also convert ~/.Xresources color values" \
    " (if you defined black as #000000)" \
    " Example color_convert black; will be (0, 0, 0)" \
    " Or: color_convert 0; where '0' is color0" \
    ""
    exit
}

if [[ $# -eq 0 ]]; then
    echo -e " Invalid color value, or value is empty!\n"
    _usage
fi

_getXresColors() {
    local color="$1"
    xrdb -query \
    | awk -v colour="$color" '
        $0 ~ colour ":" { sub("[#]","",$2); print $2 }
    '
}

# Prints the RGB triplet colorized with its own truecolor background.
_rgb=""

_colorized() {
    local r g b

    if [[ $1 =~ ([[:xdigit:]]{2})([[:xdigit:]]{2})([[:xdigit:]]{2}) ]]; then
        r=$((16#${BASH_REMATCH[1]}))
        g=$((16#${BASH_REMATCH[2]}))
        b=$((16#${BASH_REMATCH[3]}))
        _rgb="($r, $g, $b)"
        printf '\e[48;2;%d;%d;%dm  %s  \e[0m\n' "$r" "$g" "$b" "$_rgb"
    fi
}

# Prints the HEX code colorized with its own truecolor background.
_rgbToHex() {
    local r g b

    if [[ $1 =~ ([[:digit:]]{1,3}),([[:digit:]]{1,3}),([[:digit:]]{1,3}) ]]; then
        r="${BASH_REMATCH[1]}"
        g="${BASH_REMATCH[2]}"
        b="${BASH_REMATCH[3]}"
        printf '\e[48;2;%d;%d;%dm  #%02x%02x%02x  \e[0m\n' "$r" "$g" "$b" "$r" "$g" "$b"
    fi
}

if [[ $1 =~ ([[:xdigit:]]{2})([[:xdigit:]]{2})([[:xdigit:]]{2}) ]]; then
    _colorized "$1"
    exit 0
elif [[ $1 =~ ([[:digit:]]{1,3}),([[:digit:]]{1,3}),([[:digit:]]{1,3}) ]]; then
    _rgbToHex "$1"
    exit 0
fi

case "$1" in
    foreground|fg)    _colorized "$(_getXresColors foreground)" ;;
    background|bg)    _colorized "$(_getXresColors background)" ;;
    black|blk|0)      _colorized "$(_getXresColors color0)" ;;
    red|1)            _colorized "$(_getXresColors color1)" ;;
    green|grn|2)      _colorized "$(_getXresColors color2)" ;;
    yellow|ylw|3)     _colorized "$(_getXresColors color3)" ;;
    blue|blu|4)       _colorized "$(_getXresColors color4)" ;;
    magenta|mag|5)    _colorized "$(_getXresColors color5)" ;;
    cyan|cyn|6)       _colorized "$(_getXresColors color6)" ;;
    white|wht|7)      _colorized "$(_getXresColors color7)" ;;
    black2|blk2|8)    _colorized "$(_getXresColors color8)" ;;
    red2|9)           _colorized "$(_getXresColors color9)" ;;
    green2|grn2|10)   _colorized "$(_getXresColors color10)" ;;
    yellow2|ylw2|11)  _colorized "$(_getXresColors color11)" ;;
    blue2|blu2|12)    _colorized "$(_getXresColors color12)" ;;
    magenta2|mag2|13) _colorized "$(_getXresColors color13)" ;;
    cyan2|cyn2|14)    _colorized "$(_getXresColors color14)" ;;
    white2|wht2|15)   _colorized "$(_getXresColors color15)" ;;
    -h|--help)        _usage ;;
esac
