#!/usr/bin/env bash

rc="$HOME/.config/dmenu/dmenurc"

[ -f "$rc" ] && . "$rc"

confDir="$HOME/.config/"

dirOptions=$(cd ${confDir} && ls -d */ | cut -d " " -f 1)
dirChoice=$(echo "${dirOptions[@]}" | dmenu -i $DMENU_OPTIONS -p 'Config directories: ')
fileOptions=$(cd ${confDir}${dirChoice} && ls -Ap | cut -d " " -f 1 | grep -v / )
fileChoice=$(echo "${fileOptions[@]}" | dmenu -i -l 10 $DMENU_OPTIONS -p 'Edit this file: ')
    
if [ -z "$dirChoice" ]; then
    exit 0
else
    [ -z "$fileChoice" ] && exit 0 \
    || exec geany ${confDir}${dirChoice}${fileChoice}
fi
