#!/bin/bash

rc="$HOME/.config/dmenu/dmenurc"

[ -f "$rc" ] && . "$rc"

if [[ -n $(pidof bspwm) ]]; then
    awk '/^[a-zA-Z]/ \
    && last {print $0,"\t",last} \
    {last=""} /^#/{last=$0}' \
    ~/.config/bspwm/bsp_sxhkdrc_memo \
    | column -t -s $'\t' \
    | dmenu -i -l 15 $DMENU_OPTIONS -p 'Sxhkd memo '
    exit 0
elif [[ -n $(pidof i3) ]]; then
    awk '/^[a-zA-Z]/ \
    && last {print $0,"\t",last} \
    {last=""} /^#/{last=$0}' \
    ~/.config/i3/i3_sxhkdrc_memo \
    | column -t -s $'\t' \
    | dmenu -i -l 15 $DMENU_OPTIONS -p 'Sxhkd memo '
    exit 0
else
    echo "no bspwm or i3 session running" && exit 1
fi
