#!/usr/bin/env bash

# command ls | fzf --reverse --bind "enter:become(echo {} && ffmpeg_tagger {})"
err() {
    cat <<'USAGE'
    ffmpeg_tagger [OPTIONS] <file>
    Options:
        -a: artist/author
        -A: album/book title
        -c: comment
        -g: genre
        -n: track/chapter number
        -N: total number of tracks/chapters
        -t: song/chapter title
        -y: year of publication
    You will be prompted for title, artist, and album if not given.
USAGE
    exit 1
}

while getopts "a:A:c:g:n:N:t:y:" tag; do
    case "${tag}" in
        a) artist="${OPTARG}" ;;
        A) album="${OPTARG}" ;;
        c) comment="${OPTARG}" ;;
        g) genre="${OPTARG}" ;;
        n) track="${OPTARG}" ;;
        N) total="${OPTARG}" ;;
        t) title="${OPTARG}" ;;
        y) date="${OPTARG}" ;;
        *) printf "Invalid option: -%s\\n" "$OPTARG" && err ;;
    esac
done

shift $((OPTIND - 1))

file="$1"

temp="$(mktemp -p "$(dirname "$file")")"
trap 'rm -f $temp' SIGHUP SIGINT SIGQUIT SIGTERM SIGPWR EXIT

[[ ! -f $file ]] && echo -e "\n    Provide a file to ${0##*/}.\n" && err
[[ -z $title ]] && echo -e "\n Enter a title." && read -r title
[[ -z $artist ]] && echo -e "\n Enter an artist." && read -r artist
[[ -z $album ]] && echo -e "\n Enter an album." && read -r album
[[ -z $track ]] && track=1
[[ -z $comment ]] && comment="tagged with ffmpeg"

cp -f "$file" "$temp" && ffmpeg -i "$temp" -map 0 -y -codec copy \
    -metadata title="$title" \
    -metadata album="$album" \
    -metadata artist="$artist" \
    -metadata track="${track}${total:+/"$total"}" \
    ${date:+-metadata date="$date"} \
    ${genre:+-metadata genre="$genre"} \
    ${comment:+-metadata comment="$comment"} "$file" >/dev/null 2>&1 && \
echo " ${file##*/} tagged successfully"
