#!/bin/bash

file="$1"
filename="${file%.*}"
extension="${file##*.}"

segment() {
    while true; do
        echo "Would you like to cut out a segment ?"
        echo -e "1) Yes\n2) No\n3) Quit"
        read CHOICE
        if [ "$CHOICE" == "3" ]; then
            exit
        elif [ "$CHOICE" == "2" ]; then
            clear
            break
        elif [ "$CHOICE" == "1" ]; then
            clear
            ((segments++))
            echo "What time does segment $segments starts ?"
            read SEGSTARTS
            clear
            echo -e "Segment $segments start set to $SEGSTARTS\n"
            echo "What time does segment $segments end ?"
            read SEGENDS
            clear
            echo -e "Segment $segments ends set to $SEGENDS\n"
            break
        else
            clear
            echo -e "Bad option"
            segment "$segments"
        fi
    done

    if [ "$CHOICE" == "1" ]; then
        echo "Cutting file $file video segment $segments starting at $SEGSTARTS and ending at $SEGENDS"
        ffmpeg -i "$file" -ss $SEGSTARTS -to $SEGENDS \
        -map 0:0 -map 0:1 -c:a copy -c:v copy  "$filename-part$segments.$extension"
        clear
        echo -e "Cut file $filename-part$segments.$extension starting at $SEGSTARTS and ending at $SEGENDS\n"
        segment "$segments"
    fi
}

concat() {
    if [[ -n $(find . -name "*.mp4" -o -name "*.mkv") ]]; then
        if [[ -n $(find . -depth -name "* *") ]]; then
            find . -depth -name "* *" -exec \
            bash -c '
                for f in "$@"; do
                    n="${f##*/}"
                    mv -nv "$f" "${f%/*}/${n// /_}"
                done
            ' dummy {} +
        fi
        find . -name "*.mp4" -o -name "*.mkv" \
        | sed 's:\ :\ :g;s/^/file /' \
        | sort -d > files.txt
        ffmpeg -safe 0 -f concat -i files.txt -c copy "$1"
        rm files.txt
        mv "$1" .. >/dev/null
    else
        echo "No mp4 or mkv file found..." && exit 1
    fi
}

clear
segments=0
segment "$segments"
clear

if (("$segments"==1)); then
    mv $filename"-part1."$extension "$filename-segmented.$extension"
elif (("$segments">1)); then
    echo "Would you like to join the segments into one file ?"
    OPTIONS="Yes No Quit"
    select opt in $OPTIONS; do
        clear
        if [ "$opt" == "Quit" ]; then
            exit
        elif [ "$opt" == "Yes" ]; then
            mv "$file" .. >/dev/null
            clear
            echo "Please set a new filename:"
            read NAME
            echo "Joining segments"
            concat "$NAME"
            clear
            echo "Would you like to delete the part files ?"
            select opt in $OPTIONS; do
                clear
                if [ "$opt" == "Quit" ]; then
                    exit
                elif [ "$opt" == "Yes" ]; then
                    rm *
                    break
                elif [ "$opt" == "No" ]; then
                    break
                else
                    clear
                    echo -e "Bad option\n"
                fi
            done
            break
            clear
        elif [ "$opt" == "No" ]; then
            exit
        else
            clear
            echo -e "Bad option\n"
        fi
    done
fi

