#!/bin/bash

file="$1"
filename="${file%.*}"
extension="${file##*.}"
duration=$(ffmpeg -i "$1" 2>&1 | awk '/Duration/{print substr($2, 1, length($2)-4)}')

_Segmentize() {
    while true; do
        printf '\n'
        echo -e "\n Duration = $duration\n make sure this directory contains only one file."
        read -rsn 1 -p ' Would you like to cut out a segment? [Y/n] or [Q]uit: ' CHOICE
        case "$CHOICE" in
            q|Q)
                clear; exit
            ;;
            n|N)
                clear; break
            ;;
            y|Y*)
                ((segments++))
                printf '\n'
                read -r -p " What time does the segment ${segments} starts?: " START
                echo -e "\n Segment ${segments} start at $START\n"
                read -r -p " What time does segment ${segments} ends?: " END
                echo -e "\n Segment ${segments} ends at $END\n"
                if [[ -n $START && -n $END ]]; then
                    printf '%s\n' " Cutting ${file} video segment ${segments}" \
                    " starting at ${START}, ending at ${END}"; sleep 1
                    ffmpeg \
                    -i "${file}" \
                    -ss "${START}" \
                    -to "${END}" \
                    -map 0:0 \
                    -map 0:1 \
                    -c:a copy \
                    -c:v copy  "${filename}-part${segments}.${extension}" >/dev/null 2>&1
                    sleep 1
                    clear
                    printf '\n%s\n' " segment ${segments} done"
                else
                    continue
                fi
            ;;
            *)
                printf '\n'
                echo -e " Bad option\n"
            ;;
        esac

    done

    
}

_Concatentate() {
    if [[ -n $(find . -name "*.mp4" -o -name "*.mkv") ]]; then
        if [[ -n $(find . -depth -name "* *") ]]; then
            find . -depth -name "* *" -exec \
            bash -c '
                for f in "$@"; do
                    n="${f##*/}"
                    mv -nv "$f" "${f%/*}/${n// /_}"
                done
            ' dummy {} +
        fi
        find . -name "*.mp4" -o -name "*.mkv" \
        | sed 's:\ :\ :g;s/^/file /' \
        | sort -d > files.txt
        ffmpeg -safe 0 -f concat -i files.txt -c copy "$1"
        rm files.txt 2>&1
        mv "$1" .. >/dev/null
    else
        echo " No mp4 or mkv file found..." && exit 1
    fi
}

clear
segments=0
_Segmentize "$segments"
clear

if (("$segments"==1)); then
    mv "$filename"-part1."$extension" "$filename"."$extension"
elif (("$segments">1)); then
    printf '\n'
    read -rn 1 -p " Join the segments into one file? [Y/n] or [Q]uit: " OPTIONS
    case "$OPTIONS" in
        y|Y)
            mv "${file}" .. >/dev/null
            clear
            printf '\n'
            echo " Set a new filename (no extension):"
            read -r NAME
            _Concatentate "${NAME}"."${extension}"
            rm ./*
            clear
        ;;
        *)
            exit
        ;;
    esac

fi

