#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV>
#
# Fill the myModelName variable with your supported keyboard.
# G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro,
# and the myModelBinary in lower case suffixed with '-led'
# use lsusb to find out your model name & model id

# shellcheck disable=SC2024
myModelName=G815
myModelId=c33f
myModelBinary=g815-led

! grep -q "$myModelName" < <(lsusb) && {

    [[ -z $(command -v $myModelBinary) ]] && {
    	echo " $myModelBinary not found...exiting"
    	exit 127
    }

    echo "$myModelName is not plugged in, exiting..."
    exit 1

}

config_dir="$HOME/.config/g810-led"
etcProfiles="/etc/g810-led/profiles"
groupSkel="$config_dir/group_skel"
profiles_dir="$config_dir/profiles"
profileSkel="$config_dir/profile_skel"
rules="/etc/udev/rules.d/g810-led.rules"
profile=$(grep -e "$myModelId" "$rules" | sed 's,.*/,,;s/"//')
themes_dir="$config_dir/themes"
themesNum=("$themes_dir"/*)
grn=$'\e[32m'
nc=$'\e[0m'

_Menu() {
    clear
    while [[ -d /etc/g810-led ]]; do
        clear
        echo -e "\n Actual number of themes: ${#themesNum[@]}\n"
        echo -e " Actual profile: ${profile#profile_}\n"
        printf '%s\n' "${grn}                                         ::g810-led-menu options::" \
                        "                       ┌───────────────────────────────────────────────────────────┐" \
                        "                       │  1) Create a keys profile    5) Edit keys profile skel    │" \
                        "                       │  2) Create a groups profile  6) Edit groups profile skel  │" \
                        "                       │  3) Delete a profile         7) Edit a theme              │" \
                        "                       │  4) Switch to a profile      X) Exit                      │" \
                        "                       └───────────────────────────────────────────────────────────┘" \
                        "                                             Select an item${nc}"
        printf '\n'

        read -rsn 1 option
        case "$option" in
            1) _createProfileType --keys ;;
            2) _createProfileType --groups ;;
            3) _deleteProfile ;;
            4) _switchProfile ;;
            5) vim "$profileSkel" ;;
            6) vim "$groupSkel" ;;
            7) _editTheme ;;
            [xX]) clear && exit ;;
        esac
    done
}

_editTheme() {

    clear
    printf '\n'

    PS3=""$'\n'" Choose a RGB profile to edit: "
    select name in $(find "$themes_dir" -type f -printf '%f\n' | sort); do
        vim "$themes_dir"/"$name" && return
    done

}

_keyboardHook() {

    locak rulesProfile GET_SINK_MUTE muteKeyOn
    rulesProfile=$(grep -e 'profile_' "$rules" | sed 's,.*/,,;s/"//')
    GET_SINK_MUTE=$(pactl get-sink-mute "$(pactl get-default-sink)")
    muteKeyOn=$(awk '/^var color1/{print $NF}' "$etcProfiles"/"$rulesProfile")

    polybar-msg \
        -p "$(pgrep --full "$(awk '/Name/{print $2}' < <(wmctrl -m))"-bar-2)" \
        action "#ksp-ipc.hook.0" >/dev/null 2>&1

    [[ -s $XDG_RUNTIME_DIR/scratchpad_hidden.list ]] && \
        sudo "$myModelBinary" -fx breathing logo fb4934 5
    [[ ${GET_SINK_MUTE} == 'Mute: yes ' ]] && \
        sudo "$myModelBinary" -k mute "$muteKeyOn"
}

_deleteProfile() {

    cd "$etcProfiles" || exit 1
    clear

    awk -v ID="$myModelId" -v PFL="$profile" '
    	$0 ~ ID {
    		gsub("/","")
    		sub("[\"]","")
    		}
    	{ print " in use: "PFL" "; exit }
    ' "$rules" | sed 's/profile_//'
    printf '\n'

    PS3=""$'\n'" Choose a RGB profile to delete: "
    select name in $(
            find . \
            -type f \
            -not -name "profile_default" \
            -name "profile_*" -printf '%f\n' \
            | sort \
            | sed 's/profile_//'
        ); do

        if [[ "$profile" =~ $name ]]; then
            sudo "$myModelBinary" -pp < profile_default
            sudo sed -i "s/${profile}/profile_default/" "$rules"
            sudo rm profile_"$name"
            rm "$profiles_dir"/profile_"$name"
    	    echo " profile $name deleted."
            sleep 2
        else
            sudo rm profile_"$name"
            rm "$profiles_dir"/profile_"$name"
    	    echo " profile $name deleted."
            sleep 2
        fi
        break
    done

    _keyboardHook

}

_ifTypeIs() {

    if [[ $create =~ g|G ]]; then
        cp "$groupSkel" "$profiles_dir"/profile_"$name"
        sed -i "1s/^/# groups_$name\n/" profile_"$name"
    else
        cp "$profileSkel" "$profiles_dir"/profile_"$name"
        sed -i "1s/^/# profile_$name\n/" profile_"$name"
    fi

}

_saveAs() {

    sudo mkdir -p "$etcProfiles"
    sudo cp -f profile_"$name" "$etcProfiles"/profile_"$name"

    read -rp " Apply $name? [Y/n]: "
    case "$REPLY" in
        y|Y)
            sudo "$myModelBinary" -pp < "$etcProfiles"/profile_"$name"
            sudo sed -i "s/${profile}/profile_${name}/" "$rules"
            _keyboardHook
        ;;
        n|N) exit 0 ;;
        *  ) echo " wrong option $REPLY...exiting" && exit 1 ;;
    esac

}

_createProfile() {

    declare -a XresourcesColors=(
        color1 color2 color3 color4 color5 color6 color7
    )

    # ~/.config/g810-led/themes/<myTheme> [variables] names
    declare -A ThemeColors=(
        [red]="${XresourcesColors[0]}"
        [grn]="${XresourcesColors[1]}"
        [ylw]="${XresourcesColors[2]}"
        [blu]="${XresourcesColors[3]}"
        [mag]="${XresourcesColors[4]}"
        [cyn]="${XresourcesColors[5]}"
        [wht]="${XresourcesColors[6]}"
    )

    cd "$profiles_dir" || exit 1

    printf '\n'
    case "$create" in
        m|M)
            read -rp ' Enter a profile name: ' name
            _ifTypeIs
            for m in "${XresourcesColors[@]}"; do
                printf '\n'
                printf '%s\n' " color1=red color2=green color3=yellow color4=blu " \
                              " color5=magenta color6=cyan color7=white"
                printf '\n'
                read -rp " Enter an hex color value for $m: " clr
                sed -i "s/var ${m}/var ${m} ${clr}/" profile_"$name"
                clear
            done
        ;;
        t|T)
            if [[ -d $themes_dir ]]; then
                PS3=""$'\n'" Choose a theme: "
                select name in $(find "$themes_dir" -type f | sort | sed 's,.*/,,'); do
                    _ifTypeIs
    	            for key in "${!ThemeColors[@]}"; do
                        colorname="${ThemeColors[${key}]}"
                        colorvalue=$(
                            awk -F'#' -v K="$key" '$0~K{print $3; exit}
                            ' "$themes_dir"/"$name"
                        )
                        echo "$colorvalue"
                        sed -i "s/var ${colorname}/var ${colorname} ${colorvalue}/" \
                        "$profiles_dir"/profile_"$name"
                    done
    	            break
                done
            else
                echo " $themes_dir does not exist...exiting" && exit 1
            fi
        ;;
        x|X)
            if [[ -e $HOME/.Xresources ]]; then
                read -rp ' Enter a profile name: ' name
                _ifTypeIs
                for x in "${XresourcesColors[@]}"; do
                    colorvalue=$(xrdb -query | awk -F'#' -v X="$x" '$0~X{print $2; exit}')
                    echo "$colorvalue"
                    sed -i "s/var ${x}/var ${x} ${colorvalue}/" profile_"$name"
                done
            else
                echo " $HOME/.Xresources does not exist...exiting" && exit 1
            fi
        ;;
        *)
            echo " Wrong option '$create'...exiting" && exit 1
        ;;
    esac

    _saveAs

}

_createProfileType() {

    case "$1" in
        --groups)
            read -rp " create groups profile [M]anually, from a [T]heme or from [X]resources: " create
            _createProfile
        ;;
        --keys)
            read -rp " create keys profile [M]anually, from a [T]heme or from [X]resources: " create
            _createProfile
        ;;
    esac

}

_switchProfile() {

    cd "$profiles_dir" || exit 1
    clear

    awk -v ID="$myModelId" -v PRFL="$profile" '
    	$0 ~ ID {
    		gsub("/","")
    		sub("[\"]","")
    		}
    	{ print " In use "PRFL": "; exit }
    ' "$rules" | sed 's/profile_//'
    printf '\n'

    PS3=""$'\n'" Choose a RGB profile: "
    select name in $(
    		find . \
    		-type f \
    		-name "profile_*" -printf '%f\n' \
    		| sort \
    		| sed 's/profile_//'
    	); do

        sudo "$myModelBinary" -pp < profile_"$name"
        sudo sed -i "s/${profile}/profile_${name}/" \
        "$rules"
    	echo " profile $name selected."
        sleep 2
        break
    done

    _keyboardHook

}

_Menu "${@}"
