#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV>
#
# Dependencies: awk, g810-led, lsusb, dialog (optional)
# This script let us create, delete, switch between RGB profiles
# designed to be use with our Logitech compatible keyboard.
# First install the g810-led package from sources or the AUR repository.
#
# Supported keyboards: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro
# Themes, profiles and "skeletons" can be edited through the menu too.
# use lsusb | grep -i keyboard, to find out your model name & model id

# shellcheck disable=SC2024
# colors
R=$'\e[31m'
G=$'\e[32m'
Y=$'\e[33m'
B=$'\e[34m'
M=$'\e[35m'
C=$'\e[36m'
W=$'\e[37m'
Z=$'\e[0m'

[[ ! $(awk '/Keyboard/{print $7}' < <(lsusb)) =~ ^Logitech,$ ]] && {
    printf '%s\n' " ${R}No Logitech keyboard detected, exiting...${Z}"
    exit 1
}

declare -a Keyboards=( G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro )
for keyboard in "${Keyboards[@]}"; do
    if [[ ! $(awk -v kb="$keyboard" '$0 ~ kb {print $9}' < <(lsusb)) ]]; then
        continue
    else
        myModelName="$keyboard"
    fi
done

myModelBinary="${myModelName,}-led"
command -v "$myModelBinary" &>/dev/null || {
    printf '%s\n' " ${R}No g810-led related binary found, exiting...${Z}"
    exit 127
}

if command -v vim &>/dev/null; then
    editor=vim
else
    read -rp " ${R}Enter your editor of choice: ${Z}" editor
    [[ -z $editor ]] || ! command -v "$editor" &>/dev/null && exit 1
fi

# computed once so every menu (main and submenus) agrees on whether to use dialog
command -v dialog &>/dev/null && HAS_DIALOG=1

etc_confdir="/etc/g810-led"
profile=$(sed -n '1s/# //p' "$etc_confdir"/profile)
etc_profiles="$etc_confdir/profiles"
config_dir="$HOME/.config/g810-led"
groups_skel="$config_dir/groups_skel"
keys_skel="$config_dir/keys_skel"
profiles_dir="$config_dir/profiles"
profiles_num=("$profiles_dir"/*)
themes_dir="$config_dir/themes"
themes_num=("$themes_dir"/*)

_mainMenuAction() {

    case "$1" in
        1) _createProfile ;;
        2) _deleteProfile ;;
        3) _switchProfile ;;
        4) _editFiles keys ;;
        5) _editFiles groups ;;
        6) _editFiles theme ;;
        7) _editFiles profile ;;
        [xX]) clear; exit ;;
    esac

}

_mainMenuDialog() {

    local option status

    while true; do
        option=$(
            dialog \
            --backtitle "Themes: ${#themes_num[@]}  Profiles: ${#profiles_num[@]}  In use: ${profile}" \
            --title "G810-LED-MENU OPTIONS" \
            --cancel-label "Exit" \
            --menu "Select an item:" 18 60 8 \
            1 "Create a profile" \
            2 "Delete a profile" \
            3 "Switch profile" \
            4 "Edit keys profile skel" \
            5 "Edit groups profile skel" \
            6 "Edit a theme" \
            7 "Edit a profile" \
            3>&1 1>&2 2>&3 3>&-
        )
        status=$?
        clear
        ((status != 0)) && exit 0
        # [[ $status -ne 0 ]] && exit 0
        _mainMenuAction "$option"
    done

}

_mainMenuText() {

    while true; do
        clear
        echo -e "\n Number of themes:   ${G}${#themes_num[@]}${Z}"
        echo -e " Number of profiles: ${G}${#profiles_num[@]}${Z}"
        echo -e " Profile in use:     ${G}${profile}${Z}\n\n"
        printf '%s\n' "${W}                                      ::${R}G${G}810${W}-${Y}LED${W}-${B}MENU ${M}OPTIONS${W}::${G}" \
                        "                       ┌────────────────────────────────────────────────────┐" \
                        "                       │  1) Create a profile  4) Edit keys profile skel    │" \
                        "                       │  2) Delete a profile  5) Edit groups profile skel  │" \
                        "                       │  3) Switch profile    6) Edit a theme              │" \
                        "                       │  ${R}X) Exit${G}              7) Edit a profile            │" \
                        "                       └────────────────────────────────────────────────────┘" \
                        "                                           ${C}Select an item${Z}" \
        ""

        read -rsn 1 option
        case "$option" in
            1|2|3|4|5|6|7|[xX]) _mainMenuAction "$option" ;;
            *) continue ;;
        esac
    done

}

_mainMenu() {

    # resizing the terminal
    echo -ne '\e[8;30;103t'
    clear
    command -v dialog &>/dev/null && HAS_DIALOG=1
    if [[ -n $HAS_DIALOG ]]; then
        _mainMenuDialog
    else
        _mainMenuText
    fi

}

_cancel() {

    case $REPLY in
        [cC])
            profile=$(sed -n '1s/# //p' "$etc_confdir"/profile)
            printf '%s\n' " ${R}Selection cancelled...${Z}"
            rm "$profiles_dir"/{keys,groups}_skel 2> /dev/null
            sleep 2
            _mainMenu
        ;;
    esac

}

# Picks a file name from a list, using dialog if available or the select builtin otherwise.
# Result is returned in the global PICKRESULT variable, empty/cancelled selections go back to _mainMenu.
_selectFile() {

    local title="$1" text="$2"; shift 2
    local -a items=("$@")
    PICKRESULT=""

    if [[ -n $HAS_DIALOG ]]; then
        if (( ${#items[@]} == 0 )); then
            clear
            printf '%s\n' " ${R}Nothing to select...${Z}"
            sleep 2
            _mainMenu
        fi

        local -a menu_items=() item
        for item in "${items[@]}"; do menu_items+=("$item" ""); done

        PICKRESULT=$(
            dialog \
            --backtitle "In use: ${profile}" \
            --title "$title" \
            --cancel-label "Cancel" \
            --menu "$text" 24 30 8 \
            "${menu_items[@]}" \
            3>&1 1>&2 2>&3 3>&-
        )

        local status=$?
        clear
        [[ $status -ne 0 ]] && _mainMenu
    else
        PS3=""$'\n'" ${G}$text or [C]ancel: ${Z}"
        select PICKRESULT in "${items[@]}"; do _cancel; break; done
    fi

}

_blankLine() { printf '\n'; }

_editMenu() {

    local title="$1" text="$2" profile_name
    local -a files=()

    while IFS= read -r profile_name; do
        files+=("$profile_name")
    done < <(find . -type f -printf '%f\n' | sort)

    clear
    _blankLine
    _selectFile "$title" "$text" "${files[@]}"
    "$editor" "$PICKRESULT"

}

_editFiles() {

    case $1 in
        groups) "$editor" "$groups_skel" ;;
        keys) "$editor" "$keys_skel" ;;
        profile)
            cd "$profiles_dir" || exit 1
            _editMenu "Edit a profile" "Choose a RGB profile to edit"
        ;;
        theme)
            cd "$themes_dir" || exit 1
            _editMenu "Edit a theme" "Choose a theme to edit"
        ;;
    esac

}

# Polybar module to display the profile in use and to switch between profiles,
# using the g810_switch_profile script.
#
# [module/ksp-ipc]
# type = custom/ipc
# hook-0 = echo "%{F$(xrdb -query | awk '/color4:/{print $NF}')}$(sed -n '1s/#//p' /etc/g810-led/profile) %{F-}"
# initial = 1
# format = <output>
# format-prefix = "   "
# format-prefix-foreground = ${colors.green}
# format-padding = 1
#
# Edit the line below according to your terminal emulator,
# to open a floating terminal with the g810_switch_profile script.
# click-left = urxvtc -name floaterm -geometry 60x12 -e g810_switch_profile & disown
#
# This function updates the logitech logo and the mute key,
# if some window(s) are in the scratchpad and the computer sound is muted,
# it also indicates the profile name in polybar.
_keyboardHook() {

    local get_sink_mute muteKeyOn
    get_sink_mute=$(pactl get-sink-mute "$(pactl get-default-sink)")
    muteKeyOn=$(awk '/^var color1/{print $NF}' "$etc_profiles"/"$profile")

    polybar-msg \
        -p "$(pgrep --full "$(awk '/Name/{print $2}' < <(wmctrl -m))"-bar-2)" \
        action "#ksp-ipc.hook.0" >/dev/null 2>&1

    [[ -s $XDG_RUNTIME_DIR/scratchpad_hidden.list ]] && \
        sudo "$myModelBinary" -fx breathing logo fb4934 5
    [[ ${get_sink_mute} == 'Mute: yes ' ]] && \
        sudo "$myModelBinary" -k mute "$muteKeyOn"

}

_deleteProfile() {

    cd "$etc_profiles" || exit 1
    clear
    local profile_name
    local -a files=()

    while IFS= read -r profile_name; do
        files+=("$profile_name")
    done < <(find . -type f -not -name "default" -printf '%f\n' | sort)

    _selectFile "Delete a profile" "Choose a RGB profile to delete" "${files[@]}"
    profile_name="$PICKRESULT"

    if [[ $profile_name == "$profile" ]]; then
        # if we want to remove the profile in use...
        # the default profile will be applied.
        sudo "$myModelBinary" -pp < default
        sudo rm "$profile_name"
        sudo cp -f "$etc_profiles/default" "$etc_confdir/profile"
        rm "$profiles_dir/$profile_name"
        # Updating the menu (the profile name).
        profile="default"
        printf '%s\n' " ${R}profile $profile_name deleted.${Z}"
        sleep 2
    else
        sudo rm "$profile_name"
        rm "$profiles_dir/$profile_name"
        printf '%s\n' " ${R}profile $profile_name deleted.${Z}"
        sleep 2
    fi
    # and update the menu for the number of existing profiles.
    profiles_num=("$profiles_dir"/*)
    _keyboardHook

}

_ifProfileNameAlreadyExist() {

    read -rp " ${G}Enter a profile name: ${Z}" profile_name
    [[ -f $profile_name ]] && {
        printf '%s\n' " ${R}profile $profile_name already exists, try again...${Z}"
        sleep 2
        clear
        _mainMenu
    }

}

_ifProfileTypeIs() {

    case "${profile_type}" in
        [gG])
            cp "$groups_skel" "$profiles_dir/$profile_name"
            sed -i "1s/^/# $profile_name\n/" "$profile_name"
        ;;
        [kK])
            cp "$keys_skel" "$profiles_dir/$profile_name"
            sed -i "1s/^/# $profile_name\n/" "$profile_name"
        ;;
        *)
            printf '%s\n' " ${R}Wrong option $profile_type.${Z}"
            sleep 2
            _mainMenu
        ;;
    esac

    clear

}

_createProfile() {

    cd "$profiles_dir" || exit 1
    clear

    declare -a XresourcesColors=(
        color1 color2 color3 color4 color5 color6 color7
    )

    # ~/.config/g810-led/themes/<myTheme> [variables] names
    declare -A ThemeColors=(
        [red]="${XresourcesColors[0]}"
        [grn]="${XresourcesColors[1]}"
        [ylw]="${XresourcesColors[2]}"
        [blu]="${XresourcesColors[3]}"
        [mag]="${XresourcesColors[4]}"
        [cyn]="${XresourcesColors[5]}"
        [wht]="${XresourcesColors[6]}"
    )

    local profile_name profile_type create_from colorvalue colorname

    _blankLine
    read -rp " ${G}Create a [G]roups or a [K]eys profile, [C]ancel: ${Z}" profile_type
    case $profile_type in [cC]) _mainMenu ;; esac
    read -rp " ${G}Create [M]anually, from a [T]heme or from [X]resources: ${Z}" create_from
    _blankLine

    __sedEditProfile() {
        sed -i "
            s/var ${colorname}/var ${colorname} ${colorvalue}/
        " "$profile_name"
    }

    case "$create_from" in
        [mM])
            _ifProfileNameAlreadyExist
            _ifProfileTypeIs

            for colorname in "${XresourcesColors[@]}"; do

                _blankLine
                printf '%s\n' " ${G}color1=red color2=green color3=yellow color4=blue " \
                              " color5=magenta color6=cyan color7=white${Z}" \
                ""

                read -rp " ${G}Enter an hex color value for $colorname: ${Z}" colorvalue
                # testing the range and the number of characters for hexadecimal colors.
                [[ ! $colorvalue =~ ^[a-fA-F0-9]{6}$ ]] && {
                    printf '%s\n' " ${R}Hex colors must be 6 digits/numbers long!" \
                    " 0 -> 9, a -> f, eg: 88def2${Z}"
                    rm "$profile_name"
                    sleep 5
                    _mainMenu
                }

                __sedEditProfile
                clear

            done
        ;;
        [tT])
            if [[ -d $themes_dir ]]; then

                local -a theme_files=()

                while IFS= read -r profile_name; do
                    theme_files+=("$profile_name")
                done < <(find "$themes_dir" -type f -printf '%f\n' | sort)

                _selectFile "Create from theme" "Choose an existing theme" "${theme_files[@]}"
                profile_name="$PICKRESULT"

                # _ifProfileNameAlreadyExist isn't needed here,
                # the profile name is determined by the user's choice in the menu.
                _ifProfileTypeIs

                for key in "${!ThemeColors[@]}"; do
                    colorname="${ThemeColors[${key}]}"
                    colorvalue=$(
                        awk -F'#' -v K="$key" '
                            $0 ~ K { print $3; exit }
                        ' "$themes_dir/$profile_name"
                    )
                    printf '%s\n' "$colorvalue"
                    __sedEditProfile
                done

            else
                printf '%s\n' " ${R}$themes_dir does not exist...exiting${Z}"
                rm {groups,keys}_skel 2>/dev/null
                sleep 2
                exit 1
            fi
        ;;
        [xX])
            if [[ -e $HOME/.Xresources ]]; then

                _ifProfileNameAlreadyExist
                _ifProfileTypeIs

                for colorname in "${XresourcesColors[@]}"; do
                    colorvalue=$(
                        xrdb -query \
                        | awk -F'#' -v X="$colorname" '
                            $0 ~ X { print $2; exit }
                        '
                    )
                    printf '%s\n' "$colorvalue"
                    __sedEditProfile
                done

            else
                printf '%s\n' " ${R}$HOME/.Xresources does not exist...exiting!${Z}"
                rm {groups,keys}_skel 2>/dev/null
                exit 1
            fi
        ;;
        *)
            printf '%s\n' " ${R}Wrong option '$create_from'...try again${Z}"
            rm {groups,keys}_skel 2>/dev/null
            sleep 2
            _mainMenu
        ;;
    esac

    sudo mkdir -p "$etc_profiles"
    sudo cp -f "$profile_name" "$etc_profiles/$profile_name"
    sudo chmod +r "$etc_profiles/$profile_name"

    read -rp " ${G}Apply $profile_name? [Y/n]: ${Z}" apply
    # Yes or Enter (empty string) will apply the profile.
    case "$apply" in
        [yY]|"")
            sudo "$myModelBinary" -pp < "$etc_profiles/$profile_name"
            sudo cp -f "$etc_profiles/$profile_name" "$etc_confdir"/profile
            _keyboardHook
            profile="$profile_name"
            profiles_num=("$profiles_dir"/*)
        ;;
        *)
            profiles_num=("$profiles_dir"/*)
            _mainMenu
        ;;
    esac

}

_switchProfile() {

    cd "$profiles_dir" || exit 1
    clear

    local profile_name
    local -a files=()

    while IFS= read -r profile_name; do
        files+=("$profile_name")
    done < <(find . -type f -not -name "$profile" -printf '%f\n' | sort)

    _selectFile "Switch profile" "Choose a RGB profile" "${files[@]}"
    profile_name="$PICKRESULT"

    sudo "$myModelBinary" -pp < "$profile_name"
    sudo cp -f "$etc_profiles/$profile_name" "$etc_confdir"/profile
    printf '%s\n' " ${G}profile $profile_name selected.${Z}"
    sleep 2

    _keyboardHook
    profile="$profile_name"

}

_mainMenu "${@}"