#!/usr/bin/env bash

NAME=$(basename "$0")

_usage() {
   cat <<- EOF

        AUTHOR: Barret E (2020) <archus@protonmail.com>

        SYNOPSIS: $NAME displays the hexadecimal value of a color defined in $HOME/.Xresources.

        -h,--help   Shows this message.
                     Without any arguments this message will be displayed.

        USAGE:

            $NAME [COLOR-NUM] | [COLOR-NAME/VARIABLE] | [-a|--all]

        [-a|--all]:

            Prints all colors from the resources file.

        COLOR-NUM/NAME:

            The color numbers are set as: color0, color1 and so on until color15.

            eg: $NAME 10     # Will provide the second green as such *.color10:	#XXXXXX

        COLOR-NAME/VARIABLE:

            ... but you can also set "variables" to recall the colors from different programs and scripts.
            More help can be found here: https://wiki.archlinux.org/index.php/X_resources#Include_files
            If you do so, just edit the case statement of this script.

            Xresources example:

               #include ".xfiles/themes/onedark" # set themes directory and the active one.
               #include ".xfiles/colors"         # this file contains variables and names.

            examples:

               name:     $NAME green2
               variable: $NAME grn2

EOF
}

[[ ! -e $HOME/.Xresources ]] && {
    echo "$HOME/.Xresources: no such file or directory"
    exit 1
}

_query() { xrdb -query | grep "$1"; }

_allcolors() {
    echo
    echo "  Resources   |  Values  |  Names"
    echo "--------------------------------------"

    declare -a xres=(
        "$(_query 'foreground:')    foreground"
        "$(_query 'background:')    background"
        "$(_query 'color0:')    black"
        "$(_query 'color1:')    red"
        "$(_query 'color2:')    green"
        "$(_query 'color3:')    yellow"
        "$(_query 'color4:')    blue"
        "$(_query 'color5:')    magenta"
        "$(_query 'color6:')    cyan"
        "$(_query 'color7:')    white"
        "$(_query 'color8:')    black 2"
        "$(_query 'color9:')    red 2"
        "$(_query 'color10:')    green 2"
        "$(_query 'color11:')    yellow 2"
        "$(_query 'color12:')    blue 2"
        "$(_query 'color13:')    magenta 2"
        "$(_query 'color14:')    cyan 2"
        "$(_query 'color15:')    white 2"
    )

    for i in "${xres[@]}"; do
        echo "$i"
    done

}

if [[ -n "$1" ]]; then
    color=$1
fi

case "$color" in
    foreground|fg)    _query 'foreground:' ;;
    background|bg)    _query 'background:' ;;
    black|0|blk)      _query 'color0:'  ;;
    red|1)            _query 'color1:'  ;;
    green|2|grn)      _query 'color2:'  ;;
    yellow|3|ylw)     _query 'color3:'  ;;
    blue|4|blu)       _query 'color4:'  ;;
    magenta|5|mag)    _query 'color5:'  ;;
    cyan|6|cyn)       _query 'color6:'  ;;
    white|7|wht)      _query 'color7:'  ;;
    black2|8|blk2)    _query 'color8:'  ;;
    red2|9)           _query 'color9:'  ;;
    green2|10|grn2)   _query 'color10:' ;;
    yellow2|11|ylw2)  _query 'color11:' ;;
    blue2|12|blu2)    _query 'color12:' ;;
    magenta2|13|mag2) _query 'color13:' ;;
    cyan2|14|cyn2)    _query 'color14:' ;;
    white2|15|wht2)   _query 'color15:' ;;
    -a|--all)         _allcolors ;;
    -h|--help|*)      _usage ;;
esac
