#!/bin/bash

# Hardware utilizations and temperatures displayed in polybar.

_mpd() {
    # I know itsn't relared to hardware stufff but I had to do this...
    # if ncmpcpp is running it will activate the same polybar module,
    # but if it's not the case...
    if [[ -z $(pidof ncmpcpp) ]]; then
        polybar-msg -p "$(pgrep --full bspwm-bar-2)" \
        action "#music_player-ipc.hook.1" >/dev/null 2>&1 \
        || polybar-msg -p "$(pgrep --full i3-bar-2)" \
        action "#music_player-ipc.hook.1" >/dev/null 2>&1
    fi
}

_coreusage() { cut -d ' ' -f1 /proc/loadavg; }

_coretemp() {
    if [[ -n $(sensors | awk '/Tccd1/') ]]; then
        sensors | awk '/Tccd1/{ sub("+",""); print $2 }'
    else
        sensors | awk '/Tdie/{ sub("+",""); print $2 }'
    fi
}

_nvidia() {
    gputemp="$(nvidia-smi \
            --format=nounits,csv,noheader \
            --query-gpu=temperature.gpu)"
    usedgpu="$(nvidia-smi \
            --format=nounits,csv,noheader \
            --query-gpu=utilization.gpu)"

    [[ -x /bin/nvidia-smi ]] \
        && echo "${usedgpu}% - ${gputemp}°C" \
        || echo "no nvidia driver installed"
}

_fanspeed() { sensors | awk '/fan2/{print $2" ""rpm"}'; }

_mem() { free -h | awk '/Mem:/{print $3}'; }

_disksusage() {
    if (( $(df -h | awk '/sda2/{ sub("%",""); print $5 }') > 65 )); then
        sudo paccache --quiet -rk0
    else
        df -h | awk '/sda2/{print $5}'
    fi
}

# colored FontAwesome icons for polybar using ~/.Xresources parameters.
# (p)oint is just a character that creates a kind of padding function,
# for simulated blocks or modules.
_icons_color() { xrdb -query | awk '/color4:/{print $NF}'; }

p="%{F"$(xrdb -query | awk '/background:/{print $NF}')"}:%{F-}"
icon_core="%{F"$(_icons_color)"}%{F-}"
icon_nvidia="%{F"$(_icons_color)"}%{F-}"
icon_fan="%{F"$(_icons_color)"}%{F-}"
icon_mem="%{F"$(_icons_color)"}%{F-}"
icon_disk="%{F"$(_icons_color)"}%{F-}"
icon_kernel="%{F"$(_icons_color)"}%{F-}"

echo "${icon_core}""${p}" "$(_coreusage)"% - "$(_coretemp)""${p}" \
     "${icon_nvidia}""${p}" "$(_nvidia)""$p" "${icon_fan}""${p}" "$(_fanspeed)""${p}" \
     "${icon_mem}""${p}" "$(_mem)""$p" "${icon_disk}""${p}" "$(_disksusage)"
$(_mpd)
