#!/bin/bash

# Hardware utilizations and temperatures for polybar

_kernel() { uname -r; }

_mem() { free -h | awk '/Mem:/{print $3}'; }

_coreusage() { cut -d ' ' -f1 /proc/loadavg; }

_disksusage() { df -h | awk '/sda2/{print $5}'; }

_fanspeed() { sensors | awk '/fan2/{print $2}'; }

_coretemp() { sensors | awk '/Tccd1/{print $2}' | sed 's/+//'; }
#_coretemp() { sensors | awk '/Tdie/{print $2}' | sed 's/+//'; }

_nvidia() {
    gputemp="$(nvidia-smi \
    --format=nounits,csv,noheader \
    --query-gpu=temperature.gpu)"
    usedgpu="$(nvidia-smi \
    --format=nounits,csv,noheader \
    --query-gpu=utilization.gpu)"

    [[ $(pacman -Q nvidia) =~ 'nvidia' ]] \
        && echo "$usedgpu% - $gputemp°C" \
        || echo "no nvidia driver installed"
}

# colored FontAwesome icons for polybar using ~/.Xresources parameters.
# (p)oint is just a character that creates a kind of padding function,
# for simulated blocks or modules.

p="%{F$(xrdb -query | awk '/background:/{print $NF}')}:%{F-}"
icon_core="%{F$(xrdb -query | awk '/color5:/{print $NF}')}%{F-}"
icon_nvidia="%{F$(xrdb -query | awk '/color5:/{print $NF}')}%{F-}"
icon_fan="%{F$(xrdb -query | awk '/color5:/{print $NF}')}%{F-}"
icon_mem="%{F$(xrdb -query | awk '/color5:/{print $NF}')}%{F-}"
icon_disk="%{F$(xrdb -query | awk '/color5:/{print $NF}')}%{F-}"
icon_kernel="%{F$(xrdb -query | awk '/color5:/{print $NF}')}%{F-}"

echo "$icon_core""$p" "$(_coreusage)"% - "$(_coretemp)""$p" "$icon_nvidia""$p" "$(_nvidia)""$p" \
     "$icon_fan""$p" "$(_fanspeed)""$p" "$icon_mem""$p" "$(_mem)""$p" \
     "$icon_disk""$p" "$(_disksusage)""$p" "$icon_kernel""$p" "$(_kernel)"

