#!/bin/bash

# Hardware utilizations and temperatures displayed in polybar.
# I had to include mpd stuff not to create another polybar module.
# Same thing for mpv...

WM_NAME=$(wmctrl -m | awk '/Name/{print $2}')

_mpd() {
    # if ncmpcpp is running it will activate the same polybar module,
    # but if it's not the case...
    [[ -z $(pidof ncmpcpp) ]] && {
        polybar-msg \
        -p "$(pgrep --full "$WM_NAME"-bar-2)" \
        action "#music_player-ipc.hook.1" >/dev/null 2>&1
    }
}

_mpv() {
    
    [[ -n $(pidof mpv) ]] && {
        
        local metadata="$XDG_RUNTIME_DIR/mpv.txt"
        
        [[ ! -f "$metadata" ]] && touch "$metadata"
        echo '{ "command": ["get_property", "media-title"] }' \
        | socat - /tmp/mpvsocket | awk -F '"' '{print $4}' > "$metadata"
        
        polybar-msg -p "$(pgrep --full "$WM_NAME"-bar-3)" \
        action "#mpv-ipc.hook.1"
        
    } || polybar-msg -p "$(pgrep --full "$WM_NAME"-bar-3)" \
    action "#mpv-ipc.hook.0"
    
}

_coreusage() { cut -d ' ' -f1 /proc/loadavg; }

_coretemp() {
    if [[ -n $(sensors | awk '/Tccd1/') ]]; then
        sensors | awk '/Tccd1/{ sub("[+]",""); print $2 }'
    else
        sensors | awk '/Tdie/{ sub("[+]",""); print $2 }'
    fi
}

_nvidia() {
    gputemp="$(nvidia-smi \
            --format=nounits,csv,noheader \
            --query-gpu=temperature.gpu)"
    usedgpu="$(nvidia-smi \
            --format=nounits,csv,noheader \
            --query-gpu=utilization.gpu)"

    [[ -x /bin/nvidia-smi ]] \
        && echo "${usedgpu}% - ${gputemp}°C" \
        || echo "no nvidia driver installed"
}

_fanspeed() { sensors | awk '/fan2/{print $2" ""rpm"}'; }

_mem() { free -h | awk '/Mem:/{print $3}'; }

_disksusage() {
    if (( $(df -h | awk '/sda2/{ sub("[%]",""); print $5 }') > 65 )); then
        echo "%{F#FF4747}"$(df -h | awk '/sda2/{print $5}')"%{F-}"
    else
        df -h | awk '/sda2/{print $5}'
    fi
}

# colored FontAwesome icons for polybar using ~/.Xresources parameters.
# (p)oint is just a character that creates a kind of padding function,
# for simulated blocks or modules.
_icons_color() { xrdb -query | awk '/color4:/{print $NF}'; }

p="%{F"$(xrdb -query | awk '/background:/{print $NF}')"}:%{F-}"
icon_core="%{F"$(_icons_color)"}%{F-}"
icon_nvidia="%{F"$(_icons_color)"}%{F-}"
icon_fan="%{F"$(_icons_color)"}%{F-}"
icon_mem="%{F"$(_icons_color)"}%{F-}"
icon_disk="%{F"$(_icons_color)"}%{F-}"
icon_kernel="%{F"$(_icons_color)"}%{F-}"

echo "${icon_core}""${p}" "$(_coreusage)"% - "$(_coretemp)""${p}" \
     "${icon_nvidia}""${p}" "$(_nvidia)""$p" "${icon_fan}""${p}" "$(_fanspeed)""${p}" \
     "${icon_mem}""${p}" "$(_mem)""$p" "${icon_disk}""${p}" "$(_disksusage)"
$(_mpd)
$(_mpv)
