#!/bin/bash

# This script sends windows in the scratchpad,
# and activates an indicator (led 3 on the keyboard
# and a polybar module) for us to know
# how many of them we have hidden in i3wm/bspwm.
# Dependencies: polybar (optional), wmctrl, xorg-xset
#
# Polybar module for i3
#[module/scratchpad-ipc]
#type = custom/ipc
#format = <output>
#format-padding = 1
#hook-0 = echo ""
#; for bspwm
#hook-1 = echo " %{F#A6E074}scrachpad $(grep "" -c < <(bspc query -N -n .hidden.window))%{F-}"
#; for i3wm
#hook-2 = echo " %{F#A6E074}scrachpad $(awk '/-1/ {count++} END {print count}' < <(wmctrl -l))%{F-}"
#initial = 1

# ... my polybar name on monitor 3 is {bspwm,i3}-bar-3
WM_NAME=$(awk '/Name/{print $2}' < <(wmctrl -m))
BARPID=$(pgrep --full $WM_NAME-bar-3)

_indicator() {
    
    [[ $WM_NAME = i3 ]] && {
        COUNT=$(awk '/-1/ {count++} END {print count}' < <(wmctrl -l))
        if (( COUNT > 0 )); then
            xset led 3
            polybar-msg -p "$BARPID" \
            action "#scratchpad-ipc.hook.2" >/dev/null 2>&1
        else
            xset -led 3
            polybar-msg -p "$BARPID" \
            action "#scratchpad-ipc.hook.0" >/dev/null 2>&1
        fi
    }
    
    [[ $WM_NAME = bspwm ]] && {
        COUNT=$(grep "" -c < <(bspc query -N -n .hidden.window))
        if (( COUNT > 0 )); then
            xset led 3
            polybar-msg -p "$BARPID" \
            action "#scratchpad-ipc.hook.1" >/dev/null 2>&1
        else
            xset -led 3
            polybar-msg -p "$BARPID" \
            action "#scratchpad-ipc.hook.0" >/dev/null 2>&1
        fi
    }
    
}

case "$1" in
    -h) if [[ $WM_NAME = i3 ]]; then
            i3-msg move scratchpad
            _indicator
        elif [[ $WM_NAME = bspwm ]]; then
            bspc node --flag hidden=on
            _indicator
        fi
    ;;
    -u) if [[ $WM_NAME = i3 ]]; then
            i3-msg scratchpad show; i3-msg floating toggle
            _indicator
        elif [[ $WM_NAME = bspwm ]]; then
            bspc node $(bspc query -N -n .hidden.window | tail -1) \
            -g hidden=off --focus
            _indicator
        fi
    ;;
esac
