#!/bin/bash

info=$(find ~/.local/share/Trash/files/ -mindepth 1 | wc -l)

case "$1" in
    --clean)
        rm -rf ~/.local/share/Trash/{files,info}
        mkdir ~/.local/share/Trash/{files,info}
    ;;
    --info)
        echo "$info"
    ;;
esac
