#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV/>
# Creation date: 2025-07-07
# Script name: install_archlinux_Xdesktop version 1.0.1
# License: GPLv2
#
# This script automates the installation of Artix Linux Xorg/Xlibre:
# - Important: It must be run as root!!!
# - Safety check root account and internet connectivity.

UNDER CONSTRUCTION
