#!/bin/bash

# Author: Barret E <archus@protonmail.com>
# Youtube channel: <https://www.youtube.com/@linuxinfrench9388>
# Idea inspired by Yannick Vollenberg <https://nordri.vollenberg.ca>
# As the script name says, this will install an Achlinux desktop
# following the arch way to Keep It Simple Stupid, meaning no customization.
# Use it at your own risks....lol
# Download the script when logged in the arch live iso:
# curl -sL "https://raw.githubusercontent.com/archusXIV/dotfiles/main/scripts/various/install_desktop" -O
# chmod +x install_desktop && ./install_desktop

# Colors
nc=$'\e[0;m';
g=$'\e[1;32m';
r=$'\e[0;31m';
y=$'\e[93m';

_systemd() {
    pacman -Sy --needed --noconfirm lightdm lightdm-gtk-greeter
    if [[ $(dmidecode -s system-product-name) = VirtualBox ]]; then
        pacman -S --needed --noconfirm virtualbox-guest-utils
        systemctl enable {lightdm,vboxservice}.service
    else
        systemctl enable lightdm.service
    fi
}

_xorg() {
    pacman -Sy --needed --noconfirm xorg xorg-server xorg-xinit \
    xorg-xrandr xorg-xfontsel xorg-xlsfonts xorg-xkill xorg-xinput \
    xorg-xwininfo wmctrl xdg-user-dirs xterm
}

_audio() {
    pacman -Sy --needed --noconfirm alsa-utils pulseaudio \
    pulseaudio-alsa pulsemixer pavucontrol gst-libav \
    gst-plugins-{bad,base,good,ugly}
}

_i3wm() {
    _xorg && pacman -Sy --needed --noconfirm i3-wm i3lock i3status \
    i3blocks polybar dmenu rofi sxhkd rxvt-unicode alacritty htop \
    geany geany-plugins network-manager-applet ranger \
    && _audio && _systemd
}

_bspwm() {
    _xorg && pacman -Sy --needed --noconfirm bspwm sxhkd xdo polybar \
    dmenu rofi rxvt-unicode alacritty geany geany-plugins ranger htop \
    network-manager-applet && _audio && _systemd
}

_cinnamon() {
    _xorg && pacman -Sy --needed --noconfirm cinnamon cinnamon-translations \
    nemo-fileroller nemo-image-converter nemo-preview xed xreader \
    gnome-terminal metacity gnome-shell network-manager-applet htop \
    && _audio && _systemd
}

_kde() {
    _xorg && pacman -Sy --needed --noconfirm \
    plasma-meta kdialog packagekit-qt5 kcalc icoutils libappimage \
    konsole dolphin kdegraphics-thumbnailers svgpart ffmpegthumbs \
    kdenetwork-filesharing gwenview kimageformats ark kate okular \
    kcron kdf filelight print-manager kdeconnect sshfs htop \
    && _audio && _systemd
}

_mate() {
    _xorg && pacman -Sy --needed --noconfirm mate mate-extra \
    network-manager-applet htop && _audio && _systemd
}

_xfce() {
    _xorg && pacman -Sy --needed --noconfirm xfce4 xfce4-goodies \
    network-manager-applet htop && _audio
}

_InstallDesktop() {
    clear
    printf '%s\n'
    read -r -p "${g}"' First pick a new user name: '"${nc}" name
    useradd -m -G audio,video,input,wheel,sys,log,rfkill,lp,adm -s /bin/bash ${name}
    printf '%s\n' " ${g}Change $name password:${nc} "
    sleep 1s
    passwd ${name}
    printf '%s\n' " ${g}Enable $name sudo privileges in sudoers file${nc}: "
    sleep 2s
    EDITOR=vim visudo
    clear
    printf '%s\n'
    printf '%s\n' " ${g}Desktop choice, eg: x for Xfce...${nc}"
    read -r -p "${g}"' [I]3-wm, [B]spwm, [C]innamon, [K]de Plasma, [M]ate, [X]fce: '"${nc}" name
    read -r choice
    case ${choice} in
        i|I) _i3wm     ;;
        b|B) _bspwm    ;;
        c|C) _cinnamon ;;
        k|K) _kde      ;;
        m|M) _mate     ;;
        x|X) _xfce && _systemd ;;
    esac
    
}

_Description() {
    clear
    setfont sun12x22
    cat << EOF

                #                                                       
               # #      #####   ####  #    # #      # #    # #    # #    # 
              #   #     #    # #    # #    # #      # ##   # #    #  #  #  
             #     #    #    # #      ###### #      # # #  # #    #   ##   
            #########   #####  #      #    # #      # #  # # #    #   ##   
           #         #  #   #  #    # #    # #      # #   ## #    #  #  #  
          #           # #    #  ####  #    # ###### # #    #  ####  #    #
    
                     Base installation for lazy dudes made easy!
    
    # French (ne jamais lancer un script sans le lire auparavant)
    ${g}Ce script va installer le bureau de votre choix parmi la liste suivante:${nc}
    
    Preconfigurés:     ${y}i3wm, Bspwm${nc} (coming soon)
    Brut de chez brut: ${y}Cinnamon, KDE Plasma, Mate & Xfce${nc}
    
    # English (never run a script without reading it first)
    ${g}This script will install the desktop of your choice among the following list:${nc}
    
    Preconfigured: ${y}i3wm, Bspwm${nc} (coming soon)
    Bareboned:     ${y}Cinnamon, KDE Plasma, Mate & Xfce${nc}
    
EOF
    printf '%s\n'
    read -r -p "${g}"'    Press enter to launch desktop installation, ^C to quit: '"${nc}" inst
    case "$inst" in *) _InstallDesktop ;; esac
}

_Description
