#!/bin/bash

# Terminate already polybar instances.
killall -q polybar

# Wait until the process has been closed.
while [[ -n $(pgrep -u $UID -x polybar) ]]; do
    sleep 0.5
done

bars_bsp=( "bspwm-bar-1" "bspwm-bar-2" "bspwm-bar-3" )
bars_i3=( "i3-bar-1" "i3-bar-2" "i3-bar-3" )

if [[ -n $(pidof bspwm) ]]; then
    for b in "${bars_bsp[@]}"; do
        polybar "$b" -q & disown
    done
    notify-send 'Bars launched...'
    exit 0
elif [[ -n $(pidof i3) ]]; then
    for b in "${bars_i3[@]}"; do
        polybar "$b" -q & disown
    done
    notify-send 'Bars launched...'
    exit 0
fi
