#!/bin/bash

# Terminate already polybar instances.
# First try gracefully then the hard way.
socket="ipc.$(pgrep polybar | sed -n '1p').sock"

if [[ -S $XDG_RUNTIME_DIR/polybar/$socket ]]; then
    polybar-msg cmd quit >/dev/null 2>&1
else
    rm /tmp/polybar_mqueue.* 2>/dev/null
    killall -q {conky,polybar}
fi

# Wait until the process has been closed.
while pgrep -u "$UID" -x polybar; do
    sleep 0.5
done

bars=( "bspwm-bar-1" "bspwm-bar-2" "bspwm-bar-3" \
        "i3-bar-1" "i3-bar-2" "i3-bar-3" )

if [[ -n $(pidof bspwm) ]]; then
    unset {bars[3],bars[4],bars[5]}
    for b in "${bars[@]}"; do
        polybar "$b" -q & disown
    done
    notify-send 'Bars launched...'
    exit 0
elif [[ -n $(i3 --get-socketpath) ]]; then
    unset {bars[0],bars[1],bars[2]}
    for b in "${bars_i3[@]}"; do
        polybar "$b" -q & disown
    done
    notify-send 'Bars launched...'
    exit 0
fi
