#!/usr/bin/env bash

if [[ $(systemctl status plocate-updatedb.timer \
    | awk '/Active:/{print $3}') = '(waiting)' ]]; then
    locate / | rofi -normal-window -threads 0 \
    -width 50 -dmenu -i -p "locate " | xargs -r -0 xdg-open
else
    sudo updatedb
    locate / | rofi -normal-window -threads 0 \
    -width 50 -dmenu -i -p "locate " | xargs -r -0 xdg-open
fi

