#!/bin/bash

# Usage: make-package <aur_package_name>
# $BUILDIR is an environment variable, see ~/.zshenv
# shellcheck disable=SC2044

buildir=${BUILDIR:-$XDG_CACHE_HOME/makepkg}
editor=${VISUAL:-vim}

mkdir -p "$buildir"

echo "https://aur.archlinux.org/$*" > "$buildir"/url.txt

cd "$buildir" || exit 1

git clone "$(cat "$buildir"/url.txt)"

dir="$(find . -maxdepth 1 -type d -printf '%f\n')"
dir=$*
echo "The git directory is:" "$dir"

if [[ -d $dir ]]; then
    cd "$dir" || exit 1
    if [[ -f PKGBUILD ]]; then
        read -rp 'Edit PKGBUILD? [N/y]:' ans
        case "$ans" in
            Y*|y*) "$editor" PKGBUILD ;;
            *)     echo "" ;;
        esac
    fi

    read -rp 'Only build the package & quit [b], Build & install the package [i]: ' build
    case "$build" in
        b)  makepkg --syncdeps --rmdeps
            cd "$HOME" || exit 1
            rm -rf "$HOME"/.ccache && exit
        ;;
        i)  makepkg --syncdeps --rmdeps
            for i in $(find . -name "*.zst" -o -name "*.xz"); do
                echo "Install $i ? [n/Y]:"
                read -r answer
                case "$answer" in
                    Y|y) sudo pacman -U "$i" --needed --noconfirm ;;
                    n|*) break ;;
                esac
            done

            cd "$HOME" || exit 1
            rm -rf {"$HOME"/.ccache,"$buildir"} && exit
        ;;
        *)  echo "Unknown option, exiting..." && exit 1
        ;;
    esac
else
    echo "$dir does not exist" && exit 1
fi

