#!/bin/bash

# This script controls MPD while it's active
# even if ncmpc/ncmpcpp is launched otherwise
# mpc will not exactly do what we want to.

command -v mpc >/dev/null || exit 127
[[ -z $(pidof mpd) ]] && exit 1

mpc random off

current=$(mpc --format %position% current)
last=$(mpc playlist | wc -l)
first=$((last / last))

case "$1" in
    next)
        if [[ $current = "$last" ]]; then
            mpc play "$first"
        else
            ((current++))
            mpc play "$current"
        fi
    ;;
    prev)
        if [[ $current = "$first" ]]; then
            mpc play "$last"
        else
            ((current--))
            mpc play "$current"
        fi
    ;;
    toggle)
        mpc toggle
    ;;
    stop)
        mpc stop
    ;;
esac
