#!/bin/bash

# Run this script in the background

metadata="$XDG_RUNTIME_DIR/mpv.txt"

until [[ -n $(pidof mpv) ]]; do
    polybar-msg hook mpv-ipc 1 >/dev/null 2>&1
    if [[ -f "$metadata" ]]; then
        rm "$metadata" >/dev/null 2>&1
        continue
    fi
    sleep 1s

    while [[ -n $(pidof mpv) ]]; do
        picom & >/dev/null 2>&1
        [[ ! -f "$metadata" ]] && touch "$metadata"
        echo '{ "command": ["get_property", "force-media-title"] }' \
        | socat - /tmp/mpvsocket | awk -F '"' '{print $4}' > "$metadata"
        polybar-msg hook mpv-ipc 2 >/dev/null 2>&1
        sleep 1s
    done
    killall -q picom
done

