#!/bin/sh

logfile="${XDG_CACHE_HOME:-$HOME/.cache}/netlog"

touch "$logfile" && echo "0 0" > "$logfile"

read -r rxprev txprev < "$logfile"

rxcurrent="$(($(paste -d '+' /sys/class/net/[ew]*/statistics/rx_bytes)))"
txcurrent="$(($(paste -d '+' /sys/class/net/[ew]*/statistics/tx_bytes)))"

printf " %dKiB  %dKiB\\n" "$(((rxcurrent-rxprev)/1024))" "$(((txcurrent-txprev)/1024))"

echo "$rxcurrent $txcurrent" > "$logfile"
