#!/usr/bin/env bash

# Author: Barret E (2021) <archus@protonmail.com>
# https://github.com/archusXIV/dotfiles
#
# Simple script to get the pid(s) number(s) of a running process.
# We are prompted to kill it or not...
# Of course we could use xkill but what about a background process?
# eg: pidgrep my_script_name [option] (use sudo for root privileges).
# ---------------------------------------------------------------------------------
#   USER    |   PID   |   COMMAND
# ---------------------------------------------------------------------------------
#  archang+  156439      /bin/bash /home/archangel/.local/bin/updates-manager --check
# ---------------------------------------------------------------------------------
#
# Kill [A]ll processes or just [O]ne? (press q to quit).

grn=$'\e[0;32m';
red=$'\e[0;31m';
noc=$'\e[0m';

[[ ! $2 ]] && {
    printf '%s\n' " ${red}At least one option is required." \
    " Try: ${0##*/} <process_name> -[k|t|v]${noc}"
    exit 1
}

case "${2}" in
    -t) kill_option="-TERM" ;;
    -k) kill_option="-KILL" ;;
    -v) view_option=yes ;;
    *) printf '%s\n' " ${red}Wrong option $1" \
    " Try: ${0##*/} <process_name> -[k|t|v]${noc}"; exit 1 ;;
esac

tput clear
: "${USER:=$(whoami)}"

# first test if $1 belongs to systemd.
if systemctl --user status "$1" 2>/dev/null | grep -q 'active'; then
    printf '%s\n' " ${grn}$1 is a running systemd --user unit" \
    " ${red}PLEASE USE: systemctl --user <option> $1.service to manage it.${noc}"
    systemctl --user status "$1"* | awk '/Main PID:/{print}'
    exit 0
elif systemctl status "$1" 2>/dev/null | grep -q 'active'; then
    printf '%s\n' " ${grn}$1 is a running systemd unit" \
    " ${red}PLEASE USE: sudo systemctl <option> $1.service to manage it.${noc}"
    systemctl status "$1"* | awk '/Main PID:/{print}'
    exit 0
fi

# then a regular process.
pids=$(pgrep -u "$USER" -f "$1" | grep -v "^$$\$")

if ! pgrep -f "$1" >/dev/null; then
    echo "No such process: $1"
    exit 0
else
    _printLine() {
        printf -- '-%.0s' {1..81}; printf '\n'
    }

    echo
    _printLine
    echo " ${grn}USER    |   PID   |  COMMAND${noc}"
    _printLine

    # shellcheck disable=SC2086
    ps -fp $pids \
        | awk '
            NR==1{next} {
                    count++
                    if ( count <= 5 ) print $1"   "$2"     "$9" "$10" "$11" "$12
                }
        '
    _printLine

    if [[ $view_option == yes ]]; then
        printf '\n%s\n' " ${red}Option -v is set, killing ${grn}$1 ${red}disabled.${noc}"
        exit 0
    fi

    printf '\n'
    read -rsn 1 \
        -p "${red} Kill [A]ll processes or just [O]ne? (press q to quit).${noc}"

    case "$REPLY" in
        [qQ]) tput clear; exit 0 ;;
        [aA])
            for pid in $pids; do
                kill "$kill_option" "$pid"
            done >/dev/null 2>&1
            echo -e  "\n ${grn}$1 ${red}does not exist anymore...\n${noc}"
            exit 0
        ;;
        [oO])
            printf '\n'
            read -r -p "${red}"' Enter the pid number to kill: '"${noc}" pid
            if ! echo "$pids" | grep -q "^$pid\$"; then
                echo " ${red}wrong pid number...$1 still alive."
                exit 1
            else
                kill "$kill_option" "$pid" && \
                echo -e  "\n ${grn}$1 ${red}does not exist anymore...\n${noc}"
                exit 0
            fi
        ;;
        *) exit 1 ;;
    esac
fi

