#!/usr/bin/env bash

sockets_dir="$XDG_RUNTIME_DIR/polybar"
wm_name=$(awk '/Name/{print $2}' < <(wmctrl -m))

if [[ -d $sockets_dir ]]; then
    # Terminate already polybar instances.
    killall -q --signal SIGKILL {conky,polybar}
    rm -rf {/tmp/polybar_mqueue.*,"$sockets_dir"} 2>/dev/null
fi

# Wait until the process has been closed.
while pgrep -u "$UID" -x polybar; do
    sleep 0.5
done

mapfile -t monitors < <(polybar -M | awk -F: '{print $1}')

# Launching bars according to the number of monitors
# bar names: dk-bar-{1,2,3}, bspwm-bar-{1,2,3}, i3-bar-{1,2,3}
for ((i=1;i<="${#monitors[@]}";i++)); do
    polybar "$wm_name"-bar-"${i}" -q & disown
done

notify-send 'Bars launched...'

exit 0
