#!/usr/bin/env bash

sockets_dir="$XDG_RUNTIME_DIR/polybar"
WM_NAME=$(awk '/Name/{print $2}' < <(wmctrl -m))

if [[ -d $sockets_dir ]]; then
    # Terminate already polybar instances.
    killall -q --signal SIGKILL {conky,polybar}
    rm -rf {/tmp/polybar_mqueue.*,"$sockets_dir"} 2>/dev/null
fi

# Wait until the process has been closed.
while pgrep -u "$UID" -x polybar; do
    sleep 0.5
done

mapfile -t monitors < <(
    xrandr --listactivemonitors | awk '$0 !~ /Monitor/{print $NF}'
)

# Launching bars according to the number of monitors
for ((i=1;i<="${#monitors[@]}";i++)); do
    polybar "$WM_NAME"-bar-"${i}" -q & disown
done

notify-send 'Bars launched...'

exit 0
