#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV/dofiles>
# Manage polybar instances individually using -p option and fullscreen state.
# For instance: 3 monitors (3 bars), 3 window managers (dk, bspwm, i3)
# Dependencies: awk polybar wmctrl
#
# a = all                               | keyboard shortcuts (sxhkd)
# -f: Toggles fullscreen mode           | ctrl + {_,alt,shift} + {1-4}
# -r: Restarts the bar(s).              |     polybar_control -{t,f,r}{1,2,3,a}
# -t: Toggles hidden and visible state. |
#
# ctrl + 1: toggles visibility of polybar on screen one
# ctrl + a: toggles visibility of polybar on all screens
# ctrl + alt + 1: toggles focused window fullscreen on screen one
# ctrl + alt + a: toggles last focused windows fullscreen on all screens
# ctrl + shift + 1: restarts polybar on screen one
# ctrl + shift + a: restarts all polybar instances
# See: man polybar-msg

for dep in awk polybar wmctrl; do
    command -v "${dep}" >/dev/null || {
        echo "$dep is not installed. Exiting..."
        exit 127
    }
done

# Getting monitors names and polybar pids
mapfile -t monitors < <(polybar -M | awk -F: '{print $1}')
mapfile -t barpids < <(pgrep polybar)

((${#barpids[@]} != ${#monitors[@]})) && exit 1

for ((i=0;i<${#monitors[@]};i++)); do
    monitor+=("$((i+1))")
    barpid+=("${barpids[$i]}")
done

declare -A mon_id pid_id
for ((i=1;i<=${#monitor[@]};i++)); do
    mon_id[$i]="${monitor[$((i-1))]}"
    pid_id[$i]="${barpid[$((i-1))]}"
done

action="${1#-}"
option="${action:0:1}"
num="${action:1}"
wm_name=$(wmctrl -m | awk '/Name:/{print $2}')

_WmFocusMonitor() {
    [[ $wm_name == dk ]] && dkcmd mon "${mon_id[$num]}"
    [[ $wm_name == bspwm ]] && bspc monitor -f "${mon_id[$num]}"
    [[ $wm_name == i3 ]] && i3-msg focus output "${mon_id[$num]}"
}

_ToggleFullscreen() {
    case "$1" in
        --all)
            # awk has to ignore polybar ids from wmctrl output
            # if the window manager can or do manage them.
            wmctrl -l | awk '$2 != -1 {print $1}' \
            | xargs -I {} wmctrl -i -r {} -b toggle,fullscreen
        ;;
        --focused)
            _WmFocusMonitor
            [[ $wm_name == dk ]] && { dkcmd win full; exit; }
            # No need to test $WM here, this test will fail if bspwm isn't running
            [[ -n $(bspc query -N -n focused.fullscreen) ]] && {
                bspc node focused -t tiled || bspc node focused -t fullscreen
                exit
            }
            [[ $wm_name == i3 ]] && { i3-msg fullscreen toggle; exit; }
        ;;
    esac
}

[[ -z $num && -n "$2" ]] && num="$2"
[[ $option == f && $num == a ]] && _ToggleFullscreen --all
[[ $option == t && $num == a ]] && { polybar-msg cmd toggle; exit; }
[[ $option == r && $num == a ]] && { polybar-msg cmd restart; exit; }

case "$option" in
    f) _ToggleFullscreen --focused ;;
    r)
        [[ -n "${pid_id[$num]}" ]] || { echo "Invalid bar number: $num"; exit 1; }
        polybar-msg -p "${pid_id[$num]}" cmd restart
    ;;
    t)
        [[ -n "${mon_id[$num]}" ]] || { echo "Invalid monitor number: $num"; exit 1; }
        _WmFocusMonitor "${mon_id[$num]}"
        polybar-msg -p "${pid_id[$num]}" cmd toggle
    ;;
    *)
        echo "Invalid option: $option"
        exit 1
    ;;
esac
exit

