#!/bin/bash

# Author: Barret E (2022) <archus@protonmail.com>
# https://github.com/archusXIV/dotfiles
# Simple script to control pulseaudio volume/microphone.
# For instance I use the polybar [module/pulseaudio-ipc] (sink) for sound output,
# and for my microphone (source) [module/mic-ipc]
# https://github.com/archusXIV/dotfiles/blob/main/polybar/active-modules-bar2.conf
# Usage: pulseaudio_control --sink {up,down,toggle}
#        pulseaudio_control --source {up,down,toggle}

[[ -z $(pidof polybar) ]] && exit 1

default_sink=$(pactl get-default-sink)
default_source=$(pactl get-default-source)

get_sink_mute=$(pactl get-sink-mute "${default_sink}")
get_source_mute=$(pactl get-source-mute "${default_source}")

_hook_sink_on() { polybar-msg hook pulseaudio-ipc 2 >/dev/null 2>&1; }
_hook_source_on() { polybar-msg hook mic-ipc 2 >/dev/null 2>&1; }

case "$1" in
    --sink)     case "$2" in
                    up)     if [[ ${get_sink_mute} == 'Mute: yes' ]]; then
                                pactl set-sink-mute "${default_sink}" toggle
                                pactl set-sink-volume "${default_sink}" -5%
                                _hook_sink_on
                            else
                                pactl set-sink-volume "${default_sink}" +5%
                                _hook_sink_on
                            fi
                    ;;
                    down)   pactl set-sink-volume "${default_sink}" -5%
                            _hook_sink_on
                    ;;
                    toggle) pactl set-sink-mute "${default_sink}" toggle
                            if [[ ${get_sink_mute} == 'Mute: yes' ]]; then
                                _hook_sink_on
                            else
                                polybar-msg hook pulseaudio-ipc 1 >/dev/null 2>&1
                            fi
                    ;;
                esac
    ;;
    --source)   case "$2" in
                    up    ) if [[ ${get_source_mute} == 'Mute: yes' ]]; then
                                pactl set-source-mute "${default_source}" toggle
                                pactl set-source-volume "${default_source}" 75%
                                _hook_source_on
                            else
                                pactl set-source-volume "${default_source}" +1%
                                _hook_source_on
                            fi
                    ;;
                    down  ) pactl set-source-volume "${default_source}" -1%
                            _hook_source_on
                    ;;
                    toggle) if [[ ${get_source_mute} == 'Mute: yes' ]]; then
                                pactl set-source-mute "${default_source}" toggle
                                pactl set-source-volume "${default_source}" 75%
                                _hook_source_on
                            else
                                pactl set-source-mute "${default_source}" toggle
                                pactl set-source-volume "${default_source}" 0%
                                polybar-msg hook mic-ipc 1 >/dev/null 2>&1
                            fi
                    ;;
                esac
    ;;
esac
