#!/bin/bash

_chrono1() {
	date1=`date +%s`; while true; do
		echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r" > "$XDG_CACHE_HOME"/chrono.txt
		sleep 1s
		polybar-msg hook chrono-ipc-1 1 >/dev/null 2>&1
	done
}

_chrono2() {
	date1=`date +%s`; while true; do
		echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r" > "$XDG_CACHE_HOME"/chrono.txt
		sleep 1s
		polybar-msg hook chrono-ipc-2 1 >/dev/null 2>&1
	done
}

_chrono3() {
	date1=`date +%s`; while true; do
		echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r" > "$XDG_CACHE_HOME"/chrono.txt
		sleep 1s
		polybar-msg hook chrono-ipc-3 1 >/dev/null 2>&1
	done
}

case "$1" in
	1) _chrono1 ;;
	2) _chrono2 ;;
	3) _chrono3 ;;
esac
