#!/bin/bash

#  Author: Barret E (2021) <archus@protonmail.com>
#  Dependencies: ffmpeg, polybar, rofi, simplescreenrecorder.
#
#  This script uses two screen grabbing methods:
#  simplescreenrecorder or anohter of my scripts called rofi-record.
#  Each time you will be prompt to choose a screen (monitor) to capture.
#  Of course you will have to set profiles in simplescreenrecorder gui first
#  to be able to use them later here.

declare -a deps=( "ffmpeg" "polybar" "rofi" "simplescreenrecorder" )

for i in "${deps[@]}"; do
    [[ -z $(command -v "$i") ]] && {
        notify-send "$i isn 't installed, bye..."
        exit 165
    }
done

_main() {

    case "$1" in
        -r) rofi-record &         # external script
            exit
        ;;
        -s) _simplescreenrecorder # calls below function
            exit
        ;;
        -k) if [[ -z $(pidof simplescreenrecorder) ]] \
                || [[ -z $(pidof -x rofi-record) ]]; then
                amixer set Capture,0 0%,0% mute nocap >/dev/null 2>&1
                polybar-msg action "#mic-ipc.hook.0" >/dev/null 2>&1
                exit
            fi
        ;;
    esac

}

_simplescreenrecorder() {

    local SCREENS triplescreen screen1 screen2 screen3 WM

    WM=$(wmctrl -m | awk '/Name/{print $2}')

    # Profiles:
    SCREENS="$XDG_CONFIG_HOME/simplescreenrecorder/input-profiles"
    triplescreen="$SCREENS/triplescreen.conf"
    screen1="$SCREENS/screen1.conf"
    screen2="$SCREENS/screen2.conf"
    screen3="$SCREENS/screen3.conf"

    _all_monitors() (

        amixer set Capture,0 75%,75% unmute cap >/dev/null 2>&1
        polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
        record_chrono 2 &

        [[ $WM == 'bspwm' ]] && bspc desktop --focus '^5' \
        || [[ $WM == 'i3' ]] && i3-msg workspace 5

        simplescreenrecorder \
        --start-hidden \
        --settingsfile="$triplescreen" \
        --start-recording && {

            killall --quiet record_chrono
            amixer set Capture,0 0%,0% mute nocap >/dev/null 2>&1
            polybar-msg action "#mic-ipc.hook.0" >/dev/null 2>&1
            polybar-msg action "#chrono-ipc-2.hook.1" >/dev/null 2>&1

        }
    )

    _screencast1() (

        amixer set Capture,0 75%,75% unmute cap >/dev/null 2>&1
        polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
        record_chrono 1 &

        [[ $WM == 'bspwm' ]] && bspc desktop --focus '^1' \
        || [[ $WM == 'i3' ]] && i3-msg workspace 1

        simplescreenrecorder \
        --start-hidden \
        --settingsfile="$screen1" \
        --start-recording && {

            killall --quiet record_chrono
            amixer set Capture,0 0%,0% mute nocap >/dev/null 2>&1
            polybar-msg action "#mic-ipc.hook.0" >/dev/null 2>&1
            polybar-msg action "#chrono-ipc-1.hook.1" >/dev/null 2>&1

        }
    )

    _screencast2() (

        amixer set Capture,0 75%,75% unmute cap >/dev/null 2>&1
        polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
        record_chrono 2 &

        [[ $WM == 'bspwm' ]] && bspc desktop --focus '^5' \
        || [[ $WM == 'i3' ]] && i3-msg workspace 5

        simplescreenrecorder \
        --start-hidden \
        --settingsfile="$screen2" \
        --start-recording && {

            killall --quiet record_chrono
            amixer set Capture,0 0%,0% mute nocap >/dev/null 2>&1
            polybar-msg action "#mic-ipc.hook.0" >/dev/null 2>&1
            polybar-msg action "#chrono-ipc-2.hook.1" >/dev/null 2>&1

        }
    )

    _screencast3() (

        amixer set Capture,0 75%,75% unmute cap >/dev/null 2>&1
        polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
        record_chrono 2 &

        [[ $WM == 'bspwm' ]] && bspc desktop --focus '^10' \
        || [[ $WM == 'i3' ]] && i3-msg workspace 10

        simplescreenrecorder \
        --start-hidden \
        --settingsfile="$screen3" \
        --start-recording && {

            killall --quiet record_chrono
            amixer set Capture,0 0%,0% mute nocap >/dev/null 2>&1
            polybar-msg action "#mic-ipc.hook.0" >/dev/null 2>&1
            polybar-msg action "#chrono-ipc-2.hook.1" >/dev/null 2>&1

        }
    )

    # testing our monitors setup to launch the right options.
    if [[ $(xrandr | grep -cw connected) -eq 1 ]]; then
        _screencast1
    elif [[ $(xrandr | grep -cw connected) -eq 2 ]]; then
        choice=$(printf "all_monitors\\nmonitor1\\nmonitor2" \
        | rofi -normal-window -dmenu -i -width 20 -hide-scrollbar \
        -line-padding 4 -padding 20 -lines 3 -p 'Pick a monitor to capture')
        case "$choice" in
            all_monitors) _all_monitors ;;
            monitor1    ) _screencast1  ;;
            monitor2    ) _screencast2  ;;
        esac
    elif [[ $(xrandr | grep -cw connected) -eq 3 ]]; then
        choice=$(printf "all_monitors\\nmonitor1\\nmonitor2\\nmonitor3" \
        | rofi -normal-window -dmenu -i -width 20 -hide-scrollbar \
        -line-padding 4 -padding 20 -lines 4 -p 'Pick a monitor to capture')
        case "$choice" in
            all_monitors) _all_monitors ;;
            monitor1    ) _screencast1  ;;
            monitor2    ) _screencast2  ;;
            monitor3    ) _screencast3  ;;
        esac
    else
        exit
    fi

}

_main "${@}"
