#!/bin/bash

if [[ -n $(pidof bspwm) ]]; then
    for proc in sxhkd-watcher bspc-layout; do
        killall -q "$proc"
    done
    bspc wm -r
elif [[ -n $(pidof i3) ]]; then
    i3-msg -q restart
else
    echo "no running Bspwm or i3 instance found" && exit 1
fi
