#!/bin/bash

WmName=$(wmctrl -m | awk '/Name: /{print $2}')

WinId() { wmctrl -lx | awk '{print $1}'; }

case "$1" in
    restartmsg)
        for wd in $(WinId); do
            [[ $WmName == bspwm ]] && xdo close "$wd"
            [[ $WmName == i3 ]] && xdo close "$wd"
            [[ $WmName == dk ]] && dkcmd win "$wd" kill
        done
    ;;
    reloadmsg )
        if [[ $WmName = bspwm ]]; then
            "$HOME"/.config/bspwm/bspwmrc -c
        elif [[ $WmName = i3 ]]; then
            i3-msg reload
        elif [[ $WmName = dk ]]; then
            "$HOME"/.config/dk/dkrc
        fi
    ;;
esac
