#!/usr/bin/env bash

rc="$HOME/.config/dmenu/dmenurc"

[ -f "$rc" ] && . "$rc"

confDir="$HOME/.config/"

dirOptions=$(cd ${confDir} && ls -d */ | cut -d " " -f 1)
dirChoice=$(echo -e "${dirOptions[@]}\nquit" \
    | rofi -normal-window -dmenu -i -width 20 -hide-scrollbar \
    -line-padding 4 -padding 20 -lines 5 -p 'Config directories ')

if [ "$dirChoice" == "quit" ]; then
    echo dmenu closed.
elif [ "$dirChoice" == ${dirChoice} ]; then
    fileOptions=$(cd ${confDir}${dirChoice} && ls -Ap | cut -d " " -f 1 | grep -v / )
    fileChoice=$(echo -e "${fileOptions[@]}" \
    | rofi -normal-window -dmenu -i -width 20 -hide-scrollbar \
    -line-padding 4 -padding 20 -lines 4 -p 'Edit this file: ')
    exec geany ${confDir}${dirChoice}${fileChoice}
fi
