#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP=''

NAME=$(basename "$0")
VER="0.5"

usage()
{
    cat <<- EOF

 USAGE:  $NAME [OPTIONS]

 OPTIONS:

     -h,--help          Display this message

     -v,--version       Display script version

     -r,--run           Application launcher

     -w,--window        Switch between windows

     -l,--logout        System logout dialog

  Without any options the run dialog will be opened.

EOF
}

for arg in "$@"; do
    case $arg in
        -r|--run)
            rofi -normal-window -modi run,drun -show drun -line-padding 4 \
            -columns 2 -padding 50 -hide-scrollbar
            ;;
        -w|--window)
            rofi -normal-window -modi window -show window -no-show-icons \
            -hide-scrollbar -padding 70 -line-padding 4
            ;;
        -l|--logout)
            if grep -q 'exec startx' $HOME/.*profile; then
                ANS="$(rofi -normal-window -sep "|" -dmenu -i -p 'System' -width 20 \
                    -hide-scrollbar -line-padding 4 -padding 20 \
                    -lines 3 <<< " Lock| Reboot| Shutdown")"
            else
                ANS="$(rofi -normal-window -sep "|" -dmenu -i -p 'Power options' -width 250 \
                    -hide-scrollbar -line-padding  -padding 20 \
                    -lines 5 <<< " Reload| Lock| Exit| Reboot| Shutdown")"
            fi

            case "$ANS" in
                *Lock) scrot_lock ;;
                *Reboot) sudo reboot ;;
                *Shutdown) sudo poweroff ;;
                *Exit) Xexit ;;
                *Reload) restart_wm ;;
            esac
            ;;
        *)
            printf "\nOption does not exist: %s\n\n" "$arg"
            exit 2
            ;;
    esac
done

(( $# == 0 )) && "$0" -r

exit 0
