#!/usr/bin/env bash
#
# Author: Barret E (2026) <https://github.com/archusXIV/>
# Script name: rofi_chooser
# License: GPLv2
#
# shellcheck disable=SC2012
declare -a choices=(
    Applications Autoscript Configs Find Fonts
    Keybindings Pass Record Themes Windows
)

choice=$(
    printf '%s\n' "${choices[@]}" \
    | rofi \
    -normal-window \
    -dmenu \
    -i \
    -p 'Rofi scripts' \
    -no-show-icons \
    -width 500 \
    -lines 10 \
    -location 0
)

_autoscript_menu() {
    [[ -z ${SCRIPTDIR+x} ]] && exit 1

    _autoscript() {
        local date script_file
        date=$(date +%Y)
        script_file="$SCRIPTDIR/$1"

        if [[ -f $script_file ]]; then
            "$EDITOR" "$script_file" & disown
        else
            cat > "$script_file" <<EOF
#!/usr/bin/env bash
#
# Author: Barret E ($date) <https://github.com/archusXIV/>
# Script name: ${script_file##*/}
# License: GPLv2

EOF
            chmod +x "$script_file"
            "$EDITOR" "$script_file" & disown
        fi
    }

    selected=$(
        find "$HOME"/.local/bin \
        -maxdepth 1 \
        -type f \
        -printf '%f\n' \
        | sort \
        | rofi -i \
        -normal-window \
        -dmenu \
        -width 30 \
        -hide-scrollbar \
        -line-padding  \
        -padding 20 \
        -lines 10 \
        -p "edit/create a script "
    )

    [[ -z $selected ]] && exit

    _autoscript "$selected"
}

_passwd_copy() {
    local list selected
    list="$HOME/Documents/.admin/pass/pass.txt"

    selected=$(
        awk '{print $1}' "$list" \
        | rofi -i \
            -normal-window \
            -dmenu \
            -columns 2 \
            -width 30 \
            -hide-scrollbar \
            -line-padding 2 \
            -padding 20 \
            -lines 10 \
            -p "Choose an account "
    )

    [[ -z $selected ]] && exit

    awk -v SEL="$selected" '$0 ~ SEL { print $2" "$3 }' < "$list" | xclip -sel clip
    exit
}

_rofi_configs() {
    local conf_dir dir_options dir_choice file_options file_choice

    conf_dir="$HOME/.config/"
    dir_options=$(cd "${conf_dir}" && ls -d ./* | cut -d " " -f 1)
    dir_choice=$(echo -e "${dir_options[*]}\nquit" \
        | rofi -normal-window -dmenu -i -width 20 -hide-scrollbar \
        -line-padding 4 -padding 20 -lines 5 -p 'Config directories ')
    file_options=$(cd "${conf_dir}${dir_choice}" && ls -Ap | cut -d " " -f 1 | grep -v / )
    file_choice=$(echo -e "${file_options[@]}" \
        | rofi -normal-window -dmenu -i -width 20 -hide-scrollbar \
        -line-padding 4 -padding 20 -lines 4 -p 'Edit this file: ')

    if [[ -z $dir_choice ]]; then
        exit 0
    else
        [[ -z $file_choice ]] && exit 0
        exec geany "${conf_dir}/${dir_choice}/${file_choice}" & disown
        exit
    fi
}

_theme_selector() {
    local xres_file selected
    xres_file="${RESOURCES_FILE:-$HOME/.Xresources}"

    selected="$(
        ls "$XDG_CONFIG_HOME"/xfiles/themes \
        | rofi -i -normal-window \
        -dmenu -width 40 \
        -hide-scrollbar \
        -line-padding  \
        -padding 20 \
        -lines 10 \
        -columns 4 \
        -p "The actual theme is $(grep themes "$xres_file" | sed 's,.*/,,;s/"//')"
    )"

    [[ ! -f $xres_file ]] && echo "$xres_file: no such file or directory" && exit 1
    [[ ! -f "$HOME"/.config/xfiles/themes/$selected ]] && exit 1

    sed -i --follow-symlinks \
        "/\#include \"\.config\/xfiles\/themes\//c\\#include \"\.config\/xfiles\/themes\/$selected\"" \
        "$xres_file"

    sleep 1s

    xrdb -load "$xres_file" \
    && restart_wm reloadmsg \
    && Terminal_theme_changer \
    && xre2rasi \
    && polybar_start \
    && sxhkd_start \
    && notify-send 'theme changed'
    local config_dir="$HOME/.config/g810-led"
    local profile="$config_dir/profiles/profile_$selected"
    [[ -f $profile ]] && g810_switch_profile "$selected"
    exit 0
}

case "$choice" in
    Applications)
        rofi -i -normal-window -modi run,drun \
        -show drun -line-padding 4 -columns 2 \
        -padding 50 -hide-scrollbar
    ;;
    Autoscript)
        _autoscript_menu
    ;;
    Configs)
        _rofi_configs
    ;;
    Find)
        if [[ $(systemctl status plocate-updatedb.timer \
            | awk '/Active:/{print $3}') = '(waiting)' ]]; then
            locate / | rofi -normal-window -threads 0 \
            -width 50 -dmenu -i -p "locate in system" | xargs -r -0 xdg-open
        else
            sudo updatedb
            locate / | rofi -normal-window -threads 0 \
            -width 50 -dmenu -i -p "locate in system" | xargs -r -0 xdg-open
        fi
    ;;
    Fonts)
        fontawesomemenu -f "$HOME"/Documents/theming/fa4-icon-list.txt; exit
    ;;
    Keybindings)
        WM_NAME=$(wmctrl -m | awk '/Name/{print $2}')
        awk '/^[a-zA-Z]/ && last {print $0,"\t",last} \
        {last=""} /^#/{last=$0}' ~/.config/sxhkd/"$WM_NAME"_sxhkdrc_memo \
        | column -t -s $'\t' | rofi -normal-window -dmenu -no-show-icons \
        -width 1200 -location 0 -i -p "$WM_NAME keybindings memo"
        exit 0
    ;;
    Pass  ) _passwd_copy ;;
    Record) rofi-record & ;;
    Themes) _theme_selector ;;
    Windows) rofi -modi window -show window -location 0 -width 850 & ;;
esac

exit