#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP=''

NAME=$(basename "$0")

usage() {
    cat <<- EOF

    USAGE:  $NAME [OPTIONS]

    OPTIONS:
    -h,--help          Display this message
    -l,--logout        System logout dialog
    -r,--run           Application launcher
    -s,--sleep         Put monitor(s) in sleepping modes
    -w,--window        Switch between windows

    Without any options the run dialog will be opened.

EOF
}

for arg in "$@"; do
    case $arg in
        -h) usage ;;
        -l|--logout)
            if grep -q 'exec startx' "$HOME"/.*profile; then
                ANS="$(rofi -normal-window -sep "|" -dmenu -i -p 'System' -width 20 \
                    -hide-scrollbar -line-padding 4 -padding 20 \
                    -lines 3 <<< " Lock| Reboot| Shutdown")"
            else
                ANS="$(rofi -normal-window -sep "|" -dmenu -i -p 'Power options' -width 250 \
                    -hide-scrollbar -line-padding  -padding 20 \
                    -lines 5 <<< " Restart WM| Lock| Exit| Reboot| Shutdown")"
            fi

            case "$ANS" in
                *Lock) scrot_lock ;;
                *Reboot) sudo reboot ;;
                *Shutdown) sudo poweroff ;;
                *Exit) session_exit ;;
                *Restart) restart_wm restartmsg ;;
            esac
            ;;
        -r|--run)
            rofi -normal-window -modi run,drun -show drun -line-padding 4 \
            -columns 2 -padding 50 -hide-scrollbar
            ;;
        -s|--sleep)
            _SleepOption() { xset +dpms; xset dpms force "$1"; }
            ANS="$(rofi -normal-window -sep "|" -dmenu -i -p 'Monitors sleep options' -width 255 \
                -hide-scrollbar -line-padding  -padding 20 \
                -lines 3 <<< " StandBy| Suspend| Power_off")"
            case "$ANS" in
                *StandBy) _SleepOption standby ;;
                *Suspend) _SleepOption suspend ;;
                *Power_off) _SleepOption off ;;
            esac
            ;;
        -w|--window)
            rofi -normal-window -modi window -show window -no-show-icons \
            -hide-scrollbar -padding 70 -line-padding 4
            ;;
        *)
            printf "\nOption does not exist: %s\n\n" "$arg"
            exit 2
            ;;
    esac
done

(( $# == 0 )) && "$0" -r

exit 0