#!/bin/bash

# This script hide and show focused windows whithin you favorite
# window manager or DE by using xdo to proceed
# We can also use rofi to select and show back hidden windows

_Dependencies() {
    DEPS=( "polybar" "rofi" "wmctrl" "xdo" "xprop" "xset" )

    for pkg in "${DEPS[@]}"; do
        [[ -z $(which $pkg) ]] \
        && notify-send "$pkg is not installed...exiting" \
        && exit 127
    done
}

# Place your polybar module in bar-3
BARPID=$(pgrep --full $(wmctrl -m | awk '/Name/{print $2}')-bar-3)

_Indicator() {
    case "$1" in
        off)    xset -led 3
                polybar-msg -p "$BARPID" \
                action "#scratchpad-ipc.hook.0" >/dev/null 2>&1
                notify-send 'nothing else in scratchpad'
        ;;
        on )    xset led 3
                polybar-msg -p "$BARPID" \
                action "#scratchpad-ipc.hook.1" >/dev/null 2>&1
        ;;
    esac
}

TARGET=$(xdo id ${1})
ID_LIST="$XDG_RUNTIME_DIR/scratchpad_hidden.list"
ID_LIST_ALL="$XDG_RUNTIME_DIR/scratchpad_all.list"

case "$1" in
    -h) # sending all existing windows ids/instances/classes in a file to keep track
        _Dependencies
        wmctrl -lx | awk '{print $1" "$3}' > "$ID_LIST_ALL"
        # using lowercases will match ids in $ID_LIST_ALL
        echo "$TARGET" | tr [:upper:] [:lower:] >> "$ID_LIST"
        xdo hide "$TARGET"
        _Indicator on
    ;;
    -u) if [[ $(xprop -id $(sed -n '1p' "$ID_LIST") \
            | awk '/window state: / {print $3}') = Withdrawn ]]; then
            # show the first entry
            xdo show "$(sed -n '1p' "$ID_LIST")"
            # remove it from the list
            sed -i '1d' "$ID_LIST"
            if (( $(grep "" -c "$ID_LIST") > 0 )); then
                _Indicator on
            else
                _Indicator off
            fi
        else
            _Indicator off
        fi
    ;;
    -r) if (( $(grep "" -c $ID_LIST) > 0 )); then

            HIDDEN=$(cat $ID_LIST)

            # making a rofi menu
            N=$(for w in $HIDDEN; do
                NAME=$(xprop -id "$w" WM_CLASS 2>/dev/null | sed -r 's/.+ "(.+)"$/\1/')
                TITLE=$(xprop -id "$w" _NET_WM_NAME 2>/dev/null | sed -r 's/.+ "(.+)"$/\1/')
                [[ "$NAME" = "WM_CLASS" ]] && echo "$w" || echo "$NAME  \"$TITLE\""
            done | rofi -dmenu -no-custom -format i -p 'Unhide a window: ')

            [[ -n "$N" ]] && {

                ID=$(echo "$HIDDEN" | sed -n "$((N+1))p")
                xdo show "$ID"

                sed -i "/${ID}/d;/^\s*$/d" "$ID_LIST"

                if (( $(grep "" -c $ID_LIST) > 0 )); then
                    _Indicator on
                else
                    _Indicator off
                fi
            }

        else
            _Indicator off
        fi
    ;;
esac
