#!/bin/bash

scrot_path="$HOME/Documents/Pictures/screens"
viewer="feh" # Can edit images too.
rc="$HOME/.config/dmenu/dmenurc"

[ -f "$rc" ] && source "$rc"

choice=$(printf "quick_fullscreen\\ndelayed_fullscreen\\nselection\\nfocused_window" \
        | dmenu -i $DMENU_OPTIONS -p "Select a capture type:")

cd "$scrot_path" || exit 1

case "$choice" in
    quick_fullscreen)   scrot '%d-%m-%Y-@%H-%M-%S-full.png' \
                        -e "$viewer \$f" && notify-send 'Fullscreen taken and saved'
    ;;
    delayed_fullscreen) scrot -d 15 '%d-%m-%Y-@%H-%M-%S-full.png' \
                        -e "$viewer \$f" && notify-send 'Fullscreen taken and saved'
    ;;
    selection)          scrot -s '%d-%m-%Y-@%H-%M-%S-selection.png' \
                        -e "$viewer \$f" && notify-send 'Screenshot of selection saved'
    ;;
    focused_window)     scrot -u -b '%d-%m-%Y-@%H-%M-%S-focused.png' \
                        -e "$viewer \$f" && notify-send 'Focused window captured'
    ;;
    *)                  notify-send 'No screenshot taken!'
    ;;
esac
