#!/bin/bash

# Listen on sxhkd events to:
# - indicates when in a chord chain,
# - indicates the last hotkey and the corresponding command.

pid=$(pgrep --full "$(wmctrl -m | awk '/Name/{print $2}')"-bar-1)
cmd="$XDG_RUNTIME_DIR/cmd.txt"
keys="$XDG_RUNTIME_DIR/keys.txt"

while read -r line; do
    if [[ "$line" == 'EEnd chain' ]]; then
        polybar-msg -p "$pid" action \
        "#sxhkd-ipc.hook.1" >/dev/null 2>&1
    elif [[ "$line" == 'BBegin chain' ]]; then
        polybar-msg -p "$pid" action \
        "#sxhkd-ipc.hook.0" >/dev/null 2>&1
    elif [[ "$line" =~ 'H' ]]; then
        echo "$line" > "$keys"
        polybar-msg -p "$pid" action \
        "#hotkeys-ipc.hook.1" >/dev/null 2>&1
    elif [[ "$line" =~ 'C' ]]; then
        echo "$line" > "$cmd"
        polybar-msg -p "$pid" action \
        "#command-ipc.hook.1" >/dev/null 2>&1
    fi
done < "$SXHKD_FIFO"
