#!/usr/bin/env bash

# Terminate existing sxhkd scripts instances

if [[ -n $(pidof -x sxhkd) ]]; then
    for proc in sxhkd-watcher sxhkd; do
        killall -q "$proc"
    done

    # Wait until the process has been shut down
    while pgrep -u $UID -x sxhkd >/dev/null; do

        sleep 0.5

    done
fi

fifo="$XDG_RUNTIME_DIR/sxhkd.fifo"

[[ -e $fifo ]] && rm -f "$fifo"
sleep 0.5
mkfifo "$fifo"

if [[ -n $(pidof bspwm) ]]; then
    # Launch sxhkd, with the -s option for the listener script.
    sxhkd -t 6 \
    -s "$fifo" \
    -c "$HOME"/.config/sxhkd/sxhkdrc{,_bspc} &

    sxhkd-listener &
    notify-send 'hotkeys daemon ready'
    rm -f "$HOME"/1 >/dev/null
elif [[ -n $(pidof i3) ]]; then
    # Launch sxhkd within i3
    sxhkd -t 6 \
    -s "$fifo" \
    -c "$HOME"/.config/sxhkd/sxhkdrc &

    sxhkd-listener &
    notify-send 'hotkeys daemon ready'
    rm -f "$HOME"/1 >/dev/null
else
    exit 1
fi
