#!/usr/bin/env sh
#
# Listen on sxhkd events to:
# - indicate when in a chord chain

fifo="$XDG_RUNTIME_DIR/sxhkd.fifo"
keys="$XDG_RUNTIME_DIR/keys.txt"

exec 3< "${fifo}"
while read -r line <&3; do
    case "$line" in
        B*) hook=1 ;;
        E*) hook=2 ;;
    esac
    polybar-msg action "#sxhkd-ipc.hook.${hook}"
done
exec 3<&-
