#!/usr/bin/env bash

################################################
# script name: sysinfo                         #
# Copyright (C) 2026 Barret E                  #
# By: ArchusXIV <https://github.com/archusXIV> #
# License: GPL v2.0                            #
################################################

# fancy stuff
G=$'\e[0;32m'
R=$'\e[0;31m'
Y=$'\e[0;33m'
Z=$'\e[0m'
# Modify this to fit the longest output
dashes=$(printf "%-77s" "-")

distro=$(awk -F'\t' '/Description:/ { print $2 }' < <(lsb_release -a))
kernelver=$(uname -sr)
arch=$(uname -m)
shell="$SHELL"
cpu_model=$(awk -F: '/Model name:/{ sub(/^[ \t]+/,"",$2); print $2 }' < <(lscpu))
cpu_threads=$(awk -F: '/^CPU\(s):/{ sub(/^[ \t]+/,"",$2); print $2 }' < <(lscpu))

if lscpu | grep -q "CPU max MHz" &>/dev/null; then
    cpu_freq=$(awk -F: '/CPU max MHz:/{ sub(/^[ \t]+/,"",$2); print $2 " MHz" }' < <(lscpu))
else
    cpu_freq=$(awk -F: '/CPU MHz:/{ sub(/^[ \t]+/,"",$2); print $2 " MHz" }' < <(lscpu))
fi

gpu_cpu=$(awk -F: '/VGA/ { sub(/[^\s]/,"",$3); print $3; exit }' < <(lspci))
gpu_dedicated=$(awk -F: '/VGA/ { sub(/[^\s]/,"",$3); count++; if (count == 2) print $3 }' < <(lspci))
mem_total=$(awk 'NR==2 { print $2 " MiB" }' < <(free -m))
mem_used=$(awk '/Mem:/{ print ($2 - $4 - $6 + $5) " MiB" }' < <(free -m))

block_dev() {
    mapfile -t blocks < <(lsblk)
    echo "${Y}Block Devices:"
    for ((i=1;i<=${#blocks[@]};i++)); do
        echo "    ${R}> ${G}$(lsblk -o NAME,FSTYPE,MOUNTPOINT,SIZE,FSUSED,FSAVAIL | sed -n "${i}p")"
    done
}

network=$(
    echo -e "${Y}IP Configuration: \n${G}$(ip addr \
    | awk \
    -v red="${R}" \
    -v green="${G}" '
        /\<inet\>/ { sub(/\<inet\>/, red "> " green "inet"); print }
        '
    )"
)

tput clear
printf '\n%s' \
"  ${R}* ${G}$(whoami)${R}@${Y}$(</etc/hostname) ${R}${G}${dashes// /-}>${R}" \
"  * ${Y}Command Shell: ${R}$shell" \
"  * ${Y}Distribution: ${R}$distro ${G}BTW${R}" \
"  * ${Y}Kernel Version: ${R}$kernelver" \
"  * ${Y}Architecture: ${R}$arch" \
"  * ${Y}System Uptime: ${R}$(uptime -p)" \
"  * ${Y}CPU Model: ${R}$cpu_model" \
"  * ${Y}CPU Threads: ${R}$cpu_threads" \
"  * ${Y}CPU Clock: ${R}$cpu_freq" \
"  * ${Y}GPU - CPU: ${R}$gpu_cpu" \
"  * ${Y}GPU (dedicated): ${R}$gpu_dedicated" \
"  * ${Y}Memory Usage: ${R}$mem_used / $mem_total" \
"  * $(block_dev)${R}" \
"  * $network${Z}" \
""
