#!/usr/bin/env bash
# First change colors in ~/.Xresources, then run this script

xrdb_query() {
    for scope in {urxvt,"\\*"}; do
      value=$(xrdb -query | grep -i "^${scope}\.$1:" | cut -f 2)
      if [ -n "${value}" ]; then
        echo "${value}"
        return 0
      fi
    done
    return 1
}

sequences=""
for i in $(seq 0 15); do
    sequences+="\033]4;${i};$(xrdb_query "color${i}")\007"
done
sequences+="\033]10;$(xrdb_query foreground)\007"
sequences+="\033]11;$(xrdb_query background)\007"
sequences+="\033]12;$(xrdb_query cursor)\007"
sequences+="\033]17;$(xrdb_query highlightColor)\007"
sequences+="\033]708;$(xrdb_query borderColor || xrdb_query background)\007"

for term in /dev/pts/[0-9]*; do
  printf "%b" "${sequences}" > "${term}" &
done
