#!/bin/sh
#
# ufetch-arch - tiny system info for arch

## INFO
# user is already defined
host="$(cat /etc/hostname)"
distro='Arch Linux (BTW)'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
aur="$(pacman -Qm | wc -l)"
shell="${SHELL##*/}"

if [ -z "${WM}" ]; then
    if [ "${XDG_CURRENT_DESKTOP}" ]; then
        envtype='DE'
        WM="${XDG_CURRENT_DESKTOP}"
    elif [ "${DESKTOP_SESSION}" ]; then
        envtype='DE'
        WM="${DESKTOP_SESSION}"
    else
        envtype='WM'
        WM="$(wmctrl -m | awk '/Name:/{ print $2 }')"
    fi
else
    envtype='WM'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
# black="$(tput setaf 0)"
red="$(tput setaf 1)"
# green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
# blue="$(tput setaf 4)"
# magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
hc="${reset}${bold}${cyan}"  # user and hostname
lc="${reset}${bold}${cyan}"  # labels
ic="${reset}${bold}${white}" # info
ac="${reset}${bold}${red}"   # aur
# c0="${reset}${bold}${cyan}"  # first color
c1="${reset}${yellow}"       # second color

## OUTPUT
echo ""
cat <<EOF
${c1}        /\        ${hc}${USER}${ic}@${hc}${host}${reset}
${c1}       /^^\       ${lc}DISTRO:   ${ic}${distro}${reset}
${c1}      /    \      ${lc}KERNEL:   ${ic}${kernel}${reset}
${c1}     /      \     ${lc}UPTIME:   ${ic}${uptime}${reset}
${c1}    /   __   \    ${lc}PACKAGES: ${ic}${packages}${reset}
${c1}   /   (  )   \   ${lc}AUR PKGS: ${ac}${aur}${reset}
${c1}  / ___|  |__  \  ${lc}SHELL:    ${ic}${shell}${reset}
${c1} ///          \\\\\ ${lc}${envtype}:       ${ic}${WM}${reset}
EOF
