#!/bin/bash

case "$1" in
    -a) urxvtc -name aur-cli -e aur-cli ;;
    -b) urxvtc -name bashterm -e bash ;;
    -c) urxvtc -name cmus -e cmus ;;
    -d) urxvtc -name mpm -e mpm_test ;;
    -e) urxvtc -name mutt -e neomutt ;;
    -f) : ;;
    -g) urxvtc -name floaterm -geometry 60x14 -e g810_switch_profile ;;
    -h) urxvtc -name htop -e htop -u archangel -s Command ;;
    -i) urxvtc -name jnettop -e sudo jnettop -i enp21s0f4u2 ;;
    -j) urxvtc -name jnettop -e sudo jnettop -i enp8s0 ;;
    -k) : ;;
    -l) : ;;
    -m) urxvtc -name pulsemixer -e pulsemixer ;;
    -n) urxvtc -name ncmpcpp -e ncmpcpp -s clock --quiet ;;
    -o) : ;;
    -p) urxvtc -name pacman-cli -e pacman-cli ;;
    -q) : ;;
    -r) urxvtc -name newsboat -e newsboat ;;
    -s) urxvtc -name somabox -e somabox ;;
    -t) urxvtc -name top -e btop ;;
    -u) : ;;
    -v) urxvtc -name vim_script -geometry 160x40 -e vim_script ;;
    -w) : ;;
    -x) urxvtc -name ripper -e Xtreamripper ;;
    -y) urxvtc -name youtube-viewer -e youtube-viewer ;;
    -z) urxvtc -name mpm -geometry 80x34 -e mpm_test ;;
esac
