#!/bin/bash

case "$1" in
    -a) urxvtc -name aur-cli -e aur-cli ;;
    -b) urxvtc -name bashterm -e bash ;;
    -c) urxvtc -name cmus -e cmus ;;
    -d) urxvtc -name mpm -e mpm ;;
    -e) urxvtc -name mutt -e neomutt ;;
    -h) urxvtc -name htop -e htop -u archangel -s Command ;;
    -j) urxvtc -name jnettop -e sudo jnettop -i enp7s0 ;;
    -m) urxvtc -name pulsemixer -e pulsemixer ;;
    -n) urxvtc -name ncmpcpp -e ncmpcpp -s clock --quiet ;;
    -p) urxvtc -name pacman-cli -e pacman-cli ;;
    -r) urxvtc -name newsboat -e newsboat ;;
    -s) urxvtc -name vim_script -geometry 160x40 -e vim_script ;;
    -t) urxvtc -name termscp -e termscp ;;
    -x) urxvtc -name ripper -e xtreamripper ;;
    -y) urxvtc -name youtube-viewer -e youtube-viewer ;;
esac
