#!/bin/bash

# Most frequently edited configurations files are linked in "$confdir"
confdir="$HOME/.config/CONFIGS"

cd "$confdir" || exit 1

PS3="Enter a file number to Edit or Remove (^C to exit): "

# set the configs list using the 'find' command for symbolic links.
select link in $(find $confdir -type l | sort -d | sed 's,.*/,,'); do
    echo "[E]dit or [R]emove $link?:"
    read action
    case "$action" in
        E|e) $VISUAL "$link"
        ;;
        R|r) echo "Do you really want to REMOVE $link? [y/N]:"
            read del
            case $del in
                y|yes|Y) rm "$link"
                ;;
                n|no|N) echo "Deletion aborted"
                ;;
                *) echo "Unknown option...deletion aborted" && exit 1
                ;;
            esac
        ;;
    esac
    break
done
