#!/bin/bash

# SCRIPTDIR is part of the environment variables.

cd "$SCRIPTDIR" || exit 1

PS3="Enter a script number to Chmod, Edit, Remove, or Rename: "

[[ -n $(find . -maxdepth 1 -perm 644) ]] && {
    printf '%s\n' "THESE FILES ARE NOT EXECUTABLE:"
    find . -maxdepth 1 -perm 644 | sed 's/.\///'
    echo ""
}

# set the scripts list.
select file in $(find "$SCRIPTDIR" -maxdepth 1 -type f | sort -d | sed 's,.*/,,'); do
    echo ""
    read -rp '[C]hmod, [E]dit, [R]emove, [r]ename the chosen script or QUIT [q]: ' action
    case "$action" in
        C|c)    chmod u+x "$file"
                printf '%s\n' "$file is now executable."

        ;;
        E|e)    $VISUAL "$file"
        ;;
        R  )    printf '%s\n' "remove $file? [y/N]:"
                read -rsn 1 del
                case "$del" in
                    y|yes|Y) rm "$file" && printf '%s\n' "$file removed"
                    ;;
                    n|no|N) printf '%s\n' "Deletion aborted"
                    ;;
                    *) printf '%s\n' "Unknown option...deletion aborted" && exit 1
                    ;;
                esac
        ;;
        r  )    printf '%s\n' "rename $file:"
                read -r name
                mv "$file" "$name"
                printf '%s\n' "$file renamed to: $name"
        ;;
        q)  exit 0
        ;;
    esac
    break
done
