#!/usr/bin/env bash

# Volume control:
# Author: Barret E (2022) <archus@protonmail.com>
# https://github.com/archusXIV/dotfiles
# Simple script to control pulseaudio volume/microphone.
# For instance I use the polybar [module/pulseaudio-ipc] (sink) for sound output,
# and for my microphone (source) [module/mic-ipc]
# https://github.com/archusXIV/dotfiles/blob/main/polybar/active-modules-bar2.ini
# Usage: volume_control sink --{up,down,toggle} (preset is -/+5%)
#        volume_control source --{up,down,toggle} (preset is -/+1%)
#        volume_control sink --set "value" (onthefly_preset)
#        volume_control source --set "value" (onthefly_preset)
#        volume_control sink --balance "left_vol" "right_vol" (for balance control)

# change default presets values to your liking.
sink_preset=5
source_preset=1
onthefly_preset="$3"
default_source_vol="90%"

_polybarHook() {
    # Make sure we have polybar running
    ! pgrep -x polybar >/dev/null && return 1
    local type state module
    type=$1
    state=$2
    if [[ $type == "sink" ]]; then
        module="volume-ipc"
    else
        module="mic-ipc"
    fi
    pid=$(pgrep -f "$(wmctrl -m | awk '/Name/{print $2}')"-bar-2)
    polybar-msg -p "$pid" action "#${module}.hook.${state}" >/dev/null 2>&1
}

_notifyVolume() {
    notify-send "\
    Main pulseaudio volume $(pactl get-sink-volume @DEFAULT_SINK@ \
    | awk '{if(NR!=2) {print $5}}')\
    "
}

_keyboardMuteKey() {
    command -v g810-led >/dev/null 2>&1 || return 1
    # variables used if g810-led package is installed.
    local profile_rules profile_udev profiles_dir muteKeyOff muteKeyOn state key_state

    profile_rules="/etc/udev/rules.d/g810-led.rules"
    profile_udev=$(grep -e 'profile_' "$profile_rules" | sed 's,.*/,,;s/"//')
    profiles_dir="/etc/g810-led/profiles"
    muteKeyOff=$(awk '/^var color3/{print $NF}' "$profiles_dir"/"$profile_udev")
    muteKeyOn=$(awk '/^var color1/{print $NF}' "$profiles_dir"/"$profile_udev")
    state=$1
    key_state=

    [[ $state == "on" ]] && key_state="$muteKeyOn" || key_state="$muteKeyOff"

    if [[ -s "$XDG_RUNTIME_DIR"/scratchpad_hidden.list ]]; then
        sudo g815-led -k mute "$key_state"
        sudo g815-led -fx breathing logo fb4934 5
        [[ $state == "on" ]] && notify-send 'Volume muted'
    else
        sudo g815-led -k mute "$key_state"
        [[ $state == "on" ]] && notify-send 'Volume muted'
    fi
}

# Helper function to handle volume changes
_handleVolume() {
    local device action preset default_device left_vol right_vol

    device=$1    # sink or source
    action=$2    # up, down, toggle, set
    preset=$3    # volume change preset
    left_vol=$4  # left channel volume (for balance)
    right_vol=$5 # right channel volume (for balance)
    default_device="DEFAULT_${device^^}"

    __setVolume() { pactl set-"${device}"-volume "@${default_device}@" "$1"; }
    __setBalance() { pactl set-"${device}"-volume "@${default_device}@" "$1" "$2"; }
    __getVolume() { pactl get-"${device}"-mute "@${default_device}@"; }
    __toggleMute() { pactl set-"${device}"-mute "@${default_device}@" toggle; }

    case "$action" in
        balance)
            __setBalance "$left_vol%" "$right_vol%"
            [[ $device == sink ]] && _notifyVolume
            _polybarHook "${device}" 1
        ;;
        up)
            if __getVolume | grep -q "yes"; then
                __toggleMute
                [[ $device == "source" ]] && __setVolume "$default_source_vol"
                [[ $device == "sink" ]] && { _keyboardMuteKey off; _notifyVolume; }
                _polybarHook "${device}" 1
            else
                __setVolume "+${preset}%"
                [[ $device == "sink" ]] && { _keyboardMuteKey off; _notifyVolume; }
                _polybarHook "${device}" 1
            fi
        ;;
        down)
            __setVolume "-${preset}%"
            [[ $device == "sink" ]] && _notifyVolume
            _polybarHook "${device}" 1
        ;;
        toggle)
            if __getVolume | grep -q "yes"; then
                __toggleMute
                [[ $device == "source" ]] && __setVolume "$default_source_vol"
                [[ $device == "sink" ]] && { _keyboardMuteKey off; _notifyVolume; }
                _polybarHook "${device}" 1
            else
                __toggleMute
                [[ $device == "source" ]] && __setVolume "0%"
                [[ $device == "sink" ]] && _keyboardMuteKey on
                _polybarHook "${device}" 0
            fi
        ;;
        set)
            __setVolume "${onthefly_preset}%"; _notifyVolume
            _polybarHook "${device}" 1
        ;;
    esac
}

case "$1" in
    sink)
        case "$2" in
            --up|--down|--toggle)
                _handleVolume "sink" "${2#--}" "$sink_preset"
            ;;
            --balance)
                _handleVolume "sink" "balance" "set" "$3" "$4"
                _polybarHook "sink" 1
            ;;
            --set)
                _handleVolume "sink" "set" "$onthefly_preset"
            ;;
        esac
    ;;
    source)
        case "$2" in
            --up|--down|--toggle|--set)
                _handleVolume "source" "${2#--}" "$source_preset"
            ;;
            --balance)
                _handleVolume "source" "balance" "set" "$3" "$4"
                _polybarHook "source" 1
            ;;
        esac
    ;;
esac
