#!/bin/bash

systemctl --user stop Xsession.target

declare -A wm=(
    [dk]="dkcmd exit"
    [bspwm]="bspc quit"
    [i3]="i3-msg exit"
)

rm -f /tmp/dk__* 2>/dev/null
rm -f /tmp/{serverauth,polybar_mqueue}.*

for x in "${!wm[@]}"; do
    pidof "${x}" >/dev/null && "${wm[${x}]}"
done

pkill -9 -u "$USER"
