#!/bin/bash

_alarm() { mpv "$HOME"/Documents/mixkit-low-church-bell-calling-623.wav; }

_fithteen() {
    local hour min sec
    hour=00
    min=15
    sec=0

    while [ $hour -ge 0 ]; do
        while [ $min -ge 0 ]; do
            while [ $sec -ge 0 ]; do
                echo "Timer: $hour:$min:$sec" > "$XDG_CACHE_HOME"/timer.txt
                let "sec=sec-1"
                sleep 1s
                polybar-msg hook timer 2 >/dev/null 2>&1
            done
            sec=59
            let "min=min-1"
        done
        min=59
        let "hour=hour-1"
    done
    polybar-msg hook timer 1 >/dev/null 2>&1
    pulsemixer --set-volume 20
    _alarm &
}

_thirty() {
    local hour min sec
    hour=00
    min=30
    sec=0

    while [ $hour -ge 0 ]; do
        while [ $min -ge 0 ]; do
            while [ $sec -ge 0 ]; do
                echo "Timer: $hour:$min:$sec" > "$XDG_CACHE_HOME"/timer.txt
                let "sec=sec-1"
                sleep 1s
                polybar-msg hook timer 2 >/dev/null 2>&1
            done
            sec=59
            let "min=min-1"
        done
        min=59
        let "hour=hour-1"
    done
    polybar-msg hook timer 1 >/dev/null 2>&1
    pulsemixer --set-volume 20
    _alarm &
}

_fourty_five() {
    local hour min sec
    hour=00
    min=45
    sec=0

    while [ $hour -ge 0 ]; do
        while [ $min -ge 0 ]; do
            while [ $sec -ge 0 ]; do
                echo "Timer: $hour:$min:$sec" > "$XDG_CACHE_HOME"/timer.txt
                let "sec=sec-1"
                sleep 1s
                polybar-msg hook timer 2 >/dev/null 2>&1
            done
            sec=59
            let "min=min-1"
        done
        min=59
        let "hour=hour-1"
    done
    polybar-msg hook timer 1 >/dev/null 2>&1
    pulsemixer --set-volume 20
    _alarm &
}

_sixty() {
    local hour min sec
    hour=00
    min=60
    sec=0

    while [ $hour -ge 0 ]; do
        while [ $min -ge 0 ]; do
            while [ $sec -ge 0 ]; do
                echo "Timer: $hour:$min:$sec" > "$XDG_CACHE_HOME"/timer.txt
                let "sec=sec-1"
                sleep 1s
                polybar-msg hook timer 2 >/dev/null 2>&1
            done
            sec=59
            let "min=min-1"
        done
        min=59
        let "hour=hour-1"
    done
    polybar-msg hook timer 1 >/dev/null 2>&1
    pulsemixer --set-volume 20
    _alarm &
}

rc="$HOME/.config/dmenu/dmenurc"

# shellcheck source=/dev/null
[[ -f "$rc" ]] && . "$rc"

# shellcheck disable=SC2086
timer=$(printf "15m\\n30m\\n45m\\n1h" | dmenu $DMENU_OPTIONS -p "Set a timer:")

case "$timer" in
    15m ) _fithteen
    ;;
    30m ) _thirty
    ;;
    45m ) _fourty_five
    ;;
    1h  ) _sixty
    ;;
esac
