#!/bin/bash

rc="$HOME/.config/dmenu/dmenurc"

[ -f "$rc" ] && source "$rc"

_lite() {
    if [[ -n $(pidof lite-xl) ]]; then
        bspc desktop -f '^5' || i3-msg workspace 5
    fi
}

if [[ -n $(pidof lite-xl) ]]; then
    bspc monitor --focus $MONITOR1 || i3-msg --monitor $MONITOR1
fi

choice=$(printf "archwiki\\nconfig\\nfind\\nman\\ndmenu\\nmpd\\npass\\npower\\nscrot\\ntimer\\nvideo" \
        | dmenu -f -i $DMENU_OPTIONS -p "Select a script:")

[[ -z $choice ]] && _lite && exit

case "$choice" in
    archwiki) search_archwiki &
    ;;
    config) configurator &
    ;;
    find) dmenu-find &
    ;;
    man) man-display.sh &
    ;;
    dmenu) i3-dmenu-desktop &
    ;;
    mpd) mpd_command &
    ;;
    pass) pass_menu &
    ;;
    power) power-menu &
    ;;
    scrot) screenshooter &
    ;;
    timer) dmenu-timer &
    ;;
    video) openvideo &
    ;;
esac
