#!/bin/bash

# Terminate already polybar instances in case it's true.
if [[ -n $(pidof polybar) ]]; then
    killall -q polybar

    # Wait until the process has been shut down
    while pgrep -u $UID -x polybar >/dev/null; do
        sleep 1s
    done
fi

if [[ -n $(pidof bspwm) ]]; then
    polybar bspwm-bar-1 -q &
    sleep 0.5
    polybar bspwm-bar-2 -q &
    sleep 0.5
    polybar bspwm-bar-3 -q &
    notify-send 'Bars launched...'
elif [[ -n $(pidof i3) ]]; then
    polybar i3-bar-1 -q &
    sleep 0.5
    polybar i3-bar-2 -q &
    sleep 0.5
    polybar i3-bar-3 -q &
    notify-send 'Bars launched...'
else
    echo "no wm at all.....!" && exit 1
fi

