#!/usr/bin/env bash

if [[ -n $(pidof nvidia-persistenced) ]]; then
    xrandr --output DP-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
           --output HDMI-0 --mode 1920x1080 --pos 1920x0 --rotate normal \
           --output DVI-D-0 --mode 1920x1080 --pos 3840x0 --rotate normal
           nvidia-settings -l
else
    xrandr --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
           --output HDMI-1 --mode 1920x1080 --pos 1920x0 --rotate normal \
           --output DVI-D-1 --mode 1920x1080 --pos 3840x0 --rotate normal
fi
