#!/bin/sh

num="$(2:-5)"

if pgrep -x pulseaudio; then
    toggle() { pulsemixer --toggle-mute ; }
    mute() { pulsemixer --mute ; }
    up() { pulsemixer --change-volume +"$num" ; }
    down() { pulsemixer --change-volume -"$num" ; }
else
    toggle() { amixer sset Master toggle ; }
    mute() { amixer sset Master mute ; }
    up() { amixer sset Master "$num"%+ ; }
    down() { amixer sset Master "$num"- ; }
fi

case "$1" in
    toggle) toggle ;;
    mute) mute ;;
    up) up ;;
    down) down ;;
esac >/dev/null

