#!/bin/sh

# Gives a dmenu prompt to search the ArchWiki.
# Without input, will open https://wiki.archlinux.org/.
# URLs will be directly handed to the browser.
# Anything else, it search it.
browser=${BROWSER:-firefox}

pgrep -x dmenu && exit

rc="$HOME"/.config/dmenu/dmenurc

[ -f "$rc" ] && . "$rc"

choice=$(echo "" | dmenu -i $DMENU_OPTIONS -p "Search ArchWiki:") || exit 1

if [ "$choice" = ""  ]; then
    $browser "https://wiki.archlinux.org/"
else
    # Detect if url
    if [[ "$choice" =~ ^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$ ]]; then
        $browser "$choice"
    else
        $browser "https://wiki.archlinux.org/index.php?search=$choice"
    fi
fi
