#!/bin/bash

### APPS RULES & ASSIGNMENTS ###

_WindowRules() {
    # If reloading this file, remove all previous rules (added on the fly)
    # to prevent doubling up.
    bspc rule --remove "*"

    # add windows class names to this file if you want them to float.
    while read -r line; do
        _Rules "$line" state=floating focus=on center=on
    done < "$XDG_CONFIG_HOME"/bspwm/FloatingApps

    # [class:instance]="desktop number"
    declare -A WINRULES=(
        [URxvt:cmus]="1" [URxvt:ncmpcpp]="1"
        [URxvt:ripper]="1" [URxvt:youtube]="1"
        [feh]="2" [Zathura]="2"
        [URxvt:ranger]="3" [URxvt:sudoranger]="3"
        [code-oss]="4" [Geany]="4" [lite-xl]="4"
        [VirtualBox]="5" [mpv:gl]="5"
        [URxvt:htop]="6" [URxvt:jnettop]="6"
        [Chromium]="7" [firefox]="7"
        [file-roller]="8" [filezilla]="8" [Pcmanfm]="8"
        [obs]="9" [SimpleScreenRecorder]="9"
    )
    
    for w in "${!WINRULES[@]}"; do
        _Rules "$w" desktop=^"${WINRULES[${w}]}" follow=on
    done
    
    # Specials =========================== attributs =================#
    _Rules URxvt:liteterm       desktop=^4 follow=on state=floating rectangle=1553x462+2274+575
    _Rules Five-or-more         state=floating rectangle=434x488+2662+281
}
