#!/bin/bash

### APPS RULES & ASSIGNMENTS ###

_WindowRules() {
    # If refreshing bspwmrc, remove all previous rules
    # to prevent doubling up.
    bspc rule -r "*"

    # add windows class names to this list if you want them floating.
    local FloatingApps="$XDG_CONFIG_HOME/bspwm/FloatingApps"
    
    mapfile -t < <(cat "$FloatingApps")
    
    for item in "${MAPFILE[@]}"; do
        _Rules "$item" state=floating focus=on center=on
    done

    # Monitor 1
    _Rules firefox              desktop=^1 follow=on
    _Rules URxvt:mpm            desktop=^1 follow=on
    _Rules Pcmanfm              desktop=^2 follow=on
    _Rules File-roller          desktop=^2 follow=on
    _Rules Filezilla            desktop=^2 follow=on
    _Rules obs                  desktop=^3 follow=on
    _Rules SimpleScreenRecorder desktop=^3 follow=on
    _Rules feh                  desktop=^4 follow=on state=fullscreen
    _Rules VirtualBox           desktop=^4 follow=on
    _Rules Nitrogen             desktop=^4 follow=on
    _Rules Zathura              desktop=^4 follow=on
    _Rules qv4l2                desktop=^4 follow=on
    _Rules Mumble               desktop=^4 follow=on

    # Monitor 2
    _Rules Geany                desktop=^5 follow=on
    _Rules lite-xl              desktop=^5 follow=on
    _Rules mpv                  desktop=^6 follow=on
    _Rules URxvt:youtube        desktop=^6 follow=on
    _Rules qvidcap              desktop=^6 follow=on
    _Rules Five-or-more         desktop=^7 follow=on rectangle=434x488+2662+281
    _Rules Sol                  desktop=^7 follow=on

    # Monitor 3
    _Rules URxvt:ncmpcpp        desktop=^8 follow=on
    _Rules URxvt:cmus           desktop=^8 follow=on
    _Rules URxvt:ripper         desktop=^8 follow=on
    _Rules URxvt:htop           desktop=^9 follow=on
    _Rules URxvt:jnettop        desktop=^9 follow=on
    _Rules URxvt:newsboat       desktop=^9 follow=on
    _Rules URxvt:mutt           desktop=^9 follow=on
    _Rules URxvt:packagelist    desktop=^10 follow=on
    _Rules URxvt:ranger         desktop=^10 follow=on
    _Rules XTerm                desktop=^10 follow=on
}

