#!/bin/bash

# shellcheck disable=all
###### DK WINDOW MANAGER CONFIGURATION FILE version 2.3-1 ######
export DKSOCK="/tmp/$(command ls /tmp | awk '/dk__/{print $0}')"

# let's include our windows rules
. "$HOME"/.config/dk/_WindowsRules

_Has() { command -v "$1" >/dev/null; }

if _Has xrdb && [[ -e $HOME/.Xresources ]]; then
    blk=$(xrdb -query | awk '/color8:/{print $NF}')
    grn=$(xrdb -query | awk '/color2:/{print $NF}')
    red=$(xrdb -query | awk '/color1:/{print $NF}')
else
    blk='#222222'
    grn='#63b96c'
    red='#ee5555'
fi

# workspaces/gaps/padding/split ratio/layouts/borders settings
# -----------------------------------
dkcmd set numws=10

dkcmd set ws=_ apply layout=rtile master=1 stack=3 \
pad {l,r,t,b}=6 gap=5 msplit=0.67 ssplit=0.5

dkcmd set ws=1 layout=grid pad {l,r,t,b}=25 gap=50
dkcmd set ws=4 layout=tstack msplit=0.80

dkcmd set static_ws=true \
    ws=1 name='1:G' mon="$MONITOR1" \
    ws=2 name='2:R' mon="$MONITOR1" \
    ws=3 name='3:R' mon="$MONITOR1" \
    ws=4 name='4:W' mon="$MONITOR2" \
    ws=5 name='5:R' mon="$MONITOR2" \
    ws=6 name='6:R' mon="$MONITOR2" \
    ws=7 name='7:R' mon="$MONITOR3" \
    ws=8 name='8:R' mon="$MONITOR3" \
    ws=9 name='9:R' mon="$MONITOR3" \
    ws=10 name='10:R' mon="$MONITOR3"

dkcmd set {obey_motif,focus_open,tile_tohead}=true
dkcmd set {focus_{mouse,urgent},obey_motif,tile_hints,smart_{border,gap}}=false
dkcmd set win_{minwh,minxy}=50
dkcmd set mouse mod=super move=button1 resize=button2
dkcmd set border width=3 outer_width=1
dkcmd set border colour \
    {focus,outer_focus}="$grn" \
    {urgent,outer_urgent}="$red" \
    {unfocus,outer_unfocus}="$blk"

_WindowsRules

_Has polybar && polybar_start
_Has sxhkd && sxhkd_start
sleep 1
dkcmd status type=full num=1 | dkcmd -p > "$XDG_CONFIG_HOME"/dk/dk_status.log

exit 0
