#!/bin/bash

# Author: Barret E <archus@protonmail.com>
# github directory: https://github.com/archusXIV/wm_config
# Youtube channel: <https://www.youtube.com/@linuxinfrench9388>
#
# BE CAREFULL, this scripts will erase all the content of critical directories
# in your $HOME folder such as ~/.config & ~/.local and replace them with
# a simple customization to get ready to go and use an i3/bspwm desktops.
# It also provide other critical files such as shell configs (.bashrc,.zshrc)
# .Xresources, .Xmodmap, .xinitrc and systemd user services.
# So it is intended to be used on a very first desktop installation.
# USE IT AT YOUR OWN RISKS.

# Colors
nc=$'\e[0;m';
g=$'\e[1;32m';
r=$'\e[0;31m';
y=$'\e[93m';

_WmConfig() {
    
    # On first run, zsh will ask for configuration but we already have one.
    # We enter 0 to shut it's mouth and remove the new .zshrc it created.
    [[ -f ~/.zshrc ]] && rm ~/.zshrc
    [[ -d ~/.config ]] && rm -rf  ~/.config
    [[ -d ~/.local ]] && rm -rf  ~/.local

    git clone https://github.com/archusXIV/wm_config.git
    cd wm_config/ || exit 1
    
    local LNG WM KBD
    LNG=$(sed -n '1p' /etc/locale.conf)
    KBD=$(sed 's/KEYMAP=//;s/-.*//' /etc/vconsole.conf | sed -n '1p')
    
    __ExportLang() (
        if [[ $LNG = LANG="fr_FR.UTF-8" ]]; then
            echo 'export LANG="fr_FR.UTF-8"' \
            | tee -a .bash_profile >> .zshenv
        elif [[ $LNG = LANG="en_US.UTF-8" ]]; then
            echo 'export LANG="en_US.UTF-8"' \
            | tee -a .bash_profile >> .zshenv
        else
            printf '%s\n' " ${r}Your locales are not set.${nc}"
            sleep 2s
        fi
    )
    
    __CommonConf() (
        printf '%s\n' " ${y}Configuring $WM.${nc}"
        sleep 1s
        mv config .config && mv local .local
        chmod +x .local/bin/*
        echo "setxkbmap $KBD" >> .local/bin/autostart
        __ExportLang
        mv -f .local .. && mv -f .config ..
        
        if [[ -d ~/Pictures ]]; then
            mv -f wallpapers ~/Pictures/
        else
            mv -f wallpapers ~/Images/
        fi
        
        chmod +x .fehbg && chmod +x ~/.config/ranger/scope.sh
        mv -f .{bash_profile,bashrc,zshenv,fehbg,xinitrc,Xresources} ..
        echo "exec $WM" >> ~/.xinitrc
        cd ~ && rm -rf wm_config
    )
    
    clear
    
    if [[ -f /usr/share/xsessions/i3.desktop ]]; then
        WM="i3"
        __CommonConf
        printf '%s\n' " ${y}$WM configured, rebooting...${nc}"
        sleep 2s && reboot
    elif [[ -f /usr/share/xsessions/bspwm.desktop ]]; then
        WM="bspwm"
        __CommonConf
        chmod +x ~/.config/bspwm/bspwmrc
        printf '%s\n' " ${y}$WM configured, rebooting...${nc}"
        sleep 2s && reboot
    else
        printf '%s\n' " ${r}$WM is not installed.${nc}"
        sleep 3s
        exit 127
    fi
    
}

_Description() {
    
    clear
    setfont sun12x22
    cat << EOF
                #                                                       
               # #      #####   ####  #    # #      # #    # #    # #    # 
              #   #     #    # #    # #    # #      # ##   # #    #  #  #  
             #     #    #    # #      ###### #      # # #  # #    #   ##   
            #########   #####  #      #    # #      # #  # # #    #   ##   
           #         #  #   #  #    # #    # #      # #   ## #    #  #  #  
          #           # #    #  ####  #    # ###### # #    #  ####  #    #
    
                 i3/bspwm configurations for lazy dudes made easy!
    
    # French (ne jamais exécuter un script sans le lire auparavant)
    ${r}ATTENTION: lancez ce script uniquement sur un système fraichement installé!
    ${y}Ce script va installer la configuration de bspwm ou i3wm selon votre précédent
    choix dans la phase 'install_desktop'.
    Au redémarrage lancez startx et veuillez lire le fichier README.md ouvert dans geany.${nc}
    
    # English (never run a script without reading it first)
    ${r}BE CAREFULL: run this script only on a fresh installed system!
    ${y}This script will install the bspwm or i3wm configuration depending
    on your previous choice in the 'install_desktop' phase.
    On restart launch startx and please read the README.md file opened in geany.${nc}
    
EOF
    printf '%s\n'
    read -r -p "${g}"'    Press enter to launch the installation, ^C to quit: '"${nc}" config
    case "$config" in *) _WmConfig ;; esac
    
}

_Description
