-- mod-version:3
local syntax = require "core.syntax"

syntax.add {
  name = "Shell script",
  files = {
    "%.sh$", "%.bash$",
    PATHSEP .. "%.bashrc$", PATHSEP .. "%.bash_profile$", PATHSEP .. "%.profile$",
    "%.zsh$", "%.fish$",
    PATHSEP .. "APKBUILD$",
  },
  headers = "^#!.*bin.*sh\n",
  comment = "#",
  patterns = {
    -- $# is a bash special variable and the '#' shouldn't be interpreted
    -- as a comment.
    { pattern = "%$[%a_@*#][%w_]*",                type = "keyword2" },
    -- Comments
    { pattern = "#.*",                             type = "comment" },
    -- Strings
    { pattern = { '"', '"', '\\' },                type = "string" },
    { pattern = { "'", "'", '\\' },                type = "string2" },
    { pattern = { '`', '`', '\\' },                type = "string3" },
    -- Ignore numbers that start with dots or slashes
    { pattern = "%f[%w_%.%/]%d[%d%.]*%f[^%w_%.]",  type = "number" },
    -- Operators
    { pattern = "[!<>|&%[%]:=*]",                  type = "operator" },
    -- Match parameters
    { pattern = "%f[%S][%+%-][%w%-_:]+",           type = "function" },
    { pattern = "%f[%S][%+%-][%w%-_]+%f[=]",       type = "function" },
    -- Prevent parameters with assignments from been matched as variables
    { pattern = "%s%-%a[%w_%-]*%s+()%d[%d%.]+",    type = { "function", "number" } },
    { pattern = "%s%-%a[%w_%-]*%s+()%a[%a%-_:=]+", type = { "function", "symbol" } },
    -- Match variable assignments
    { pattern = "[_%a][%w_]+%f[%+=]",              type = "keyword2" },
    -- Match variable expansions
    { pattern = "%${.-}",                          type = "keyword2" },
    { pattern = "%$[%d%$%a_@*][%w_]*",             type = "keyword2" },
    -- Everything else
    { pattern = "[%a_][%w_]*",                     type = "symbol" },
    -- Functions
    { pattern = "[%a_%-][%w_%-]*[%s]*%f[(]",       type = "function" },
  },
  symbols = {
    ["alias"]     = "normal",
    ["awk"]       = "literal",
    ["break"]     = "keyword",
    ["case"]      = "keyword",
    ["cat"]       = "literal",
    ["clear"]     = "normal",
    ["continue"]  = "keyword",
    ["cp"]        = "literal",
    ["cut"]       = "literal",
    ["declare"]   = "keyword",
    ["disable"]   = "normal",
    ["disown"]    = "literal",
    ["do"]        = "keyword",
    ["done"]      = "keyword",
    ["echo"]      = "normal",
    ["elif"]      = "keyword",
    ["else"]      = "keyword",
    ["enable"]    = "normal",
    ["esac"]      = "keyword",
    ["eval"]      = "normal",
    ["exec"]      = "normal",
    ["export"]    = "normal",
    ["exit"]      = "normal",
    ["false"]     = "literal",
    ["fi"]        = "keyword",
    ["find"]      = "literal",
    ["for"]       = "keyword",
    ["function"]  = "operator",
    ["getopts"]   = "normal",
    ["grep"]      = "literal",
    ["hash"]      = "literal",
    ["head"]      = "literal",
    ["if"]        = "keyword",
    ["in"]        = "keyword",
    ["jq"]        = "literal",
    ["kill"]      = "literal",
    ["let"]       = "normal",
    ["ln"]        = "literal",
    ["local"]     = "keyword",
    ["ls"]        = "literal",
    ["mapfile"]   = "normal",
    ["mkdir"]     = "literal",
    ["mv"]        = "literal",
    ["nl"]        = "literal",
    ["paste"]     = "literal",
    ["pgrep"]     = "literal",
    ["pwd"]       = "literal",
    ["printf"]    = "literal",
    ["read"]      = "normal",
    ["readarray"] = "normal",
    ["return"]    = "keyword",
    ["rm"]        = "literal",
    ["rmdir"]     = "literal",
    ["sed"]       = "literal",
    ["select"]    = "keyword",
    ["set"]       = "keyword",
    ["shift"]     = "keyword",
    ["shopt"]     = "keyword",
    ["sleep"]     = "literal",
    ["sort"]      = "literal",
    ["source"]    = "normal",
    ["tail"]      = "literal",
    ["tee"]       = "literal",
    ["then"]      = "keyword",
    ["time"]      = "literal",
    ["tr"]        = "literal",
    ["trap"]      = "literal",
    ["true"]      = "literal",
    ["type"]      = "keyword",
    ["unalias"]   = "normal",
    ["uniq"]      = "literal",
    ["unset"]     = "normal",
    ["until"]     = "keyword",
    ["wait"]      = "keyword",
    ["wc"]        = "literal",
    ["while"]     = "keyword",
    ["xargs"]     = "literal",
  },
}
