-- mod-version:2 -- lite-xl 2.0
local syntax = require "core.syntax"

syntax.add {
  files = { "%.sh$" },
  headers = "^#!.*bin.*sh\n",
  comment = "#",
  patterns = {
    { pattern = "#.*\n",                  type = "comment"  },
    { pattern = [[\.]],                   type = "normal"   },
    { pattern = { '"', '"', '\\' },       type = "string"   },
    { pattern = { "'", "'", '\\' },       type = "string2"  },
    { pattern = { '`', '`', '\\' },       type = "string3"  },
    { pattern = "%f[%w_][%d%.]+%f[^%w_]", type = "number"   },
    { pattern = "[!<>|&%[%]=*]",          type = "operator" },
    { pattern = "%f[%S]%-[%w%-_]+",       type = "function" },
    { pattern = "${.-}",                  type = "keyword"  },
    { pattern = "$[%a_@*][%w_]*",         type = "keyword2" },
    { pattern = "[%a_][%w_]*",            type = "symbol"   },
  },
  symbols = {
    ["awk"]       = "number",
    ["break"]     = "literal",
    ["case"]      = "keyword",
    ["continue"]  = "literal",
    ["cut"]       = "number",
    ["declare"]   = "literal",
    ["disown"]    = "literal",
    ["do"]        = "keyword",
    ["done"]      = "keyword",
    ["echo"]      = "literal",
    ["elif"]      = "keyword",
    ["else"]      = "keyword",
    ["esac"]      = "keyword",
    ["eval"]      = "literal",
    ["exec"]      = "literal",
    ["export"]    = "literal",
    ["exit"]      = "literal",
    ["fi"]        = "keyword",
    ["for"]       = "keyword",
    ["function"]  = "keyword",
    ["getopts"]   = "literal",
    ["grep"]      = "number",
    ["hash"]      = "literal",
    ["if"]        = "keyword",
    ["in"]        = "keyword",
    ["let"]       = "literal",
    ["local"]     = "literal",
    ["mapfile"]   = "literal",
    ["pgrep"]     = "number",
    ["printf"]    = "literal",
    ["read"]      = "literal",
    ["readarray"] = "literal",
    ["return"]    = "literal",
    ["sed"]       = "number",
    ["select"]    = "keyword",
    ["set"]       = "literal",
    ["shopt"]     = "literal",
    ["sort"]      = "number",
    ["source"]    = "literal",
    ["then"]      = "keyword",
    ["time"]      = "keyword",
    ["tr"]        = "number",
    ["trap"]      = "literal",
    ["unalias"]   = "literal",
    ["uniq"]      = "number",
    ["unset"]     = "literal",
    ["until"]     = "keyword",
    ["wait"]      = "literal",
    ["while"]     = "keyword",
    ["true"]      = "literal",
    ["false"]     = "literal",
  },
}
