local style = require "core.style"
local common = require "core.common"

style.background = { common.color "#282a36" }
style.background2 = { common.color "#1E1F29" }
style.background3 = { common.color "#21222b" }
style.text = { common.color "#7b81a6" }
style.caret = { common.color "#f8f8f0" }
style.accent = { common.color "#8be9fd" }
style.dim = { common.color "#4f5873" }
style.divider = { common.color "#1f2029" }
style.selection = { common.color "#44475a" }
style.line_number = { common.color "#53576e" }
style.line_number2 = { common.color "#5ECD3F" }
style.line_highlight = { common.color "#313442" }
style.scrollbar = { common.color "#44475a" }
style.scrollbar2 = { common.color "#ff79c6" }
style.guide = { common.color "#1E1F29" } -- indentguide

style.syntax["normal"] = { common.color "#abb2bf" }
style.syntax["symbol"] = { common.color "#3060A6" }
style.syntax["comment"] = { common.color "#5c6370" }
style.syntax["keyword"] = { common.color "#98c875" }
style.syntax["keyword2"] = { common.color "#c98344" }
style.syntax["number"] = { common.color "#c59820" }
style.syntax["literal"] = { common.color "#b02f30" }
style.syntax["string"] = { common.color "#BF606F" }
style.syntax["operator"] = { common.color "#237986" }
style.syntax["function"] = { common.color "#a7cfa3" }
style.syntax["preprocessor"] = { common.color "#98c875" } -- thinking ahead
