#!/bin/bash

_killrecording() {
    killall -q ffmpeg
    rm -f "${pid}"
    _updateicon ""
    kill -KILL $(pgrep --full "record_chrono")
    # polybar clears icons (update with "nothing").
    polybar-msg action "#recording-ipc-1.hook.1" >/dev/null 2>&1
    sleep 0.5
    polybar-msg action "#chrono-ipc-1.hook.1" >/dev/null 2>&1
    sleep 0.5
    polybar-msg action "#recording-ipc-2.hook.1" >/dev/null 2>&1
    sleep 0.5
    polybar-msg action "#chrono-ipc-2.hook.1" >/dev/null 2>&1
    sleep 0.5
    polybar-msg action "#recording-ipc-3.hook.1" >/dev/null 2>&1
    sleep 0.5
    polybar-msg action "#chrono-ipc-3.hook.1" >/dev/null 2>&1

    # Uncomment this line if there is an audio delay.
    #[[ -n $(find "$HOME"/Documents/Videos/Xsessions -name "*.mkv") ]] && _fixdelay
    #[[ -n $(find "$HOME"/Documents/Videos/webcam -name "*.mkv") ]] && _fixdelay

	amixer set Capture,0 0%,0% mute nocap >/dev/null 2>&1
	polybar-msg action "#mic-ipc.hook.0" >/dev/null 2>&1
    exit
}
