#!/bin/bash

NAME=$(basename "$0")

_usage()
{
    cat <<- EOF

        AUTHORS: Luke Smith <luke@lukesmith.xyz> Barret E (2020) <archus@protonmail.com>

                From a Luke Smith original idea.
                https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/dmenurecord

        DESCRIPTION: $NAME - A dmenu prompt to record audio & video using ffmpeg.

                The video output format is set to mkv and audio to mp3.
                Polybar(s) will be automatically updated (we have 3 of them).
                If there is already a running instance, user will be prompted to end it.
                Be carefull to modify the directories paths if necessary.

        SYNOPSIS:
                $NAME [-h|-i|-k|-o|-s(1,2,3,a)|-v|-w] Without an argument dmenu will appear and prompt you.

        OPTIONS:
                -h
                        Shows this message.

                -i
                        Records only audio from default input, and the output format is mp3

                -k
                        Kills the running instance, updates polybar(s), and fixes the audio delay.

                -o
                        Records audio from the pulseaudio default output (speakers).
                        The format is 320k mp3.

                -s
                        This option brings you to the monitors choice.

                -s[1,2,3]
                        Screencast (audio+video) on monitor 1, monitor 2 or monitor 3,
                        the default resolution is 1920x1080. Feel free to change it.

                -sa
                        With this option you will screencast all monitors at once.

                -v
                        Records only video (no audio) on monitor 1.

                -w
                        Captures the webcam (audio included).

        See also ffmpeg(1) ffmpeg-all(1) ffmpeg-resampler(1) ffmpeg-codecs(1) ffmpeg-formats(1)

EOF
}

