#!/bin/bash

# does what we expect.
# Presets: ultrafast,superfast,veryfast,faster,fast,medium (defaults).
_webcam() {
    ffmpeg -f v4l2 \
    -video_size 640x480 \
    -framerate 60 \
    -i /dev/video0 \
    -f pulse \
    -i 1 \
    -c:a mp3 \
    -c:v h264 \
    -crf 14 \
    -preset veryfast \
    "$webcam"/webcam-"$date".mkv &
    echo $! > "$XDG_RUNTIME_DIR"/recordingpid
    _updateicon "  "
    polybar-msg hook recording-ipc-2 1 >/dev/null 2>&1
    record_chrono 2
}

