#!/bin/bash

# does what we expect.
# Presets: ultrafast,superfast,veryfast,faster,fast,medium (defaults).
_webcam() {
    amixer set Capture,0 75%,75% unmute cap >/dev/null 2>&1
    polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
    ffmpeg -f v4l2 \
    -video_size 640x480 \
    -framerate 60 \
    -i /dev/video0 \
    -f pulse \
    -i 1 \
    -c:a mp3 \
    -c:v h264 \
    -crf 14 \
    -preset fast \
    "$webcam"/webcam-"$date".mkv &
    echo $! > "${pid}"
    _updateicon "  "
    polybar-msg action "#recording-ipc-2.hook.0" >/dev/null 2>&1
    record_chrono 2
}
