#!/bin/bash

# all monitors at once.
_all_monitors() {
    amixer set Capture,0 85%,85% unmute cap >/dev/null 2>&1
    polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
    ffmpeg -f pulse \
    -i 1 \
    -c:a mp3 \
    -s "$(xdpyinfo | awk '/dimensions/{print $2}')" \
    -framerate 60 \
    -f x11grab \
    -i "$DISPLAY" \
    -c:v h264 \
    -qp 0 \
    -preset veryfast \
    "$Xsessions"/all_monitors_"$date".mkv &
    echo $! > "${pid}"
    _updateicon "  "
    polybar-msg action "#recording-ipc-2.hook.0" >/dev/null 2>&1
    record_chrono 2
}

# first monitor (on the left).
_screencast1() {
    amixer set Capture,0 85%,85% unmute cap >/dev/null 2>&1
    polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
    ffmpeg -f pulse \
    -i 1 \
    -c:a mp3 \
    -video_size 1920x1080 \
    -framerate 60 \
    -f x11grab \
    -i :0.0 \
    -c:v libx264 \
    -crf 14 \
    -preset veryfast \
    "$Xsessions"/screen1_"$date".mkv &
    echo $! > "${pid}"
    _updateicon "  "
    polybar-msg action "#recording-ipc-1.hook.0" >/dev/null 2>&1
    record_chrono 1
}

# second monitor (in the center).
_screencast2() {
    amixer set Capture,0 85%,85% unmute cap >/dev/null 2>&1
    polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
    ffmpeg -f pulse \
    -i 1 \
    -c:a mp3 \
    -video_size 1920x1080 \
    -framerate 60 \
    -f x11grab \
    -i :0.0+1920 \
    -c:v libx264 \
    -crf 14 \
    -preset veryfast \
    "$Xsessions"/screen2_"$date".mkv &
    echo $! > "${pid}"
    _updateicon "  "
    polybar-msg action "#recording-ipc-2.hook.0" >/dev/null 2>&1
    record_chrono 2
}

# third monitor (on the right).
_screencast3() {
    amixer set Capture,0 85%,85% unmute cap >/dev/null 2>&1
    polybar-msg action "#mic-ipc.hook.1" >/dev/null 2>&1
    ffmpeg -f pulse \
    -i 1 \
    -c:a mp3 \
    -video_size 1920x1080 \
    -framerate 60 \
    -f x11grab \
    -i :0.0+3840 \
    -c:v libx264 \
    -crf 14 \
    -preset veryfast \
    "$Xsessions"/screen3_"$date".mkv &
    echo $! > "${pid}"
    _updateicon "  "
    polybar-msg action "#recording-ipc-3.hook.0" >/dev/null 2>&1
    record_chrono 3
}

# first monitor (by default) and no audio.
_video() {
    ffmpeg -video_size 1920x1080 \
    -framerate 60 \
    -f x11grab \
    -i :0.0 \
    -c:v libx264 \
    -crf 14 \
    -preset veryfast \
    "$Xsessions"/video-"$date".mkv &
    echo $! > "${pid}"
    _updateicon ""
    polybar-msg action "#recording-ipc-1.hook.0" >/dev/null 2>&1
    record_chrono 1
}
