#!/bin/bash

if [[ -n $(pidof nvidia-persistenced) ]]; then
    bspc monitor DP-0 -d 1 2 3 4
    bspc monitor HDMI-0 -d 5 6 7
    bspc monitor DVI-D-0 -d 8 9 10
else
    bspc monitor DP-1 -d 1 2 3 4
    bspc monitor HDMI-1 -d 5 6 7
    bspc monitor DVI-D-1 -d 8 9 10
fi
