#!/bin/sh

# Manual tiling
# =============

# Spawn window on the newest receptacle or preselection and switch focus
# to it.  For presels priority is given to the current desktop.
_bspc_query() {
    bspc query -N -n "$@"
}

recept="$(_bspc_query 'any.leaf.!window')"
presel="$(_bspc_query 'newest.!automatic')"

# Receptacles will not switch focus to the present desktop, whereas
# preselection will.  This way we can develop different workflows (e.g.
# create 3 recept in one desktop, launch 3 GUIs that take time to load,
# switch to another desktop and continue working, until you decide to go
# back to the GUIs).  This has no effect when all actions occur within
# the focused desktop.

if [ -n "$recept" ]; then
    target="$recept"
    attention="off"
elif [ -n "$presel" ]; then
    target="$presel"
fi

echo "node=${target:-focused}"
echo "follow=${attention:-on}"
