#!/bin/bash

# changing workspaces layouts
# and update the polybar layout module.

layout=$(bspc query -T -d | awk -F, '
    {gsub(/["]/,""); sub("userLayout:",""); print $4; exit}
')

_ToggleMonocle() {
    if [[ $layout = monocle ]]; then
        bspc desktop -l tiled
        bspc node --focus last.local
    elif [[ $layout = tiled ]]; then
        bspc desktop -l monocle
    fi
}

case "$1" in
    -a )
        bspc config automatic_scheme alternate
    ;;
    -l )
        bspc config automatic_scheme longest_side
    ;;
    -m )
        _ToggleMonocle
    ;;
    -s )
        bspc config automatic_scheme spiral
    ;;
esac

