#!/bin/bash
## This is a part of main script: mpv-menu.

_EditMpvConf() {
    
    _CheckEditor
    $VISUAL "$XDG_CONFIG_HOME"/mpv/mpv.conf \
    || $EDITOR "$XDG_CONFIG_HOME"/mpv/mpv.conf
    echo " ${green}mpv.conf saved.${nocolor}"
    sleep 2s
    clear
    _Menu
    
}

