#!/bin/bash
## This is a part of main script: mpv-menu.

_EditPlaylist() {

    _CheckEditor
    cd "$playlists_dir"

    PS3=${green}' Choose a playlist to edit: '${nocolor}

    select list in $(find . -name "*.m3u" -o -name "*.m3u_origin" \
        | sort -d | sed 's,.*/,,'); do
        echo ""
        $VISUAL "$list" || $EDITOR "$list"
        echo " ${green}$list saved${nocolor}"
        sleep 2s
        break
    done
    _Menu
    
}

