#!/bin/bash
## This is a part of main script: mpv-menu.

_GetCompleted() {
    
    echo " ${green}Downloads are completed, do you want to keep main playlist? [N/y]: ${nocolor}"
    read -rsn 1
    case "$REPLY" in
        N|n)    rm "$QUEUE"_origin && _Menu ;;
        *  )    mv -f "$QUEUE"_origin "$QUEUE" && _CheckQueue ;;
    esac
    
}

