#!/bin/bash
## This is a part of main script: mpv-menu.

_GetQualityCodes() {
    # we want to play the best quality first...
    case "$1" in
        # -q for default.m3u, -l for (play)list
        -q  )   mapfile -t qualitycode < <(cat "$QUEUE" | sed '/#EXTM3U/d')
        
                for line in "${qualitycode[@]}"; {
                    youtube-dl -F $line > "$YTOP"
                    if grep -q '^137' "$YTOP"; then
                        echo $line >> "$HIGH"
                    elif grep -q '^22' "$YTOP"; then
                        echo $line >> "$MEDIUM"
                    elif grep -q '^135' "$YTOP"; then
                        echo $line >> "$LOW"
                    else
                        echo $line >> "$ELSE"
                    fi
                }
                
                sed -i -n \
                'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P' \
                "$HIGH" "$MEDIUM" "$LOW" >/dev/null 2>&1
        ;;
        -l  )   mapfile -t qualitycode < <(cat "$list" | sed '/#EXTM3U/d')
        
                for line in "${qualitycode[@]}"; {
                    youtube-dl -F $line > "$YTOP"
                    if grep -q '^137' "$YTOP"; then
                        echo $line >> "$HIGH"
                    elif grep -q '^22' "$YTOP"; then
                        echo $line >> "$MEDIUM"
                    elif grep -q '^135' "$YTOP"; then
                        echo $line >> "$LOW"
                    else
                        echo $line >> "$ELSE"
                    fi
                }
                
                sed -i -n \
                'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P' \
                "$HIGH" "$MEDIUM" "$LOW" >/dev/null 2>&1
        ;;
    esac
    
}

