#!/bin/bash
## This is a part of main script: mpv-menu.

_GetAudio() {

    cd "$audios_dir"
    cp -f "$QUEUE" "$QUEUE"_origin

    _CheckCode -q

    for url in $(grep '^https' "$QUEUE"); do

        if (( $(grep "" -c "$QUEUE") < 3 )); then
            echo ""
            echo " ${green}There is $(_GetLinesQueue) audio file left to download.${nocolor}"
        else
            echo ""
            echo " ${green}There are $(_GetLinesQueue) audio files left to download.${nocolor}"
        fi

        youtube-dl -F "$url" | sed -n '/audio only/p'
        echo ""
        echo " ${green}Choose a format code: ${nocolor}"
        read -r code
        clear
        echo -e " ${green}Please be patient while downloading \n ${red}$(_GetMediaTitle)...${nocolor}"
        sleep 2s
        youtube-dl -f "$code" --progress "$url"
        sed -i '2d' "$QUEUE"
        clear

    done

    echo -e " ${green}Done\n${nocolor}"

    if [[ -n $(find . -iname "*.webm") ]]; then
        
        echo " ${green}Please be patient while ffmpeg is working...${nocolor}"
        find . -iname "*.webm" -exec \
        bash -c 'FILE="$1"; \
        ffmpeg -i "${FILE}" \
        -vn -ab 320k -ar 48000 \
        -y "${FILE%.webm}.mp3";' _ '{}' \; 2>"$FFOP"

        echo " ${green}Done${nocolor}"
        sleep 2s
        rm ./*.webm
        _CleanTmpDir
        _GetIncompleted
    
    else
        _CleanTmpDir
        _GetIncompleted
    fi

}

