#!/bin/bash
## This is a part of main script: mpv-menu.

_GetVideo() {

    cd "$videos_dir"
    cp -f "$QUEUE" "$QUEUE"_origin

    _CheckCode -q

    for url in $(grep '^https' "$QUEUE"); do

        if (( $(grep "" -c "$QUEUE") < 3 )); then
            echo ""
            echo " ${green}There is $(_GetLinesQueue) video file left to download.${nocolor}"
        else
            echo ""
            echo " ${green}There are $(_GetLinesQueue) video files left to download.${nocolor}"
        fi

        youtube-dl -F "$url" | sed '/^sb/d'
        echo ""
        echo -e " ${green}Choose a format code. \n eg: 137+251 for merging, hls-1080p, 22 for single:${nocolor}"
        # We redirect the format code in a text file,
        # because 'grep' can't act within a variable ($code).
        read -r code
        sleep 0.5
        clear
        
        if [[ "$code" =~ '+' ]]; then
            echo " ${green}Please be patient while downloading and merging formats for:"
            echo " ${red}$(_GetMediaTitle).${nocolor}"
            youtube-dl -f "$code" --merge-output-format mp4 --progress "$url"
        else
            echo " ${green}Please be patient while downloading:"
            echo " ${red}$(_GetMediaTitle).${nocolor}"
            youtube-dl -f "$code" --progress "$url"
        fi

        sed -i '2d' "$QUEUE"
        clear

    done

    echo -e " ${green}Done.\n${nocolor}"
    sleep 2s
    _GetIncompleted

}

