#!/bin/bash
## This is a part of main script: mpv-menu.

_LoadPlaylist() {

    cd "$playlists_dir"

    PS3=""
    echo -e " ${green}Select a playlist to load (Press 'q' to quit mpv):\n${nocolor}"
    select list in $(find . -name "*.m3u" | sort -d | sed 's,.*/,,'); do

        if ! grep -q -e '^https' "$list"; then
            echo " ${red}$list is empty...${nocolor}"
            sleep 3s
            break
        fi

        # $list may also contain a {playlist url}, so let's extract videos from,
        # remove {playlist url} and grab videos' titles.(in the second while loop).
        if [[ $(grep -e 'playlist?list=' "$list") ]]; then
            echo ""
            echo -e " ${green}Checking youtube playlist availability...please wait.${nocolor}\n"
            [[ -f $URLS_INFO ]] && rm "$URLS_INFO"

            mapfile -t listinfo < <(cat "$list" | sed '/#EXTM3U/d')
            
            for line in "${listinfo[@]}"; {
                youtube-dl -j $line \
                | jq '(.webpage_url)' \
                | cat | sed 's/"//g' >> "$URLS_INFO"
            }

            cat "$URLS_INFO" >> "$list"

            # Cleaning $list...
            sed -i '/playlist/d' "$list"
            sed -i -n 'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P' "$list"
            _CheckCode -l
        else
            cat "$list" | sed '/#EXTM3U/d' > "$URLS_INFO"
        fi

        echo -e " ${green}Getting videos titles...please wait.${nocolor}\n"
        
        [[ -f $COMPLETE_INFO ]] && rm "$COMPLETE_INFO"

        mapfile -t videotitle < <(cat "$list" | sed '/#EXTM3U/d')
        
        for line in "${videotitle[@]}"; {
            youtube-dl -j $line \
            | jq '(.title)' >> "$COMPLETE_INFO"
        }
        
        [[ -n $(uniq -d "$COMPLETE_INFO") ]] && {
            echo " ${red}Removing double entries...${nocolor}"
            sleep 2s
            sed -i -n \
            'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P' \
            "$COMPLETE_INFO"
        }

        cat -n "$COMPLETE_INFO"

        echo ""
        echo -e " ${green}Just load [l] download audio [a] or download video [v] \n (Press '^C' to quit youtube-dl):${nocolor} "
        read -rsn 1 letter
        
        case "$letter" in
            a)  _DownloadAudio ;;
            l)  echo ""
                read -rsn 1 -p  ${green}' Load audio only [a] or video [v] ?: '${nocolor} load
                clear
                case "$load" in
                    a)  _CheckCode -l && mpv --no-video "$list" ;;
                    v)  _GetQualityCodes -l &
                        _CheckCode -l && _LoadVideo ;;
                    *)  echo " ${red} Wrong option! Wait and try again...${nocolor}"
                        sleep 3s ;;
                esac

                _CleanTmpDir
                clear
                _Menu ;;
            v)  _DownloadVideo ;;
            *)  echo " ${red} Wrong option! Wait and try again...${nocolor}"
                sleep 3s ;;
        esac

    done

    clear
    _Menu

}

