#!/bin/bash
## This is a part of main script: mpv-menu.

_LoadAudio() {
    
    clear
    echo ""
    echo "${red}Tip: You may want put this in your mpv.conf:"
    printf '%s\n' "term-playing-msg='Tiltle: \${media-title}'"
    echo "Otherwise press I for more infos${nocolor}"
    echo ""
    
    case "$1" in
        -q) mpv --input-ipc-server=/tmp/mpvsocket \
            --no-video "$QUEUE"
        ;;
        -l) mpv --input-ipc-server=/tmp/mpvsocket \
            --no-video "$list"
        ;;
    esac
    
    _CleanTmpDir
    _Menu
    
}
