#!/bin/bash
## This is a part of main script: mpv-menu.

_LoadLocal() {

    local AUDIOS="$HOME/Documents/Music/" VIDEOS="$HOME/Documents/Videos/"
    
    read -rsn 1 -p ${green}' Do you want to load [a]udio or [v]ideo ?: '${nocolor} choice 
    case "$choice" in
        a)  echo ""
            echo -e " ${green}What would you like to load, a directory [d] or file(s) [f] ?: ${nocolor}\n"
            read -rsn 1 audio
    
            case "$audio" in
                d)  PS3=" Select a directory to queue in mpv: "
                    select dir in $(find "$AUDIOS" -maxdepth 1 | sed 's,.*/,,'); do
                        if [[ $(find "$AUDIOS"/"$dir" -type d -empty) ]]; then
                            echo " ${red}$dir is empty. Wait and try again...${nocolor}"
                            sleep 2s
                            break
                        else
                            # checking for content in linked directories.
                            if [[ -z $(command ls "$AUDIOS"/"$dir") ]]; then
                                echo " ${red}This symlink points to an empty directory!"
                                echo " Wait and try again...${nocolor}"
                                sleep 3s
                                break
                            fi
                            echo ""
                            mpv "$AUDIOS"/"$dir"/*
                            break
                        fi
                    done
                    _Menu ;;
                f)  ranger "$AUDIOS"; _Menu ;;
                *)  echo " ${red} Wrong option! Wait and try again...${nocolor}"
                sleep 3s ;;
            esac
            ;;
        v)  echo ""
            echo -e " ${green}What would you like to load, a directory [d] or file(s) [f] ?: ${nocolor}\n"
            read -rsn 1 video
            case "$video" in
                d)  PS3=" Select a directory to queue in mpv: "
                    select dir in $(find "$VIDEOS" -maxdepth 1 | sed 's,.*/,,'); do
                        if [[ $(find "$VIDEOS"/"$dir" -type d -empty) ]]; then
                            echo " ${red}$dir is empty. Wait and try again...${nocolor}"
                            sleep 2s
                            break
                        else
                            if [[ -z $(command ls "$VIDEOS"/"$dir") ]]; then
                                echo " ${red}This symlink points to an empty directory!"
                                echo " Wait and try again...${nocolor}"
                                sleep 3s
                                break
                            fi
                            echo ""
                            mpv "$VIDEOS"/"$dir"/*
                            break
                        fi
                    done
                    _Menu ;;
                f)  ranger "$VIDEOS"; _Menu ;;
                *)  echo " ${red} Wrong option! Wait and try again...${nocolor}"
                sleep 3s ;;
            esac
        ;;
    esac

}

