#!/bin/bash
## This is a part of main script: mpv-menu.

_LoadVideo() {

    clear
    echo ""
    
    [[ -f $HIGH ]] && mpv --ytdl-format=137+251 "$HIGH"
    [[ -f $MEDIUM ]] && mpv --ytdl-format=22 "$MEDIUM"
    [[ -f $LOW ]] && mpv "$LOW" || [[ -f $ELSE ]] && mpv "$ELSE"

    _CleanTmpDir
    _CheckQueue

}

