#!/bin/bash
## This is a part of main script: mpv-menu.

_Menu() {

    clear
    while [[ -e $QUEUE ]]; do
        clear
        echo ""
        echo -e "                                                ${red}::MPV-MENU OPTIONS::${nocolor} "
        echo -e "                            ┌─────────────────────────────────────────────────────────────┐"
        echo -e "                            │   1) Create a video playlist    6) View default playlist    │"
        echo -e "                            │   2) Create an audio playlist   7) Clear default playlist   │"
        echo -e "                            │   3) Save/Remove playlist       8) Edit a playlist          │"
        echo -e "                            │   4) Load a playlist            9) Edit mpv.conf/Usage      │"
        echo -e "                            │   5) Load local dir/files       0) Exit                     │"
        echo -e "                            └─────────────────────────────────────────────────────────────┘"
        echo -e "                                                   ${green}Select an item${nocolor}"
        echo ""
        read -rsn 1 action
        case "$action" in
            1)  _CopyVideo
                echo "" ;;
            2)  _CopyAudio
                echo "" ;;
            3)  _SaveRemove
                echo "" ;;
            4)  _LoadPlaylist
                echo "" ;;
            5)  _LoadLocal
                echo "" ;;
            6)  _ViewUrlInfo
                echo "" ;;
            7)  _DeleteUrl
                echo "" ;;
            8)  _EditPlaylist
                echo "" ;;
            9)  _EditMpvConf
                echo "" ;;
            0)  exit 0 ;;
            *)  echo -e " ${red}Wrong option!\n Wait and try again...${nocolor}"
                sleep 2s
                clear ;;
        esac
    done

}

