#!/bin/bash
## This is a part of main script: mpv-menu.

_SaveRemove() {

    cd "$playlists_dir"
    clear
    read -rsn 1 -p 'Save [s] or Remove [r] a playlist?: ' opt
    echo ""

    case "$opt" in
        s)  echo -e " ${green}Available playlists:\n${nocolor}"
            find . -name "*.m3u" -o -name "*.m3u_origin" | sort -d | sed 's,.*/,,'
            echo ""
            echo -e " ${green}Save playlist as:\n${nocolor}"
            read -r list
            
            list="$list.m3u"
            if [[ $(find . -name "${list}") ]]; then
                echo -e " ${red}This playlist already exists!\n Overwrite $list? [y/N]:${nocolor}"
                read -r overwrite
                
                case "$overwrite" in
                    y|Y)    cp -f "$QUEUE" "$list"
                            echo " ${green}$list saved ${nocolor}"
                            sleep 3s
                            _CheckQueue ;;
                    N|n)    _CheckQueue ;;
                    *  )    _CheckQueue ;;
                esac
                
            else
                cp "$QUEUE" "$list"
                echo " ${green}$list saved ${nocolor}"
                sleep 2s
                _CheckQueue
            fi ;;
        r)  PS3=""
            echo -e " ${green}Which playlist do you want to remove? \n${nocolor}"
            
            select list in $(find . -name "*.m3u" -o -name "*.m3u_origin" | sort -d | sed 's,.*/,,'); do
                echo ""
                echo " ${red}Are you sure you want to remove $list? [y/N]:${nocolor}"
                read -r del
                
                case "$del" in
                    y|Y)    rm "$list"
                            echo " ${red}$list removed ${nocolor}"
                            sleep 3s
                            _Menu ;;
                    N|n)    _Menu ;;
                    *  )    echo " ${red} Wrong option! Wait and try again...${nocolor}"
                            sleep 3s
                            _Menu ;;
                esac
                
            done ;;
            
        *)  echo " ${red} Wrong option! Wait and try again...${nocolor}"
            sleep 3s
            _Menu ;;
    esac

}

