#!/bin/bash
## This is a part of main script: mpv-menu.

_save_remove() {

    cd "$playlists_dir"

    read -rsn 1 -p 'Save [s] or Remove [r] a playlist?: ' opt
    echo ""
    case "$opt" in
        s)  echo -e " ${green}Available playlists:\n${nocolor}"
            find . -name "*.m3u" -o -name "*.m3u_origin" | sort -d | sed 's,.*/,,'
            echo ""
            echo -e " ${green}Save playlist as:\n${nocolor}"
            read -r list
            list="$list.m3u"
            if [[ $(find . -name "${list}") ]]; then
                echo -e " ${red}This playlist already exists!\n Overwrite $list? [y/N]:${nocolor}"
                read -r overwrite
                case "$overwrite" in
                    y|Y)    cp -f "$queue" "$list"
                            echo " ${green}$list saved ${nocolor}"
                            sleep 3s
                            _check_queue ;;
                    N|n)    _check_queue ;;
                    *  )    _check_queue ;;
                esac
            else
                cp "$queue" "$list"
                echo " ${green}$list saved ${nocolor}"
                sleep 2s
                _check_queue
            fi ;;
        r)  PS3=""
            echo -e " ${green}Which playlist do you want to remove? \n${nocolor}"
            select list in $(find . -name "*.m3u" -o -name "*.m3u_origin" | sort -d | sed 's,.*/,,'); do
                echo ""
                echo " ${red}Are you sure you want to remove $list? [y/N]:${nocolor}"
                read -r del
                case "$del" in
                    y|Y)    rm "$list"
                            echo " ${red}$list removed ${nocolor}"
                            sleep 3s
                            _menu ;;
                    N|n)    _menu ;;
                    *  )    echo " ${red} Wrong option! Wait and try again...${nocolor}"
                            sleep 3s
                            _menu ;;
                esac
            done ;;
        *)  echo " ${red} Wrong option! Wait and try again...${nocolor}"
            sleep 3s
            _menu ;;
    esac

}

_delete_url() {
    if (( $(grep "" -c "$queue") < 2 )); then
        echo " ${green}Nothing to do here, main list is empty...${nocolor}"
        sleep 3s
        _menu
    else
        echo ""
        sed -i '/https/d' "$queue"
        echo " ${red}All urls removed ${nocolor}"
        sleep 3s
        _menu
    fi
}
