#!/bin/bash
## This is a part of main script: mpv-menu.

_get_audio() {

    cd "$audios_dir"

    for url in $(grep 'https' "$queue"); do

        if (( $(sed '/#EXTM3U/d' "$queue" | wc -l) < 2 )); then
            echo ""
            echo " ${green}There is" "$(sed '/#EXTM3U/d' "$queue" | wc -l)" "audio file left to download.${nocolor}"
        else
            echo ""
            echo " ${green}There are" "$(sed '/#EXTM3U/d' "$queue" | wc -l)" "audio files left to download.${nocolor}"
        fi

        youtube-dl -F "$url" | grep -e 'audio only' | sed 's/audio only      //'
        echo ""
        echo " ${green}Choose a format code: ${nocolor}"
        read -r code
        
        local getaudiotitle
        getaudiotitle=$(youtube-dl -j "$url" | jq '(.webpage_url, .title)' | tac | sed -n '1p')
        echo " ${green}Please be patient while downloading ${red}$getaudiotitle...${nocolor}"
        sleep 2s
        
        youtube-dl -f "$code" "$url" > "$ytop"
        sed -i '2d' "$queue"
        clear

    done

    echo -e " ${green}Done\n${nocolor}"

    if [[ -n $(find . -iname "*.webm") ]]; then
        echo " ${green}Please be patient while ffmpeg is working...${nocolor}"
        find . -iname "*.webm" -exec \
        bash -c 'FILE="$1"; \
        ffmpeg -i "${FILE}" \
        -vn -ab 320k -ar 48000 \
        -y "${FILE%.webm}.mp3";' _ '{}' \; 2>"$ffop"

        echo " ${green}Done${nocolor}"
        sleep 2s
        rm ./*.webm
        rm "$ffop" "$ytop"
        _menu
    else
        rm "$ytop"
        _menu
    fi

}

_get_video() {

    cd "$videos_dir"

    local webm
    webm="$(find . -name '*.webm' | sed 's,.*/,,')"

    for url in $(grep 'https' "$queue"); do

        youtube-dl -F "$url"
        echo ""
        echo " ${green}Choose a format code: ${nocolor}"
        read -r code
        echo "$code" > "$ytop"
        sleep 0.5
        
        local getvideotiltle
        getvideotitle=$(youtube-dl -j "$url" | jq '(.webpage_url, .title)' | tac | sed -n '1p')
        echo " ${green}Please be patient while downloading ${red}$getvideotitle...${nocolor}"
        sleep 2s
        
        if (( $(sed '/#EXTM3U/d' "$queue" | wc -l) < 2 )); then
            echo ""
            echo " ${green}There is" "$(sed '/#EXTM3U/d' "$queue" | wc -l)" "video file left to download.${nocolor}"
        else
            echo ""
            echo " ${green}There are" "$(sed '/#EXTM3U/d' "$queue" | wc -l)" "video files left to download.${nocolor}"
        fi

        if [[ $(grep -e '+' "$ytop") ]]; then
            youtube-dl -f "$code" --merge-output-format mp4 "$url" > "$ytop"
        else
            youtube-dl -f "$code" "$url" > "$ytop"
        fi
        
        sed -i '2d' "$queue"
        clear

    done

    echo -e " ${green}Done.\n${nocolor}"

    if [[ -n ${webm} ]]; then
        echo " ${green}Please be patient while ffmpeg is working...${nocolor}"
        ffmpeg -i "$webm" "$webm".mp4 2>$ffop
        echo " ${green}All done${nocolor}"
        sleep 2s
        rm ./*.webm
        rm "$ffop" "$ytop"
        _menu
    else
        rm "$ytop"
        _menu
    fi

}
