#!/bin/bash
## This is a part of main script: mpv-menu.

_edit_playlist() {

    _check_editor

    cd "$playlists_dir"
    PS3=${green}' Choose a playlist to edit: '${nocolor}
    echo -en "\nAvailable playlists\n\n"
    select list in $(find . -name "*.m3u" -o -name "*.m3u_origin" \
        | sort -d | sed 's,.*/,,'); do
        echo ""
        $VISUAL "$list"
        echo " ${green}$list saved${nocolor}"
        sleep 2s
        break
    done
    _menu
}

_edit_mpv-conf() {
    _check_editor
    $VISUAL "$XDG_CONFIG_HOME"/mpv/mpv.conf
    echo " ${green}mpv.conf saved.${nocolor}"
    sleep 2s
    clear
    _menu
}
