#!/bin/bash
## This is a part of main script: mpv-menu.

_save_remove() {

    cd "$playlists_dir"

    read -rp 'Save [s] or Remove [r] a playlist?: ' opt
    echo ""
    case $opt in
        s)  echo "Playlists directory content:"
            echo ""
            find . -name "*.m3u" | sort -d | sed 's,.*/,,'
            echo ""
            echo "Save playlist as:"
            read list
            if [[ -f "$list" ]]; then
                echo ""
                echo " ${red}This playlist already exists!${nocolor}"
                echo " ${green}Overwrite $list? [y/N]:${nocolor}"
                read overwrite
                case $overwrite in
                    y)  cp -f "$queue" "$list"
                        echo " ${green}$list saved ${nocolor}"
                        sleep 2s
                        _check_queue
                    ;;
                    N)  _check_queue
                    ;;
                    *)  _check_queue
                    ;;
                esac
            else
                cp "$queue" "$list"
                echo " ${green}$list saved ${nocolor}"
                sleep 2s
                _check_queue
            fi
        ;;
        r)  select list in $(find . -name "*.m3u" | sort -d | sed 's,.*/,,'); do
                echo ""
                echo " ${red}Are you sure you want to remove $list? [y/N]:${nocolor}"
                read -r del
                case $del in
                    y)  rm "$list"
                        echo " ${red}$list removed ${nocolor}"
                        sleep 2s
                        _menu
                    ;;
                    N)  _menu
                    ;;
                    *)  echo -e " ${red} Wrong option! Wait and try again...${nocolor}"
                        sleep 3s
                        _menu
                    ;;
                esac
            done
        ;;
        *)  echo -e " ${red} Wrong option! Wait and try again...${nocolor}"
            sleep 3s
            _menu
        ;;
    esac

}

_delete_url() {
    [[ -z $(sed -n '2p' "$queue") ]] \
    && echo " ${green}Nothing to do here, main list is empty...${nocolor}" \
    && sleep 2s \
    && _menu || {
        sed -i /https/d "$queue" \
        && echo " ${red}All urls removed ${nocolor}" \
        && sleep 2s \
        && _menu
    }
}

