#!/bin/bash

##    Author: Barret E (2020-21) <archus@protonmail.com>
##    https://github.com/archusXIV/dotfiles
##    Dependencies: ffmpeg, jq,  mpv, ranger, youtube-dl.
##
##    Youtube-dl is for now kind of unmaintained so install and make a symlink with
##    https://github.com/yt-dlp/yt-dlp/releases
##    ln -s /usr/bin/yt-dlp ~/.local/bin/youtube-dl (if ~/.local/bin is in your $PATH)
##
##    This script rips video urls from Youtube and so on.
##    In our case we use ".m3u" files to store urls in and then be able
##    to watch from the site itself or download videos or just the audio.
##    We can save, remove or edit playlists, mpv.conf.
##    It is recommanded to disable mpv cache for better results on direct streaming,
##    or find a better cache parameter.

## prompts & messages colors
nocolor=$'\e[0m';
red=$'\e[0;31m';
green=$'\e[0;32m';

## directories & files
main_dir="$HOME/Documents/mpv-menu"
playlists_dir="$main_dir/playlists"
audios_dir="$main_dir/audios"
videos_dir="$main_dir/videos"
tmp_dir="$main_dir/tmp"

QUEUE="$playlists_dir/default.m3u"
YTOP="$tmp_dir/youtube-dl_output.txt"
FFOP="$tmp_dir/ffmpeg_output.txt"
COMPLETE_INFO="$tmp_dir/view_urls_info.txt"
URLS_INFO="$tmp_dir/urls.txt"
HIGH="$tmp_dir/quality_hight.m3u"
MEDIUM="$tmp_dir/quality_medium.m3u"
LOW="$tmp_dir/quality_low.m3u"
ELSE="$tmp_dir/else.m3u"

## First source our functions.
if [[ -n ${SCRIPTDIR+x} ]]; then
    for func in $(find $SCRIPTDIR/mpv-menu -name "_*"); do
        source "$func"
    done
else
    echo " ${red}Your scripts directory environment variable is not set...${nocolor}"
    echo " Just type: ${green}export SCRIPTDIR='/path_to_my_scripts_directory'${nocolor}"
    echo " To set it permanently put it in your .bash_profile or whatever *.profile you're using."
    exit 1
fi

trap "_CleanTmpDir; exit" SIGTERM EXIT

# avoids running multiple instances
mpvmenu=$(basename $0)
pids=($(pidof -x $mpvmenu))

[[ ${#pids[@]} -gt 1 ]] && exit

_CheckDependencies "${@}"

