#!/bin/bash
## This is a part of main script: mpv-menu.

_copy_audio() {

    while (( $(grep "" -c "$QUEUE") > 0 )); do
        echo ""
        echo " Paste an url to fill the playlist:"
        read -r url
        echo "$url" | tee -a "$QUEUE" >> "$URLS_INFO"

        _get_youtubeplaylist_urls
        _remove_crap
        clear

        if (( $(grep "" -c "$QUEUE") < 3 )); then
            echo ""
            echo " ${green}There is $(_get_lines_queue) url in the list${nocolor}."
        else
            echo ""
            echo " ${green}There are $(_get_lines_queue) urls in the list${nocolor}."
        fi

        echo ""
        echo -e "                                                 ::audio options:: "
        echo -e "                             ┌────────────────────────────────────────────────────────────┐"
        echo -e "                             │     1) Add more audio links      4) Play current list      │"
        echo -e "                             │     2) Download current list     5) View current list      │"
        echo -e "                             │     3) Save playlist as          6) Back to main menu      │"
        echo -e "                             └────────────────────────────────────────────────────────────┘"
        echo -e "                                                   ${green}Select an item${nocolor}"
        echo ""
        read -rsn 1 options
        case "$options" in
            1) clear && continue
               echo "" ;;
            2) _get_audio
               echo "" ;;
            3) _save_remove
               echo "" ;;
            4) _check_code_queue && _load_audio
               echo "" ;;
            5) _view_url_info
               echo "" ;;
            6) _check_queue
               echo "" ;;
        esac
    done

}

_copy_video() {

    while (( $(grep "" -c "$QUEUE") > 0 )); do
        echo ""
        echo " Paste an url to fill the playlist:"
        read -r url
        echo "$url" | tee -a "$QUEUE" >> "$URLS_INFO"

        _get_youtubeplaylist_urls
        _remove_crap
        clear

        if (( $(grep "" -c "$QUEUE") < 3 )); then
            echo ""
            echo " ${green}There is $(_get_lines_queue) url in the list${nocolor}."
        else
            echo ""
            echo " ${green}There are $(_get_lines_queue) urls in the list${nocolor}."
        fi

        echo ""
        echo -e "                                                 ::video options:: "
        echo -e "                             ┌────────────────────────────────────────────────────────────┐"
        echo -e "                             │     1) Add more video links      4) Play current list      │"
        echo -e "                             │     2) Download current list     5) View current list      │"
        echo -e "                             │     3) Save playlist as          6) Back to main menu      │"
        echo -e "                             └────────────────────────────────────────────────────────────┘"
        echo -e "                                                   ${green}Select an item${nocolor}"
        echo ""
        read -rsn 1 options
        case "$options" in
            1) clear && continue
               echo "" ;;
            2) _get_video
               echo "" ;;
            3) _save_remove
               echo "" ;;
            4) _check_code_queue && _load_video
               echo "" ;;
            5) _view_url_info
               echo "" ;;
            6) _check_queue
               echo "" ;;
        esac
    done

}
