#!/bin/bash
## This is a part of main script: mpv-menu.

_menu() {

    clear
    while [[ -e $queue ]]; do
        clear
        echo ""
        echo -e "                                          ::mpv-menu options:: "
        echo -e "                      ┌─────────────────────────────────────────────────────────────┐"
        echo -e "                      │   1) Create a video playlist    6) View default playlist    │"
        echo -e "                      │   2) Create an audio playlist   7) Clean default playlist   │"
        echo -e "                      │   3) Save/Remove playlist       8) Edit a playlist          │"
        echo -e "                      │   4) Load a playlist            9) Edit mpv.conf            │"
        echo -e "                      │   5) Load local dir/files       0) Exit                     │"
        echo -e "                      └─────────────────────────────────────────────────────────────┘"
        echo -e "                                             ${green}Select an item${nocolor}"
        echo ""
        read -r action
        case "$action" in
            1)  _copy_video
                echo "" ;;
            2)  _copy_audio
                echo "" ;;
            3)  _save_remove
                echo "" ;;
            4)  _load_playlist
                echo "" ;;
            5)  _load_local
                echo "" ;;
            6)  _view_url
                echo "" ;;
            7)  _delete_url
                echo "" ;;
            8)  _edit_playlist
                echo "" ;;
            9)  _edit_mpv-conf
                echo "" ;;
            0)  clear
                #[[ -z $(systemctl --user list-units | grep -e 'mpv-ipc') ]] \
                #    && systemctl --user start mpv-ipc.service
                # ffmpeg creates a ccache directory while converting/merging files.
                # rm -rf "$HOME"/.ccache
                exit 0 ;;
            *)  echo -e " ${red}Wrong option!\n Wait and try again...${nocolor}"
                sleep 2s
                clear ;;
        esac
    done

}
