#!/usr/bin/env bash

# If we close the last window on a ws then focus the last ws
# otherwise focus the last focused window who was next to the closed one.
# For this to work we have to use typical dk command for closing windows (dkcmd win kill)

[[ -S $DKSOCK ]] && {
    dkcmd win kill
    if ! dkcmd win focus last; then
        dkcmd ws last || dkcmd mon last
    else
        dkcmd win focus last
    fi
}
