#!/bin/bash

# Author: Barret E <archus@protonmail.com>
# This script change workspaces layouts and toggles monocle/previous layout.
# A polybar module is triggered and let us know if we are in static/dynamic mode,
# of course workspaces indicators are renamed as we change layouts (1:G,2:R,3:T etc...)
# Uppercase letters meaning:
# D=dwindle,G=grid,M=mono,N=none,R=rtile,S=spiral,T=tile,W=tstack

pls="$XDG_CACHE_HOME/previous_layouts"
pls_tmp="$XDG_CACHE_HOME/previous_layouts_tmp"

_ApplyLayouts() {
    n=1
    while read -r line; do
        dkcmd set ws="$n" name="$line"
        ((n++))
    done < "$pls"
    rm "$pls"
}

_DefineWorkspaces() {
    case "$1" in
        --dynamic)
            dkcmd set \
                ws=1 name=1 ws=2 name=2 ws=3 name=3 \
                ws=4 name=4 ws=5 name=5 ws=6 name=6 \
                ws=7 name=7 ws=8 name=8 ws=9 name=9
            _ApplyLayouts
            ;;
        --static)
            mon1='DVI-D-0'
            mon2='HDMI-0'
            mon3='DP-0'
            dkcmd set \
                ws=1 name='1:G' mon=$mon1 ws=2 name='2:R' mon=$mon1 ws=3 name='3:R' mon=$mon1 \
                ws=4 name='4:R' mon=$mon2 ws=5 name='5:R' mon=$mon2 ws=6 name='6:R' mon=$mon2 \
                ws=7 name='7:M' mon=$mon3 ws=8 name='8:R' mon=$mon3 ws=9 name='9:R' mon=$mon3
            _ApplyLayouts
            ;;
    esac
}

_NewLayouts() {
    wmctrl -d > "$pls"
    while read -r line; do
        if [[ $line =~ '*' ]]; then
            echo "$line" | sed "s/[A-Z]/${LAYOUT}/g" >> "$pls_tmp"
        else
            echo "$line" >> "$pls_tmp"
        fi
    done < "$pls"
        
    awk '{print $NF}' "$pls_tmp" > "$pls"
    rm "$pls_tmp"
}

static_false=$(dkcmd status type=full num=1 | grep 'static_ws":false')
static_true=$(dkcmd status type=full num=1 | grep 'static_ws":true')

_UpdateLayouts() {
    if [[ $static_false ]]; then
        _NewLayouts
        _DefineWorkspaces --dynamic
    elif [[ $static_true ]]; then
        _NewLayouts
        _DefineWorkspaces --static
    fi
}

# a mode indicator in polybar
_BarStatic() {
    case "$1" in
        --true)
            polybar-msg -p $(pgrep --full dk-bar-3) \
            action "#static_ws-ipc.hook.0" >/dev/null 2>&1
        ;;
        --false)
            polybar-msg -p $(pgrep --full dk-bar-3) \
            action "#static_ws-ipc.hook.1" >/dev/null 2>&1
        ;;
    esac
}

_ChangeMode() {
    if [[ $static_false ]]; then
    
        dkcmd set static_ws=true
        _BarStatic --true
        notify-send 'dk static mode'
        
    elif [[ $static_true ]]; then
    
        dkcmd set static_ws=false
        _BarStatic --false
        notify-send 'dk dynamic mode'
        
    fi
}

_SetLayout() { dkcmd set layout "$1"; }

fdl="$XDG_CACHE_HOME/focused_desktop_layout"
_ToggleMono() {
    if [[ ! -f $fdl ]]; then
        
        dkcmd status type=layout num=1 \
        | jq '.[]' | sed 's/"//g' > "$fdl"
        
        _SetLayout mono
        LAYOUT="M"
        _UpdateLayouts
        
    else
        dkcmd win focus last 2>/dev/null
        _SetLayout "$(cat "$fdl")"
        LAYOUT=$(
            sed '
                s/dwindle/D/g;s/grid/G/g;s/mono/M/g;s/none/N/g;
                s/rtile/R/g;s/spiral/S/g;s/tile/T/g;s/tstack/W/g
            ' < "$fdl"
        )
        _UpdateLayouts
        rm "$fdl"
    fi
}

case "$1" in
    dwindle) LAYOUT="D"; _SetLayout dwindle && _UpdateLayouts ;;
    false) _ChangeMode ;;
    grid) LAYOUT="G"; _SetLayout grid && _UpdateLayouts ;;
    toggle) _ToggleMono && _UpdateLayouts ;;
    none) LAYOUT="N"; _SetLayout none && _UpdateLayouts ;;
    rtile) LAYOUT="R"; _SetLayout rtile && _UpdateLayouts ;;
    spiral) LAYOUT="S"; _SetLayout spiral && _UpdateLayouts ;;
    tile) LAYOUT="T"; _SetLayout tile && _UpdateLayouts ;;
    tstack) LAYOUT="W"; _SetLayout tstack && _UpdateLayouts ;;
esac
