#!/bin/bash

function _WsLayout {
	awk '
	/^workspaces:/ {sub(/^workspaces: /, ""); gsub(/(*)?[0-9]*:\w*:/, ""); print; exit}
	' <(dkcmd status type=full) \
	| sed 's/dwindle/D/g;s/grid/G/g;s/mono/M/g;s/none/N/g;
	s/rtile/R/g;s/spiral/S/g;s/tile/T/g;s/tstack/W/g'
}

function _DynamicTrue {
	# we have to clean the startup workspaces name definition
	# before renaming them with the second block below using wslayout function
	# Note that we don't attribute monitors here.
	dkcmd set \
		ws=1 name=1 \
		ws=2 name=2 \
		ws=3 name=3 \
		ws=4 name=4 \
		ws=5 name=5 \
		ws=6 name=6 \
		ws=7 name=7 \
		ws=8 name=8 \
		ws=9 name=9 \
		ws=10 name=10
	
	# The bar workspaces module will look like this:
	# 1:T 2:S 3:N etc...(name:layout)
	# dwindle=D grid=G mono=M none=N rtile=R spiral=S tile=T tstack=W
	dkcmd set \
		ws=1 name=1:$(_WsLayout | awk '{print $1}') \
		ws=2 name=2:$(_WsLayout | awk '{print $2}') \
		ws=3 name=3:$(_WsLayout | awk '{print $3}') \
		ws=4 name=4:$(_WsLayout | awk '{print $4}') \
		ws=5 name=5:$(_WsLayout | awk '{print $5}') \
		ws=6 name=6:$(_WsLayout | awk '{print $6}') \
		ws=7 name=7:$(_WsLayout | awk '{print $7}') \
		ws=8 name=8:$(_WsLayout | awk '{print $8}') \
		ws=9 name=9:$(_WsLayout | awk '{print $9}') \
		ws=10 name=10:$(_WsLayout | awk '{print $10}')
	
}

function _BarStaticTrue {
	polybar-msg -p $(pgrep --full dk-bar-3) \
	action "#static_ws-ipc.hook.0" >/dev/null 2>&1
}

function _ToggleTileMono {
	
	local last_layouts="$XDG_CACHE_HOME/layouts"
	
	if [[ ! -f $last_layouts ]]; then
		_WsLayout > "$last_layouts"
		dkcmd set layout mono
	else
		rm "$last_layouts"
		# if there was another window next to the focused one
		dkcmd win focus next 2>/dev/null
		dkcmd set layout tile
	fi
}

# change active workspace layout in sxhkdrc
# alt + t ; {d,f,g,n,r,s,t,w}
#### dk_layouts_dynamic -{d,f,g,n,r,s,t,w}
# alt + m
#### dk_layouts_dynamic -m

case "$1" in
    -d) dkcmd set layout dwindle && _DynamicTrue ;;
    -f) dkcmd set static_ws=true && _BarStaticTrue ;;
    -g) dkcmd set layout grid && _DynamicTrue ;;
    -m) _ToggleTileMono && _DynamicTrue ;;
    -n) dkcmd set layout none && _DynamicTrue ;;
    -r) dkcmd set layout rtile && _DynamicTrue ;;
    -s) dkcmd set layout spiral && _DynamicTrue ;;
    -t) dkcmd set layout tile && _DynamicTrue ;;
    -w) dkcmd set layout tstack && _DynamicTrue ;;
esac

