#!/bin/bash

# define layouts array
# mimic dwm style layout symbols
typeset -A layouts=(
[tile]="[]="
[rtile]="=[]"
[mono]="[M]"
[none]="><"
[grid]="###"
[spiral]="(@)"
[dwindle]="[\\]"
[tstack]="F^F"
)

# or use iconic font
# mimic dwm style layout symbols
#typeset -A layouts=(
#[tile]="󰙀"
#[mono]="󰃚"
#[none]="󰕯"
#[grid]="󰕰"
#[spiral]="󰕬"
#[dwindle]="󰕴"
#[tstack]="󱒉"
#)

dkcmd status type=layout num=1 | jq '.[]' | sed 's/"//g'
layout="${layouts[$layout]}"

echo $layout

exit 0;
