#!/usr/bin/env bash

# send/follow all windows from the focused workspace to another one.
# options: dk_sendthemall -s (send) <workspace>
#          dk_sendthemall -f (follow) <workspace>
#
# sxhkd shortcut:
# send/follow all windows of the current ws to ws n°($2)
# super + shift + s ; {_,alt + }{1-9,0}
#     dk_sendthemall -{s,f} {1-9,10}
settings
case "$1" in
    -s)
        for win in $(xdo id -d); do
            dkcmd ws send "$win" "$2"
        done
    ;;
    -f)
        for win in $(xdo id -d); do
            dkcmd ws send "$win" "$2"
        done
        dkcmd ws "$2"
    ;;
esac
