#!/usr/bin/env bash

# move/resize window, signed (+/-) for relative changes
# move/resize ($1) direction ($2)
# change $size to whatever you like.
# alt + ctrl + {h,j,k,l}
    # dkcmd win resize {w=-20,h=+20,h=-20,w=+20}

size=20 ver="" hor=""

case "$1" in
    --move)
        ver="y" hor="x"
    ;;
    --resize)
        ver="h" hor="w"
    ;;
esac

case "$2" in
    Left ) dkcmd win resize "$hor"=-"$size" ;;
    Right) dkcmd win resize "$hor"=+"$size" ;;
    Up   ) dkcmd win resize "$ver"=-"$size" ;;
    Down ) dkcmd win resize "$ver"=+"$size" ;;
esac
