#!/usr/bin/env bash
# ~/.config/mpm/mpmrc (version 2.6-2)

############################################################
############################################################
###'##::::'##:'########::'##::::'##:'########:::'######::###
### ###::'###: ##.... ##: ###::'###: ##.... ##:'##... ##:###
### ####'####: ##:::: ##: ####'####: ##:::: ##: ##:::..::###
### ## ### ##: ########:: ## ### ##: ########:: ##:::::::###
### ##. #: ##: ##.....::: ##. #: ##: ##.. ##::: ##:::::::###
### ##:.:: ##: ##:::::::: ##:.:: ##: ##::. ##:: ##::: ##:###
### ##:::: ##: ##:::::::: ##:::: ##: ##:::. ##:. ######::###
###..:::::..::..:::::::::..:::::..::..:::::..:::......:::###
######### MPV-PLAYLISTS-MANAGER CONFIGURATION FILE #########
########### THE PLACE FOR YOUR PERSONAL SETTINGS ###########
#####~~~ change the values, not the variables names ~~~#####
############################################################

# shellcheck disable=SC2034,SC2016
# : "${XDG_DATA_HOME:-$HOME/.local/share}"
check_updates=no
width=124
height=32
copy_width=124
copy_height=17
schedule_delay=15

########################## THEMES ##########################
mainThemes=(
    default archlabs blacksea c64 dracula embers gotham
    gruvbox jellybeans kasugano monokai nord pistachio retro
    simplicity solarized TokyoNight vacuous yatheme zenburn
)

THEME=simplicity

####################### SYSTEM TOOLS #######################
clipboardCmd=( xclip -out )
FILEMANAGER=ranger
MPMEDITOR=${VISUAL:-vim}
use_somabox=yes

###################### MPM DIRECTORIES ######################
main_dir=${MPM_DIR:-$HOME/.local/share/mpm}
playlists_dir="$main_dir/playlists"
schedules_dir="$main_dir/schedules"
titles_dir="$main_dir/titles"
tmp_dir="$main_dir/tmp"
MUSIC_DIR=${MUZ:-$HOME/Documents/Music}
VIDEO_DIR=${VID:-$HOME/Documents/Videos}
audios_dir="$MUSIC_DIR/mpm_audios"
radios_dir="$MUSIC_DIR/mpd_playlists"
videos_dir="$VIDEO_DIR/mpm_videos"

################### DEFAULT TASKS ANSWERS ###################
keep_none_empty_playlist=yes
direct_download=yes
remove_video_ids=yes
quit_after_task=no

################### GNU PARALLEL OPTIONS ####################
export PARALLEL_HOME="/tmp/parallel"
use_parallel=yes
use_parallel_downloads=yes
parallel_animation=progress
# parallel_animation=spinners
parallel_threads="$(nproc)"
parallel_conversion=yes

################## YT{FZF} FUNCTIONALITIES ##################
use_fzf=yes
fzf_preview=mediainfo
# fzf_preview=exiftool
fzf_preview_size="40%"
fzf_preview_layout=down

ytfzfOptions_KC=( --keep-cache )
ytfzfOptions_PG=( --pages=5 )
ytfzfOptions_VD=( --video-duration=long )
ytfzfOptions_SB=( --sort-by=relevance )
ytfzfOptions_TP=( --type=all )
ytfzfOptions_TV=( --thumb-viewer=mpv )

ytfzfOptions_X=(
    "${ytfzfOptions_KC[@]}"
    "${ytfzfOptions_PG[@]}"
    "${ytfzfOptions_VD[@]}"
    "${ytfzfOptions_SB[@]}"
    "${ytfzfOptions_TP[@]}"
)

############ FFMPEG SPECIFICS (audio conversion) ############
automatic_audio_conversion=no
default_conversion_format=

ffmpegAacCodecOptions=( -acodec aac -ar 48000 -ab 320k )
ffmpegFlacCodecOptions=( -af aformat=s32:48000 )
ffmpegMp3CodecOptions=( -acodec libmp3lame -ar 48000 -ab 320k )
ffmpegOggCodecOptions=( -acodec libvorbis -ar 48000 -ab 320k )
ffmpegWavCodecOptions=( -acodec pcm_s32le -ar 48000 )

####################### MPVC SETTINGS #######################
use_mpvc=yes
# mpvc_tui=ncmpvc
mpvc_tui=native
# mpvc_tui=
nativeThemes=(
    default c64 dark embers gruvbox molokai
    nord retro seoul256 simplicity solarized yatheme
)

native_tui_colors=simplicity
mpvc_tui_cheatsheet="/usr/local/share/doc/mpm/ncmpvc_cheatsheet"

####################### MPV SPECIFICS #######################
mpvGenOptions_AO=( --ao=pulse )
mpvGenOptions_CA=( --cache=yes )
mpvGenOptions_SK=( --input-ipc-server='/tmp/mpvsocket' )
mpvGenOptions_ID=( --idle=no )
mpvGenOptions_CF=( --no-config )
mpvGenOptions_RP=( --no-resume-playback )
mpvGenOptions_MS=( --term-playing-msg='[Title]: ${media-title}' )
mpvGenOptions_UC=( --cookies=no )
mpvGenOptions_HD=( --hwdec=no )

mpvGenOptions_X=(
    "${mpvGenOptions_AO[@]}"
    "${mpvGenOptions_CA[@]}"
    "${mpvGenOptions_HD[@]}"
    "${mpvGenOptions_SK[@]}"
    "${mpvGenOptions_ID[@]}"
    "${mpvGenOptions_RP[@]}"
    "${mpvGenOptions_CF[@]}"
    "${mpvGenOptions_UC[@]}"
)

mpvAudioFormatOptions=( --ytdl-format='bestaudio' )
mpvVideoFormatOptions=( --ytdl-format='bestvideo+bestaudio/best' )

mpvVideoOptions_DM=( --demuxer-max-bytes=1024MiB )
mpvVideoOptions_DR=( --demuxer-readahead-secs=60 )
mpvVideoOptions_DB=( --demuxer-max-back-bytes=256MiB )
mpvVideoOptions_FS=( --fullscreen=yes )

mpvVideoOptions_X=(
    "${mpvVideoOptions_FS[@]}"
    "${mpvVideoOptions_DM[@]}"
    "${mpvVideoOptions_DR[@]}"
    "${mpvVideoOptions_DB[@]}"
)

###################### YT-DLP PRESETS ######################
# default_video_resolution="1080"
ytdlPreset_BR=( --break-on-existing )
ytdlPreset_BC=( --cookies-from-browser=brave )
ytdlPreset_DN=( --downloader m3u8:native )
ytdlPreset_DP=( --progress )
ytdlPreset_DW=( --no-warnings --ignore-errors )
ytdlPreset_FS=( --compat-options filename-sanitization )
ytdlPreset_MF=( --merge-output-format mp4 )

ytdlPreset_NC=(
    "${ytdlPreset_BR[@]}"
    "${ytdlPreset_DN[@]}"
    "${ytdlPreset_DP[@]}"
    "${ytdlPreset_DW[@]}"
    "${ytdlPreset_FS[@]}"
)

ytdlPreset_X=(
    "${ytdlPreset_NC[@]}"
    "${ytdlPreset_MF[@]}"
)

ytdlPreset_MR=( '"bestvideo[height<=?1080][vcodec!=vp9]+bestaudio/best"' )
ytdlPreset_NR=( 50 )
