#!/bin/bash
# ~/.config/mpm/mpmrc (version 2.0-2)

########################################################
#                                                      #
#    ███╗   ███╗██████╗ ███╗   ███╗██████╗  ██████╗    #
#    ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔════╝    #
#    ██╔████╔██║██████╔╝██╔████╔██║██████╔╝██║         #
#    ██║╚██╔╝██║██╔═══╝ ██║╚██╔╝██║██╔══██╗██║         #
#    ██║ ╚═╝ ██║██║     ██║ ╚═╝ ██║██║  ██║╚██████╗    #
#    ╚═╝     ╚═╝╚═╝     ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝    #
#                                                      #
####### MPV-PLAYLISTS-MANAGER CONFIGURATION FILE #######
######### THE PLACE FOR YOUR PERSONAL SETTINGS #########
#~~~~~ change the values, not the variables names ~~~~~#

# shellcheck disable=SC2034,SC2016,SC2154
: "${XDG_DATA_HOME:-$HOME/.local/share}"

check_updates="no"
width=1260
height=738

# AVAILABLE THEMES: default, dracula, blacksea, chocolat-pistache, gruvbox, gotham,
# jellybeans, monokai, nord, TokyoNight, solarized, vacuous, zenburn, zorange
THEME="blacksea"

####################### SYSTEM TOOLS ######################
MPMEDITOR=${VISUAL:-vim}
FILEMANAGER="ranger"
clipboardCmd=( xclip -out )

##################### MPM DIRECTORIES #####################
MUSIC_DIR="$HOME/Documents/Music"
VIDEO_DIR="$HOME/Documents/Videos"
main_dir="$XDG_DATA_HOME/mpm"
playlists_dir="$main_dir/playlists"
audios_dir="$MUSIC_DIR/mpm_audios"
videos_dir="$VIDEO_DIR/mpm_videos"
titles_dir="$main_dir/titles"
tmp_dir="$main_dir/tmp"

################### DEFAULT TASKS ANSWERS ##################
keep_none_empty_playlist="yes"
direct_download="yes"
quit_after_task="no"

################### GNU PARALLEL OPTIONS ###################
use_parallel="yes"
use_parallel_downloads="yes"
# parallel_animation="progress"
parallel_animation="spinners"
parallel_threads="$(nproc)"
parallel_conversion="yes"

#################### FZF FUNCTIONALITY #####################
use_fzf="yes"
fzf_preview="mediainfo"
# fzf_preview="exiftool"
fzf_preview_size="40%"
fzf_preview_layout="down"

ytfzfOptions_KC=( --keep-cache )
ytfzfOptions_PG=( --pages=5 )
ytfzfOptions_VD=( --video-duration=long )
ytfzfOptions_SB=( --sort-by=relevance )
ytfzfOptions_TY=( --type=all )
# ytfzfOptions_TV=( --thumb-viewer=mpv )

ytfzfOptions_X=(
    "${ytfzfOptions_KC[@]}"
    "${ytfzfOptions_PG[@]}"
    "${ytfzfOptions_VD[@]}"
    "${ytfzfOptions_SB[@]}"
    "${ytfzfOptions_TY[@]}"
)

############ FFMPEG SPECIFICS (audio conversion) ############
automatic_audio_conversion="yes"
default_conversion_format="flac"

ffmpegAacCodecOptions=( -acodec aac -ar 48000 -ab 320k )
ffmpegFlacCodecOptions=( -af aformat=s32:48000 )
ffmpegMp3CodecOptions=( -acodec libmp3lame -ar 48000 -ab 320k )
ffmpegOggCodecOptions=( -acodec libvorbis -ar 48000 -ab 320k )
ffmpegWavCodecOptions=( -acodec pcm_s32le -ar 48000 )

####################### MPV SPECIFICS #######################
use_mpvc="yes"
mpvc_tui="ncmpvc"
#mpvc_tui=""

mpvGenOptions_CA=( --cache=yes )
mpvGenOptions_SK=( --input-ipc-server='/tmp/mpvsocket' )
mpvGenOptions_ID=( --idle=no )
mpvGenOptions_CF=( --no-config )
mpvGenOptions_RP=( --no-resume-playback )
mpvGenOptions_MS=( --term-playing-msg='[Title]: ${media-title}' )

mpvGenOptions_X=(
    "${mpvGenOptions_CA[@]}"
    "${mpvGenOptions_SK[@]}"
    "${mpvGenOptions_ID[@]}"
    "${mpvGenOptions_CF[@]}"
    "${mpvGenOptions_RP[@]}"
    "${mpvGenOptions_MS[@]}"
)

mpvAudioFormatOptions=( --ytdl-format='bestaudio/best' )
mpvVideoFormatOptions=( --ytdl-format='bestvideo+bestaudio/best' )

mpvVideoOptions_DM=( --demuxer-max-bytes=1024MiB )
mpvVideoOptions_DR=( --demuxer-readahead-secs=60 )
mpvVideoOptions_DB=( --demuxer-max-back-bytes=256MiB )
mpvVideoOptions_FS=( --fullscreen=yes )

mpvVideoOptions_X=(
    "${mpvVideoOptions_FS[@]}"
    "${mpvVideoOptions_DM[@]}"
    "${mpvVideoOptions_DR[@]}"
    "${mpvVideoOptions_DB[@]}"
)

################ YT-DLP PRESETS (youtube-dl) ################
ytdlPreset_BR=( --break-on-existing )
ytdlPreset_DN=( --downloader m3u8:native )
ytdlPreset_MF=( --merge-output-format mp4 )
ytdlPreset_DW=( --no-warnings --ignore-errors )
ytdlPreset_DP=( --progress )
ytdlPreset_FS=( --compat-options filename-sanitization )

ytdlPreset_NC=(
    "${ytdlPreset_BR[@]}"
    "${ytdlPreset_DW[@]}"
    "${ytdlPreset_DP[@]}"
    "${ytdlPreset_FS[@]}"
)

ytdlPreset_X=(
    "${ytdlPreset_MF[@]}"
    "${ytdlPreset_DN[@]}"
    "${ytdlPreset_FS[@]}"
    "${ytdlPreset_BR[@]}"
    "${ytdlPreset_DW[@]}"
    "${ytdlPreset_DP[@]}"
)
