#!/usr/bin/env bash
# ~/.config/mpm/themerc (version 2.4-4)

######################################################################
#                                                                    #
#    ████████╗██╗  ██╗███████╗███╗   ███╗███████╗██████╗  ██████╗    #
#    ╚══██╔══╝██║  ██║██╔════╝████╗ ████║██╔════╝██╔══██╗██╔════╝    #
#       ██║   ███████║█████╗  ██╔████╔██║█████╗  ██████╔╝██║         #
#       ██║   ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝  ██╔══██╗██║         #
#       ██║   ██║  ██║███████╗██║ ╚═╝ ██║███████╗██║  ██║╚██████╗    #
#       ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝    #
#                                                                    #
########### MPV-PLAYLISTS-MANAGER THEME CONFIGURATION FILE ###########
#~~~~~~~~~~~~ change the values, not the variables names ~~~~~~~~~~~~#

# shellcheck disable=SC2034,SC2016,SC2154

###################### PROMPTS & MESSAGES COLORS ######################
### https://misc.flogisoft.com/bash/tip_colors_and_formatting
### Console_colors (default) will always use your current ~/.Xresources colors,
### or custom rgb/hex colors so you can set your own theme.
### nc=normal text, critical=warnings, info=normal prompt, mtitle=menus title,
### task=infos like: direct download, audio conversion type etc...
### customColors is called from lib/_LittleStars function.

# set your default background color here, it will be used when you quit the app.
# default_bg="#1e1f29"
default_bg=$(xrdb -query | awk '/background:/{print $NF}')

_NativePlayerColors() {

    # double quotes for the FZF_DEFAULT_OPTS if you want to use variables.
    case "$1" in
        default)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#87afaf
                --color=fg:#af5faa,fg+:#ffffff,bg:$default_bg,bg+:#2e3944
                --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87
                --color=prompt:#af5fff,spinner:#af5fff,pointer:#af5fff
                --color=border:#554476,label:#af5faa,query:#d9d9d9
                --border-label-pos='102:bottom'
                --border-label '[ theme: default ]'
            "
        ;;
        c64)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#DD8855
                --color=fg:#0088FF,fg+:#ffffff,bg:#0000AA,bg+:#0000AA
                --color=hl:#FF7777,hl+:#AAFF66,info:#AAFFEE
                --color=prompt:#AAFF66,spinner:#880000,pointer:#CC44CC
                --color=border:#BBBBBB,label:#EEEE77,query:#BBBBBB
                --border-label-pos='106:bottom'
                --border-label '[ theme: c64 ]'
            "
        ;;
        dark)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#5f87af
                --color=fg:#d0d0d0,fg+:#d0d0d0,bg:#121212,bg+:#262626
                --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87
                --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff
                --color=border:#262626,label:#d0d0d0,query:#d9d9d9
                --border-label-pos='105:bottom'
                --border-label '[ theme: dark ]'
            "
        ;;
        gruvbox)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#928374
                --color=fg:#ebdbb2,fg+:#ebdbb2,bg:#32302f,bg+:#3c3836
                --color=hl:#928374,hl+:#fb4934,info:#8ec07c
                --color=prompt:#fb4934,spinner:#fb4934,pointer:#fb4934
                --color=preview-bg:#3c3836
                --color=border:#6B6B6B,label:#ebdbb2,query:#d9d9d9
                --border-label-pos='102:bottom'
                --border-label '[ theme: gruvbox ]'
                "
        ;;
        molokai)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#7E8E91
                --color=bg+:#293739,bg:#1B1D1E,border:#808080
                --color=spinner:#E6DB74,hl:#7E8E91,fg:#F8F8F2
                --color=info:#A6E22E,pointer:#A6E22E,fg+:#F8F8F2
                --color=prompt:#F92672,hl+:#F92672
                --border-label-pos='102:bottom'
                --border-label '[ theme: molokai ]'
            "
        ;;
        nord)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#616E88
                --color=bg+:#3B4252,bg:#2E3440,border:#6B6B6B
                --color=spinner:#81A1C1,hl:#616E88,fg:#D8DEE9
                --color=info:#81A1C1,pointer:#81A1C1,fg+:#D8DEE9
                --color=preview-bg:#3B4252,prompt:#81A1C1,hl+:#81A1C1
                --border-label-pos='105:bottom'
                --border-label '[ theme: nord ]'
            "
        ;;
        retro)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#389844
                --color=bg+:#000000,bg:#000000,border:#6b946c
                --color=spinner:#b8ffc5,hl:#6b946c,fg:#48b854
                --color=info:#98E5A5,pointer:#6b946c,fg+:#55E667
                --color=preview-bg:#000000,prompt:#389844,hl+:#98E5A5
                --border-label-pos='105:bottom'
                --border-label '[ theme: retro ]'
            "
        ;;
        seoul256)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#719872
                --color=bg+:#3F3F3F,bg:#4B4B4B,border:#6B6B6B
                --color=spinner:#98BC99,hl:#719872,fg:#D9D9D9
                --color=info:#BDBB72,pointer:#E12672,fg+:#D9D9D9
                --color=preview-bg:#3F3F3F,prompt:#98BEDE,hl+:#98BC99
                --border-label-pos='101:bottom'
                --border-label '[ theme: seoul256 ]'
            "
        ;;
        solarized)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#859900
                --color=bg+:#002b36,bg:#002b36,border:#859900
                --color=spinner:#98BC99,hl:#719872,fg:#839496
                --color=info:#2AA198,pointer:#DC322F,fg+:#B58900
                --color=preview-bg:#003340,prompt:#DC322F,hl+:#2AA198
                --border-label-pos='101:bottom'
                --border-label '[ theme: solarized ]'
            "
        ;;
        yatheme)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#94B7D0
                --color=fg:#94B7D0,fg+:#50d2f3,bg:#28628B,bg+:#28628B
                --color=hl:#8be99c,hl+:#2ada56,info:#afaf87
                --color=prompt:#6E8AFF,spinner:#c45fff,pointer:#C8FF41
                --color=border:#94B7D0,label:#50D2F3,query:#d9d9d9,preview-bg:#265D85
                --border-label-pos='102:bottom'
                --border-label '[ theme: yatheme ]'
            "
        ;;
    esac

}

_Theme() {

    case "$1" in
        default)
            bg="$default_bg"
            nc=$'\e[0m';
            critical=$'\e[31m';
            info=$'\e[32m';
            mtitle=$'\e[33m';
            task=$'\e[37m';
        ;;
        archlabs)
            # Using HEX colors for array 'customColors'
            bg="#21232e"
            nc=$'\e[38;2;143;161;179m';       #8FA1B3 "0x8f 0xa1 0xb3"
            critical=$'\e[38;2;191;97;106m';  #BF616A "0xbf 0x61 0x6a"
            info=$'\e[38;2;163;190;140m';     #A3BE8C "0xa3 0xbe 0xc8"
            mtitle=$'\e[38;2;235;203;139m';   #EBCB8B "0xeb 0xcb 0x8b"
            task=$'\e[38;2;192;197;206m';     #C0C5CE "0xc0 0xc5 0xce"
            customColors=( "0x8f 0xa1 0xb3" "0xbf 0x61 0x6a" "0xa3 0xbe 0xc8" \
            "0xeb 0xcb 0x8b" "0xc0 0xc5 0xce" )
        ;;
        blacksea)
            # Using HEX colors for array 'customColors'
            bg="$default_bg"
            nc=$'\e[38;2;118;114;232m';       #7672E8 "0x76 0x72 0xe8"
            critical=$'\e[38;2;160;109;78m';  #A06D4E "0xa0 0x6d 0x4e"
            info=$'\e[38;2;105;176;191m';     #69B0BF "0x69 0xb0 0xbf"
            mtitle=$'\e[38;2;129;124;92m';    #817C5C "0x81 0x7c 0x5c"
            task=$'\e[38;2;248;248;240m';     #f8f8f0 "0xf8 0xf8 0xf0"
            customColors=( "0x76 0x72 0xe8" "0xa0 0x6d 0x4e" "0x69 0xb0 0xbf" \
            "0x81 0x7c 0x5c" "0xf8 0xf8 0xf0" )
        ;;
        c64)
            bg="#0000AA"
            nc=$'\e[38;2;0;136;255m';         #0088ff "0x00 0x88 0xff"
            critical=$'\e[38;2;207;6;6m';     #cf0606 "0xcf 0x06 0x06"
            info=$'\e[38;2;170;255;102m';     #AAFF66 "0xaa 0xff 0x66"
            mtitle=$'\e[38;2;170;255;238m';   #AAFFEE "0xaa 0xff 0xee"
            task=$'\e[38;2;255;255;255m';     #ffffff "0xff 0xff 0xff"
            customColors=( "0x00 0x88 0xff" "0xcf 0x06 0x06" "0xaa 0xff 0x66" \
            "0xaa 0xff 0xee" "0xff 0xff 0xff" )
        ;;
        dracula)
            bg="#282a36"
            nc=$'\e[38;2;189;147;249m';       #BD93F9 "0xbd 0x93 0xf9"
            critical=$'\e[38;2;255;85;85m';   #FF5555 "0xff 0x55 0x55"
            info=$'\e[38;2;80;250;123m';      #50FA7B "0x50 0xfa 0x7b"
            mtitle=$'\e[38;2;241;250;140m';   #F1FA8C "0xf1 0xfa 0x8c"
            task=$'\e[38;2;191;191;191m';     #BFBFBF "0xbf 0xbf 0xbf"
            customColors=( "0xbd 0x93 0xf9" "0xff 0x55 0x55" "0x50 0xfa 0x7b" \
            "0xf1 0xfa 0x8c" "0xbf 0xbf 0xbf" )
        ;;
        embers)
            bg="$default_bg"
            nc=$'\e[38;2;153;140;130m';       #998C82 "0x99 0x8c 0x82"
            critical=$'\e[38;2;130;87;109m';  #82576d "0x82 0x57 0x6d"
            info=$'\e[38;2;87;130;109m';      #57826d "0x57 0x82 0x6d"
            mtitle=$'\e[38;2;120;125;87m';    #787D57 "0x78 0x7d 0x57"
            task=$'\e[38;2;87;109;130m';      #576d82 "0x57 0x6d 0x82"
            customColors=( "0x99 0x8c 0x82" "0x82 0x57 0x6d" "0x57 0x82 0x6d" \
            "0x78 0x7d 0x57" "0x57 0x6d 0x82" )
        ;;
        gotham)
            bg="#251930"
            nc=$'\e[38;2;25;84;101m';         #195465 "0x19 0x54 0x65"
            critical=$'\e[38;2;210;105;57m';  #d26939 "0xd2 0x69 0x39"
            info=$'\e[38;2;38;169;139m';      #26A98B "0x26 0xa9 0x8b"
            mtitle=$'\e[38;2;237;181;75m';    #EDB54B "0xed 0xb5 0x4b"
            task=$'\e[38;2;89;156;170m';      #599caa "0x59 0x9c 0xaa"
            customColors=( "0x19 0x54 0x65" "0xd2 0x69 0x39" "0x26 0xa9 0x8b" \
            "0xed 0xb5 0x4b" "0x59 0x9c 0xaa" )
        ;;
        gruvbox)
            # Using RGB colors for array 'customColors'
            bg="#32302f"
            nc=$'\e[38;2;69;133;136m';        #458588 "0x45 0x85 0x88"
            critical=$'\e[38;2;204;36;29m';   #CC241D "0xcc 0x24 0x1d"
            info=$'\e[38;2;104;157;106m';     #689d6a "0x68 0x9d 0x6a"
            mtitle=$'\e[38;2;215;153;33m';    #D79921 "0xd7 0x99 0x21"
            task=$'\e[38;2;235;219;178m';     #ebdbb2 "0xeb 0xdb 0xb2"
            # enter the last three numbers of your custom sequence.
                        #   normal text  critical      info          mtitle       task
            customColors=( "69;133;136" "204;36;29" "104;157;106" "215;153;33" "235;219;178" )
        ;;
        jellybeans)
            # Using HEX colors for array 'customColors'
            bg="#121212"
            nc=$'\e[38;2;89;123;197m';        #597bc5 "0x59 0x7b 0xc5"
            critical=$'\e[38;2;207;106;76m';  #cf6a4c "0xcf 0x6a 0x4c"
            info=$'\e[38;2;153;173;106m';     #99ad6a "0x99 0xad 0x6a"
            mtitle=$'\e[38;2;216;173;76m';    #d8ad4c "0xd8 0xad 0x4c"
            task=$'\e[38;2;113;185;248m';     #a9a9a9 "0xa9 0xa9 0xa9"
            customColors=( "0x59 0x7b 0xc5" "0xcf 0x6a 0x4c" "0x99 0xad 0x6a" \
            "0xd8 0xad 0x4c" "0xa9 0xa9 0xa9" )
        ;;
        kasugano)
            # Using HEX colors for array 'customColors'
            bg="$default_bg"
            nc=$'\e[38;2;137;207;240m';       #89CFF0 "0x89 0xcf 0xf0"
            critical=$'\e[38;2;102;115;191m'; #6673bf "0x66 0x73 0xbf"
            info=$'\e[38;2;62;162;144m';      #3ea290 "0x3e 0xa2 0x90"
            mtitle=$'\e[38;2;176;234;217m';   #b0ead9 "0xb0 0xea 0xd9"
            task=$'\e[38;2;130;146;178m';     #8292b2 "0x82 0x92 0xb2"
            customColors=( "0x89 0xcf 0xf0" "0x66 0x73 0xbf" "0x3e 0xa2 0x90" \
            "0xb0 0xea 0xd9" "0x82 0x92 0xb2" )
        ;;
        monokai)
            # Using RGB colors for array 'customColors'
            bg="#2e2e2e"
            nc=$'\e[38;2;102;217;239m';       #66d9ef "0x66 0xd9 0xef"
            critical=$'\e[38;2;249;38;114m';  #F92672 "0xf9 0x26 0x72"
            info=$'\e[38;2;166;226;46m';      #A6E22E "0xa6 0xe2 0x2e"
            mtitle=$'\e[38;2;244;191;171m';   #F4BF75 "0xf4 0xbf 0x75"
            task=$'\e[38;2;248;248;242m';     #F8F8F2 "0xf8 0xf8 0xf2"
            # enter the last three numbers of your custom sequence.
                        #   normal text   critical      info          mtitle       task
            customColors=( "102;217;239" "249;38;114" "166;226;46" "244;191;171" "248;248;242" )
        ;;
        nord)
            # Using RGB colors for array 'customColors'
            bg="#2e3440"
            nc=$'\e[38;2;129;161;193m';       #81a1c1 "0x81 0xa1 0xc1"
            critical=$'\e[38;2;191;97;106m';  #bf616a "0xbf 0x61 0x6a"
            info=$'\e[38;2;163;190;140m';     #a3be8c "0xa3 0xbe 0x8c"
            mtitle=$'\e[38;2;235;203;139m';   #ebcb8b "0xeb 0xcb 0x8b"
            task=$'\e[38;2;136;192;208m';     #88c0d0 "0x88 0xc0 0xd0"
            # enter the last three numbers of your custom sequence.
                        #   normal text   critical      info          mtitle       task
            customColors=( "129;161;193" "191;97;106" "163;190;140" "235;203;139" "136;192;208" )
        ;;
        pistachio)
            bg="#201b1e"
            nc=$'\e[38;2;146;196;113m';       #92C471 "0x92 0xc4 0x71"
            critical=$'\e[38;2;215;95;65m';   #D75F41 "0xd7 0x5f 0x41"
            info=$'\e[38;2;146;196;113m';     #92C471 "0x92 0xc4 0x71"
            mtitle=$'\e[38;2;242;203;87m';    #F2CB57 "0xf2 0xcb 0x57"
            task=$'\e[38;2;249;230;176m';     #F9E6B0 "0xf9 0xe6 0xb0"
            customColors=( "0x92 0xc4 0x71" "0xd7 0x5f 0x41" "0x92 0xc4 0x71" \
            "0xf2 0xcb 0x57" "0xf9 0xe6 0xb0" )
        ;;
        retro)
            bg="#000000"
            nc=$'\e[38;2;56;152;68m';         #389844 "0x38 0x98 0x44"
            critical=$'\e[38;2;107;148;108m'; #6b946c "0x6b 0x94 0x6c"
            info=$'\e[38;2;152;229;165m';     #98E5A5 "0x98 0xe5 0xa5"
            mtitle=$'\e[38;2;56;152;68m';     #389844 "0x38 0x98 0x44"
            task=$'\e[38;2;107;148;108m';     #6b946c "0x6b 0x94 0x6c"
            customColors=( "0x38 0x98 0x44" "0x6b 0x94 0x6c" "0x98 0xe5 0xa5" \
            "0x38 0x98 0x44" "0x6b 0x94 0x6c" )
        ;;
        simplicity)
            bg="$default_bg"
            nc=$'\e[38;2;119;136;153m';       #778899 "0x77 0x88 0x99"
            critical=$'\e[38;2;191;92;86m';   #BF5C56 "0xbf 0x5c 0x56"
            info=$'\e[38;2;151;177;156m';     #97B19C "0x97 0xb1 0x9c"
            mtitle=$'\e[38;2;215;189;138m';   #D7BD8A "0xd7 0xbd 0x8a"
            task=$'\e[38;2;243;243;243m';     #f3f3f3 "0xf3 0xf3 0xf3"
            customColors=( "0x77 0x88 0x99" "0xbf 0x5c 0x56" "0x97 0xb1 0x9c" \
            "0xd7 0xbd 0x8a" "0xf3 0xf3 0xf3" )
        ;;
        TokyoNight)
            bg="#1f2335"
            nc=$'\e[38;2;169;177;214m';       #A9B1D6 "0xa9 0xb1 0xd6"
            critical=$'\e[38;2;197;59;83m';   #c53b53 "0xc5 0x3b 0x53"
            info=$'\e[38;2;195;232;141m';     #c3e88d "0xc3 0xe8 0x8d"
            mtitle=$'\e[38;2;255;158;100m';   #ff9e64 "0xff 0x9e 0x64"
            task=$'\e[38;2;125;207;255m';     #7DCFFF "0x7d 0xcf 0xff"
            customColors=( "0xa9 0xb1 0xd6" "0xc5 0x3b 0x53" "0xc3 0xe8 0x8d" \
            "0xff 0x9e 0x64" "0x7d 0xcf 0xff" )
        ;;
        solarized)
            bg="#002b36"
            nc=$'\e[38;2;131;148;150m';       #839496 "0x83 0x94 0x96"
            critical=$'\e[38;2;220;50;47m';   #DC322F "0xdc 0x32 0x2f"
            info=$'\e[38;2;133;153;0m';       #859900 "0x85 0x99 0x00"
            mtitle=$'\e[38;2;181;137;0m';     #B58900 "0xb5 0x89 0x00"
            task=$'\e[38;2;42;161;152m';      #2AA198 "0x2a 0xa1 0x98"
            customColors=( "0x83 0x94 0x96" "0xdc 0x32 0x2f" "0x85 0x99 0x00" \
            "0xb5 0x89 0x00" "0x2a 0xa1 0x98" )
        ;;
        vacuous)
            bg="$default_bg"
            nc=$'\e[38;2;116;145;161m';       #7491A1 "0x74 0x91 0xa1"
            critical=$'\e[38;2;209;69;72m';   #D14548 "0xd1 0x45 0x48"
            info=$'\e[38;2;167;183;154m';     #A7B79A "0xa7 0xb7 0x9a"
            mtitle=$'\e[38;2;249;187;128m';   #F9BB80 "0xf9 0xbb 0x80"
            task=$'\e[38;2;15;130;157m';      #0F829D "0x0f 0x82 0x9d"
            customColors=( "0x74 0x91 0xa1" "0xd1 0x45 0x48" "0xa7 0xb7 0x9a" \
            "0xf9 0xbb 0x80" "0x0f 0x82 0x9d" )
        ;;
        yatheme)
            bg="#28628B"
            nc=$'\e[38;2;148;183;208m';       #94B7D0 "0x94 0xb7 0xd0"
            critical=$'\e[38;2;196;95;255m';  #c45fff "0xc4 0x5f 0xff"
            info=$'\e[38;2;139;233;156m';     #8be99c "0x8b 0xe9 0x9c"
            mtitle=$'\e[38;2;175;175;135m';   #afaf87 "0xaf 0xaf 0x87"
            task=$'\e[38;2;80;210;243m';      #50D2F3 "0x50 0xd2 0xf3"
            customColors=( "0x94 0xb7 0xd0" "0xc4 0x5f 0xff" "0x8b 0xe9 0x9c" \
            "0xaf 0xaf 0x87" "0x50 0xd2 0xf3" )
        ;;
        zenburn)
            bg="#1f1f1f"
            nc=$'\e[38;2;220;220;204m';       #DCDCCC "0xdc 0xdc 0xcc"
            critical=$'\e[38;2;198;92;92m';   #C65C5C "0xc6 0x5c 0x5c"
            info=$'\e[38;2;96;180;138m';      #60B48A "0x60 0xb4 0x8a"
            mtitle=$'\e[38;2;240;223;175m';   #F0DFAF "0xf0 0xdf 0xaf"
            task=$'\e[38;2;79;122;167m';      #4F7AA7 "0x4f 0x7a 0xa7"
            customColors=( "0xdc 0xdc 0xcc" "0xc6 0x5c 0x5c" "0x60 0xb4 0x8a" \
            "0xf0 0xdf 0xaf" "0x4f 0x7a 0xa7" )
        ;;
        zorange)
            bg="#000000"
            nc=$'\e[38;2;248;116;0m';         #f87400 "0xf8 0x74 0x00"
            critical=$'\e[38;2;248;66;0m';    #f84200 "0xf8 0x42 0x00"
            info=$'\e[38;2;248;155;41m';      #f89b29 "0xf8 0x9b 0x29"
            mtitle=$'\e[38;2;240;187;17m';    #f0bb11 "0xf0 0xbb 0x11"
            task=$'\e[38;2;240;162;17m';      #f0a211 "0xf0 0xa2 0x11"
            customColors=( "0xf8 0x74 0x00" "0xf8 0x42 0x00" "0xf8 0x9b 0x29" \
            "0xf0 0xbb 0x11" "0xf0 0xa2 0x11" )
        ;;
    esac

}
